- packages/forms-web-app/src/app.js
- packages/forms-web-app/src/middleware/flash-message-cleanup.js
- packages/forms-web-app/src/middleware/flash-message-to-nunjucks.js
- packages/forms-web-app/src/views/components/flash-message.njk
- packages/forms-web-app/src/views/cookies.njk
- packages/forms-web-app/src/views/layouts/layout.njk
- packages/forms-web-app/src/views/layouts/main.njk
- packages/forms-web-app/src/views/messages/cookies-updated-successfully.njk
Brought across some missing aspects from Appeals service.
Took liberty of adding question and changing option labels on cookie information page to make it clearer what question is being asked of the user which more closely aligns with the latest thinking in the GOV.UK Design System cookie component.
> ASB-153: Got cookie information page working

- e2e-tests/cypress/integration/registration/organisation/what-is-your-job-title-or-volunteer-role.feature
- packages/forms-web-app/src/validators/register/organisation/role.js
Also added a few more examples to acceptance tests to prove job titles with 2 and 3 characters are accepted.
> ASB-123: Corrected implementation to only require 1 character as the minimum length

- pipelines/applications-service-api/applications-service-api-cd.yml
- pipelines/forms-web-app/forms-web-app-cd.yml
The CD pipeline was triggering when the CI pipeline completed on the `main` branch. However, it was triggering for all environments instead of just Dev. This is because the condition was missing the 'ResourceTrigger' reason.
> Fix CD pipeline deploying all envs when triggered by CI pipeline

- docker-compose.yml
- packages/applications-service-api/database/config/config.js
Changed DB config to be sourced exclusively from environment variables instead of trying to manage environment variations within app code.   Updated docker-compose file used locally to provide relevant values for the MYSQL_ environment variables.
This resolves an issue which was uncovered when deploying to a new development environment with `NODE_ENV` set to something other than `development`, in this case it was set to `production` yet ended up with "local" database configuration values 🙈
> Changed DB config to be sourced exclusively from environment variables

- packages/applications-service-api/__tests__/unit/controllers/interested-party.test.js
- packages/applications-service-api/src/services/interested-party.service.js
Fixed an issue where if a user saves and exits, then returns and completes registration with their original comment unchanged, they do not receive a confirmation email. This is because the code was relying upon the number of rows affected by a MySQL UPDATE.  In the event the comment is the same as what is already persisted, the number of rows is affected is returned as 0.
> Fixed an issue where registration confirmation email is not sent

- packages/forms-web-app/src/views/register/agent/are-they-18-over.njk
Corrected hint text parameter name so hint text will get correctly displayed
> ASB-259: Content update under H1 on 'Over 18' pages

- packages/applications-service-api/__tests__/unit/controllers/document-filter.test.js
- packages/applications-service-api/__tests__/unit/controllers/documents.test.js
- packages/applications-service-api/src/controllers/documents.js
- packages/forms-web-app/__tests__/unit/controllers/projects/documents.test.js
- packages/forms-web-app/src/controllers/projects/documents.js
- packages/forms-web-app/src/views/projects/documents.njk
Changed v2 documents endpoint to longer return 404 but instead an empty list when no documents are found. Changed frontend to handle an empty list of documents with no search and filters differently than when there is an empty list of documents due to search and/or filtering
> ASB-185: Handle no documents available vs no documents found properly

- packages/applications-service-api/__tests__/unit/controllers/representations.test.js
- packages/applications-service-api/src/controllers/representations.js
- packages/forms-web-app/src/views/projects/representations.njk
Changed representations endpoint to longer return 404 but instead an empty list when no representations found.   Changed frontend to handle an empty list of representations
> ASB-288: Change handling of no representations found

- packages/forms-web-app/src/views/layouts/project-2-columns.njk
- packages/forms-web-app/src/views/layouts/project-3-columns.njk
- packages/forms-web-app/src/views/layouts/project.njk
Fixed an issue with the alignment of the header, phase banner and main content by removing unnecessary margin classes.  Now, the PINS header, phase banner, project heading and project menu are properly aligned.
Before:
After:
> Addressed a few styling issues

- packages/applications-service-api/pipelines/azure-pipelines-build.yml
- packages/applications-service-api/pipelines/azure-pipelines-release.yml
- packages/common/pipelines/azure-pipelines-build.yml
- packages/forms-web-app/pipelines/azure-pipelines-build.yml
- packages/forms-web-app/pipelines/azure-pipelines-release.yml
Updated release pipelines for web and API apps to utilize [App Service slots](https://docs.microsoft.com/en-us/azure/app-service/deploy-staging-slots) for deployments. Containers are first deployed to a staging slot, then the staging slot is swapped with the current production slot.
This method of deployment decreases downtime from the end-user perspective during deployments and allows developers to swap back to the previous deployment by swapping the deployment slots, rather than needing to redeploy an old version of the app.
Both release pipelines were manually run against this branch prior to merge to confirm that both apps were successfully deployed to their respective App Service staging slot, then those slots swapped into production.
> Update release pipelines to use App Service slots

- packages/applications-service-api/pipelines/azure-pipelines-build.yml
- packages/applications-service-api/pipelines/azure-pipelines-release.yml
- packages/common/pipelines/azure-pipelines-build.yml
- packages/forms-web-app/pipelines/azure-pipelines-build.yml
- packages/forms-web-app/pipelines/azure-pipelines-release.yml
Updates pipelines to version 2.5.3.
The pipeline now works in 2 stages. First, it will deploy the changes to the Azure App Service Slot called "staging". Then it will swap the "production" and "staging" slots. Since there is an approval step in between, this gives the possibility to run some smoke tests against the staging slot.
The deployment is now done via a webhook from the pipeline (instead of previously from the container registry) so this fixes the issue where the webook was being sent over the internet instead of via the Virtual Network.
> chore(pipelines): update to pipelines version 2.5.3

- packages/applications-service-api/package.json
- packages/common/package.json
- packages/forms-web-app/package.json
Limit npm and node versions to attempt to fix the issue of chokidar not being available.
From research it appears that versions of npm above 7 can cause issues with chokidar
> build(package.json): limit npm and node versions

- azure-pipelines-build.yml
- azure-pipelines-deploy.yml
- azure-pipelines-release.yml
When the pipeline runs after a merge to `main`, the build steps were being skipped. Since it's quite difficult in ADO to get variables from another pipeline, it's better to just run all steps when merging to `main` I think.
> ci: fix build steps not running on main branch pipeline runs

- packages/forms-web-app/src/views/projects/documents.njk
This is a fix to a regression where the paging in the document library no longer works.  Select a page number in document library resulted in data unable to be fetched as the caseRef was not sent on the request to API.
> fix(documents.njk): fix for the document library paging bug

- packages/forms-web-app/src/public/javascripts/modules/sanitise-form.js
- packages/forms-web-app/src/validators/register/tell-us-about-project.js
- packages/forms-web-app/src/views/projects/documents.njk
- packages/forms-web-app/src/views/register/agent/tell-us-about-project.njk
- packages/forms-web-app/src/views/register/myself/tell-us-about-project.njk
- packages/forms-web-app/src/views/register/organisation/tell-us-about-project.njk
Fix form max character length validation 
Add maxLength attribute to html text area tag
Jira Ticket: https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-448
You can use a character count website like: https://wordcounter.net/
Local Project URL: http://localhost:9004/register/myself/check-answers
I would like to have someone pulling it and checking if it works for you as well.
Caveat: you won't see any errors if you input more than 65234 characters in the text area because its maxLength attribute is set to 65234.
To see the error and bypass it you need to inspect the element and manually increase it.
> fix(fix form max character length validation): fix form max character validation

- packages/forms-web-app/__tests__/unit/controllers/projects/examination.test.js
- packages/forms-web-app/src/controllers/projects/examination.js
- packages/forms-web-app/src/views/projects/index.njk
Fix to prevent 'Contact us for support' section rendering email paragraph when ProjectEmailAddress is returned as null.
Example of the issue can be seen at: https://applications-service-test.planninginspectorate.gov.uk/projects/EN010074
> Fix: Prevent email copy from rendering if email address is not present

- packages/applications-service-api/src/controllers/documents.js
- packages/forms-web-app/__tests__/unit/utils/replace-controller-param-type.test.js
- packages/forms-web-app/src/controllers/projects/documents.js
- packages/forms-web-app/src/utils/replace-controller-param-type.js
add Other Documents' to everything else filter
'Other Documents' to be part of 'Everything else' filter
BREAKING CHANGE: Now other documents filter is part of the everything else filter which changes how
the filters behaviour
> feat('other documents' to be part of 'everything else' filter): add Other Documents' to everything else filter

- packages/forms-web-app/src/public/stylesheets/unbranded-ie8.css
- packages/forms-web-app/src/public/stylesheets/unbranded.css
- packages/forms-web-app/src/sass/components/style/canvas-background.scss
[[A11y] SortSite - 1.3.1 Info and Relationships – Semantic Markup Not Used Appropriately](https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-347)
> ASB-347: Semantic Markup Not Used Appropriately

- packages/forms-web-app/__tests__/unit/controllers/register/agent/declaration.test.js
- packages/forms-web-app/__tests__/unit/controllers/register/myself/declaration.test.js
- packages/forms-web-app/__tests__/unit/controllers/register/organisation/declaration.test.js
- packages/forms-web-app/src/controllers/register/agent/declaration.js
- packages/forms-web-app/src/controllers/register/myself/declaration.js
- packages/forms-web-app/src/controllers/register/organisation/declaration.js
Add exception handling to relevant reps - POST to avoid uncaught exception forcing a web server re-start.
This is a generic catch all for now which will result in the same outcome on a 500 error from API - Page-not found.  The change here handles the exception which will avoid an uncaught exception and resulting web-app restart.
We may need to revisit this in future as error handling in this area requires some work.
> fix(declaration.js): ASB-620 handle internal exception when posting declaration

- .gitignore
- docker-compose.yml
- packages/applications-service-api/Dockerfile
- packages/applications-service-api/src/lib/config.js
- Moves `uploads` directory to project root
- Amend Dockerfile to ensure `node` owners owns the `uploads` directory
- Provide a volume mount between local filesystem and Docker container for when running locally via Docker Compose
> fix(docker): permissions relating to uploads directory

- packages/applications-service-api/__tests__/unit/services/timetable.service.test.js
- packages/applications-service-api/src/services/timetable.service.js
Change default sort order for `/timetables/{caseRef}` to `dateOfEvent` `ASC`
> chore(api): update fetch timetable query to order by dateOfEvent ASC

- packages/forms-web-app/src/controllers/register/start.js
Do not delete the myself session data at the start of the relevant reps submission journey.  This data will be initialised in the type-of-party.js controller.  By not deleting it we will reduce the number of null data issues.
In production we are seeing the same session Id completing multiple journeys which is causing the initial journey with deleted myself session data to throw errors.
> fix(start.js): remove code to delete myself session data

- packages/forms-web-app/__tests__/unit/controllers/examination/personal-information/controller.test.js
- packages/forms-web-app/src/controllers/examination/personal-information/controller.js
Fixes a bug when marking a file/comment as containing personal information.
> fix(personal information): clear personal information on NO selection

- packages/forms-web-app/__tests__/unit/controllers/examination/session/deadlineItems-session.test.js
- packages/forms-web-app/src/controllers/examination/session/deadlineItems-session.js
Replicate - have an empty session, go to through the emanation journey to the select a deadline item page and the page should render. 
The issues was no setting a default array if the submission items did not exists.
> fix(add another deadline item): bug with empty submission item would not be able to find

- packages/applications-service-api/__tests__/__data__/submission.js
- packages/applications-service-api/__tests__/unit/controllers/submissions.test.js
- packages/applications-service-api/__tests__/unit/middleware/parseFormDataProperties.test.js
- packages/applications-service-api/__tests__/unit/middleware/validator/openapi.test.js
- packages/applications-service-api/__tests__/unit/middleware/validator/submission.test.js
- packages/applications-service-api/__tests__/unit/routes/submissions.test.js
- packages/applications-service-api/__tests__/unit/services/submission.service.test.js
- packages/applications-service-api/api/openapi.yaml
- packages/applications-service-api/src/controllers/submissions.js
- packages/applications-service-api/src/error/apiError.js
- packages/applications-service-api/src/lib/notify.js
- packages/applications-service-api/src/middleware/parseFormDataProperties.js
- packages/applications-service-api/src/middleware/validator/openapi.js
- packages/applications-service-api/src/middleware/validator/submission.js
- packages/applications-service-api/src/routes/index.js
- packages/applications-service-api/src/routes/submissions.js
- packages/applications-service-api/src/services/submission.service.js
- packages/applications-service-api/src/utils/openapi.js
- new `/submissions/{submissionId}/complete` endpoint
- updated openapi spec
- stub implementation
- request validation
- fetching submission from DB
- does not call notify service yet, to be implemented in ASB-901
- fix incorrect path of create submission endpoint. `/submission/:caseReference` -> `/submissions/:caseReference`
> feat(applications-service-api): complete submission endpoint

- docker-compose.yml
- mock-server/init.json
- packages/applications-service-api/__tests__/unit/middleware/validator/submission.test.js
- packages/applications-service-api/src/middleware/validator/submission.js
- basic mock server with static responses for the NI API calls (fetch token & post file)
- fix bug with POST `/submissions/:caseReference` where validation occurred after request had been completed (`ERR_HTTP_HEADERS_SENT` error, introduced by refactoring in #505 )
> feat(applicatons-service-api): mock server for ni api calls

- packages/forms-web-app/__tests__/unit/controllers/examination/process-submission/controller.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/process-submission/utils/process.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/session/delete-examination-session.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/session/examination-session.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/submission-complete/controller.test.js
- packages/forms-web-app/__tests__/unit/controllers/session/app-data-session.test.js
- packages/forms-web-app/__tests__/unit/services/submission.service.test.js
- packages/forms-web-app/src/controllers/examination/process-submission/controller.js
- packages/forms-web-app/src/controllers/examination/process-submission/utils/process.js
- packages/forms-web-app/src/controllers/examination/session/delete-examination-session.js
- packages/forms-web-app/src/controllers/examination/session/examination-session.js
- packages/forms-web-app/src/controllers/examination/submission-complete/controller.js
- packages/forms-web-app/src/controllers/session/app-data-session.js
- packages/forms-web-app/src/lib/application-api-wrapper.js
- packages/forms-web-app/src/services/submission.service.js
- packages/forms-web-app/src/views/pages/examination/submission-complete.njk
Added new page for submission complete.
- The submissionId has been added to the examinationSession data
- There is an assumption that project email and submissionId will be available.  Page will still be rendered without them as we don't want to fail the process at this stage.
> feat(submission-complete): create new submission complete page

- packages/forms-web-app/__tests__/unit/services/submission.service.test.js
- packages/forms-web-app/src/lib/application-api-wrapper.js
The API handler had the content type removed as we were sending multi-part data for the new submission endpoint.
This broke the interested party endpoint as the string body was not being interpreted as JSON. 
This change defaults the content type to JSON and allows us to override with {} in the submission call in the wrapper.
> fix(application-api-wrapper.js): default the content header type 

- packages/applications-service-api/__tests__/__data__/documents.js
- packages/applications-service-api/__tests__/unit/services/document.v3.service.test.js
- packages/applications-service-api/__tests__/unit/utils/documentFilterLabelMapper.test.js
- packages/applications-service-api/api/openapi.yaml
- packages/applications-service-api/src/controllers/documents.v3.js
- packages/applications-service-api/src/services/document.v3.service.js
- packages/applications-service-api/src/utils/documentFilterLabelMapper.js
- exclude stage 0 from filters
- add label to document v3 filter response
- fix error when document filter type is empty array
- (openapi) make value and name required for /v3/documents request filter
> feat(applications-service-api): add filter label to document v3 response

- packages/applications-service-api/__tests__/unit/utils/documentFilterLabelMapper.test.js
- packages/applications-service-api/src/utils/documentFilterLabelMapper.js
the naming of "Developer's Application" in the DB is a bit inconsistent (at least on the test env DBs). This PR makes the label lookup code a bit more robust and dealing with such occurences
- looks up label name for `category` in a case insensitive way and provide a fallback value if no mapping found
> fix(applications-service-api): make category label lookup case insensitive

- packages/applications-service-api/__tests__/unit/services/document.v3.service.test.js
- packages/applications-service-api/src/services/document.v3.service.js
- adds `id` as a secondary sort column on the SELECT query which retrieves documents from the database
- this fixes an issue where results were inconsistent between queries due to documents having the same published date
> fix(applications-service-api): add secondary sort column for document v3 lookup

- packages/forms-web-app/src/views/projects/examination-timetable.njk
Remove links to overview page from exam timetable page.
Also make the closed date footer logic only appear if the exam timetable is shown.
> fix(examination-timetable.njk): remove links to project overview page

- packages/forms-web-app/src/routes/index.js
- packages/forms-web-app/src/routes/projects/index.js
Feature flag usePrivateBetaV1RoutesOnly is blocking route to having your say.
This change moves the exam timetable and having your say routes out of the scope of usePrivateBetaV1RoutesOnly.
> fix(routes): remove exam timetable from usePrivateBetaV1RoutesOnly

- docker-compose.yml
- package-lock.json
- packages/common/src/utils/redis.js
- packages/common/src/utils/redis.test.js
- packages/forms-web-app/__tests__/unit/lib/session.test.js
- packages/forms-web-app/package.json
- packages/forms-web-app/src/app.js
- packages/forms-web-app/src/config.js
- packages/forms-web-app/src/lib/session.js
changes to the web app to enable using redis as session store:
- update version of redis node library
- amend local config to use redis server with a password, as the azure redis server does
- helper function to parse the redis connection string provided by azure redis
> feat(forms-web-app): redis cache config set up

- azure-pipelines-deploy.yml
- package-lock.json
- package.json
- packages/data-service/package.json
- adds database migration NPM tasks which invoke Prisma migrate function
- exclude `data-service` from NPM test tasks for now, until DB is available in all environments
- adds "Run Database Migration" option to the "Deploy" pipeline in Azure DevOps. Unchecked by default. Runs `db:migrate:deploy` NPM task.
> feat(data-service): pipeline option to migrate db

- e2e-tests/cypress/e2e/decision-making-process-guide/decision-making-process-guide.js
- e2e-tests/cypress/e2e/get-involved-in-preliminary-meeting/get-involved-in-preliminary-meeting.js
- e2e-tests/cypress/e2e/overview-page.feature
- e2e-tests/cypress/e2e/project-application-documents.feature
- e2e-tests/cypress/e2e/project-application-documents/PageObjects/PO_ProjectAppDocs.js
- e2e-tests/cypress/e2e/register-to-say-about-national-infra-project/register-to-say-about-national-infra-project.js
- e2e-tests/cypress/e2e/registration-comments/PageObjects/PO_RegComments.js
- e2e-tests/cypress/e2e/registration-comments/registration-comments.js
- e2e-tests/cypress/support/common-methods/assertUserOnThePage.js
- e2e-tests/cypress/support/common-methods/clickLinkTonavigateToPage.js
- e2e-tests/cypress/support/common-methods/clickOnHref.js
Fix automation tests, approximately 50 failures.
Mainly due to changes in functionality/enhancements including:
- New Document library format with multiple level filters
- Paging changes for 25 documents
- Accessibility changes resulting in change of elements being returned
- Route changes for guide documents
- Other content changes.
> test: fix tests for automation

- azure-pipelines-deploy.yml
- packages/back-office-subscribers/nsip-project/__tests__/index.test.js
- packages/back-office-subscribers/nsip-project/index.js
- packages/data-service/prisma/migrations/20230405134957_init/migration.sql
- packages/data-service/prisma/migrations/20230405153152_init/migration.sql
- packages/data-service/prisma/schema.prisma
- parse incoming message, and store arrays as csv
- exclude some properties (relationships). To be added later if they are needed
- re-enable deployments for subscribers
- amend db schema to include caseId and make it the PK
> fix(back-office-subscribers): parsing project message

- packages/back-office-subscribers/host.json
- packages/back-office-subscribers/nsip-project/__tests__/index.test.js
- packages/back-office-subscribers/nsip-project/index.js
for the nsip-project subscriber function
- disable log sampling
- manually set `modifiedAt` field, is not set automatically by output binding
> fix(back-office-subscribers): set modifiedAt and disable log sampling

- packages/forms-web-app/src/pages/examination/process-submission/utils/process.js
- packages/forms-web-app/src/pages/examination/process-submission/utils/process.test.js
Fix for undefined caseRef on submission.
The caseRef has moved out of the examinationSession data and into the parent session data.
This change now uses the parent session data so that the caseRef is not undefined.
> fix(process.js): fix for caseRef issue causing horizon not to process submission

- packages/applications-service-api/__tests__/unit/middleware/validator/openapi.test.js
- packages/applications-service-api/api/openapi.yaml
- amends openapi spec (and therefore validation rules) that restrict characters that case be used in `caseReference`
- amend min/max length to reflect rules imposed by regex
- allow lowercase letters
> fix(applications-service-api): allow lowercase letters in caseref validation

- packages/forms-web-app/src/pages/projects/documents/utils/documents/search-examination-library-document.js
- packages/forms-web-app/src/pages/projects/documents/utils/documents/search-examination-library-document.test.js
documents with the name "Examination Library" may not be _the_ examination library document, so some extra filtering is required to ensure we select the right document. This PR adds an additional check that the document's `type` attribute is equal to `Examination Library`, which should ensure we get the correct document.
> fix(forms-web-app): add additional filtering for exam library doc selection

- packages/applications-service-api/__tests__/integration/subscriptions.test.js
- packages/applications-service-api/__tests__/unit/controllers/subscriptions.test.js
- packages/applications-service-api/__tests__/unit/services/backoffice.publish.service.test.js
- packages/applications-service-api/api/openapi.yaml
- packages/applications-service-api/src/controllers/subscriptions.js
- packages/applications-service-api/src/routes/subscriptions.js
- packages/applications-service-api/src/services/backoffice.publish.service.js
adds `DELETE /api/v1/subscriptions/{caseReference}` endpoint
takes encrypted email as query param and publishes message to back office 'delete nsip subscription' topic, containing email + case ref
> feat(applications-service-api): delete subscription endpoint

- packages/applications-service-api/__tests__/integration/subscriptions.test.js
- packages/applications-service-api/__tests__/unit/controllers/subscriptions.test.js
- packages/applications-service-api/src/controllers/subscriptions.js
improve validation and error handling on the `PUT /api/v1/subscriptions/{caseReference}` endpoint
- explicitly handle missing `email` / `subscriptionTypes` properties when decrypting payload
- return a nicer error message if decryption fails
> feat(applications-service-api): improve error handling for PUT /api/v1/subscriptions/{caseReference}

- packages/applications-service-api/__tests__/unit/repositories/document.backoffice.repository.test.js
- packages/applications-service-api/src/lib/config.js
- packages/applications-service-api/src/lib/prisma.js
- packages/applications-service-api/src/repositories/document.backoffice.repository.js
- packages/back-office-subscribers/nsip-documents/index.js
- packages/back-office-subscribers/nsip-project/index.js
- packages/forms-web-app/src/pages/projects/documents/utils/documents/body/mapQueryToFilterBody.js
- packages/forms-web-app/src/pages/projects/documents/utils/documents/body/mapQueryToFilterBody.test.js
fixes a couple of issues with filtering on documents page (Back Office document integration only)
- `type` property in request was ignored: Prisma query was not being constructed correctly 
- `pre-examination` stage filter ignored: Parsing of query params uses `-` as a separator so was conflicting with `-` in `pre-examination` string
also added some more verbose logging to azure functions and prisma queries (local + dev only)
> ASB-1640: fix document filtering issues

- packages/forms-web-app/src/pages/projects/documents/utils/filters/dates/fixtures/expected-from-date-is-before-to-date-dates-filter-obj.js
- packages/forms-web-app/src/pages/projects/documents/utils/filters/dates/utils/get-active-date-filters.js
- packages/forms-web-app/src/pages/projects/documents/utils/filters/dates/view-model/get-active-date-filter-view-model.js
fixes regression caused by [ASB-1202](https://github.com/Planning-Inspectorate/applications-service/pull/669/files#diff-10937d44ec7e52d5a04a6dd385cc11212ea9e7e2fe3d48d4966d0badf38f4d3aR24) where the 'remove date from/to' filter buttons on the documents page no longer had labels
> fix(forms-web-app): fix labels on document date filters

- docker-compose.yml
Windows can't map whole '/var/opt/mssql' directory as a volume and would prevent container from starting
> fix: mssql volume mapping

- packages/applications-service-api/__tests__/integration/projectUpdates.test.js
- packages/applications-service-api/__tests__/unit/controllers/project-updates.test.js
- packages/applications-service-api/src/controllers/project-updates.js
remove validation that a case exists before looking for project-updates in the db
> fix(applications-service-api): return 200 when no project updates for case

- packages/forms-web-app/src/pages/projects/_middleware/middleware.component.test.js
- packages/forms-web-app/src/pages/projects/_middleware/middleware.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-1754
Routes used to return 500 instead of 404.
> fix(project-info): routes for case-id that should be blocked return 404 correctly 

- packages/applications-service-api/__tests__/unit/middleware/parseQueryParamProperties.test.js
- packages/applications-service-api/src/middleware/parseQueryParamProperties.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-1836
normaliseArrayQueryParams was converting non array filters into array so they pass the validation check from open-api, however empty strings were being ignored. normaliseArrayQueryParams now converts empty strings to empty array which passes the open-api check as expected.
> fix: get applications empty parameters converted to array

- packages/applications-service-api/__tests__/integration/applications.test.js
- packages/applications-service-api/__tests__/unit/services/application.service.test.js
- packages/applications-service-api/api/openapi.yaml
- packages/applications-service-api/src/controllers/applications.js
- packages/applications-service-api/src/services/application.service.js
Adds `totalItemsWithoutFilters` property to the `/api/v1/applications` endpoint response. This property represents the total number of applications _without any_ filters applied. The `totalItems` property is left as-is, and continues to represent the total number of applications _with_ filters applied.
This satisfies a missed requirement (raised in ASB-1850) that the frontend needs to show the total 'unfiltered' count in the link to the CSV download, which is a list of all unfiltered applications.
Example response:
```
{
"applications": [
// 4 applications
],
"totalItems": 4,
"currentPage": 1,
"itemsPerPage": 25,
"totalPages": 1,
"totalItemsWithoutFilters": 21, // <----------------- new property
"filters": [
// some filters
]
}
```
> feat(applications-service-api): add applications totalItemsWithoutFilters property

- packages/applications-service-api/__tests__/__data__/application.js
- packages/applications-service-api/__tests__/integration/applications.test.js
- packages/applications-service-api/__tests__/integration/subscriptions.test.js
- packages/applications-service-api/__tests__/setup-jest.js
- packages/applications-service-api/__tests__/unit/controllers/applications.v2.test.js
- packages/applications-service-api/__tests__/unit/controllers/subscriptions.test.js
- packages/applications-service-api/__tests__/unit/services/application.service.test.js
- packages/applications-service-api/__tests__/unit/utils/application.mapper.test.js
- packages/applications-service-api/__tests__/unit/utils/mapLocation.test.js
- packages/applications-service-api/src/controllers/subscriptions.js
- packages/applications-service-api/src/services/application.ni.service.js
- packages/applications-service-api/src/services/application.service.js
- packages/applications-service-api/src/utils/application.mapper.js
- packages/applications-service-api/src/utils/mapLocation.js
- rework `controllers/subscriptions.js` to use new `getApplication` service function, which allows the endpoint to process `caseReference`s that are either for applications in the NI database, or from Back Office
- refactoring:
- make `getBackOfficeApplication` private as this was the only place it was in use and is now superseded by `getApplication`
- move `addMapZoomLevelAndLongLat` to `application.mapper.js` and simplify implementation
- fix incorrect default zoom level
> feat(applications-service-api): allow subscribing to project updates for ni application

- packages/applications-service-api/__tests__/integration/applications.test.js
- packages/applications-service-api/__tests__/unit/services/application.ni.service.test.js
- packages/applications-service-api/__tests__/unit/utils/application.mapper.test.js
- packages/applications-service-api/src/repositories/project.ni.repository.js
- packages/applications-service-api/src/services/application.ni.service.js
- packages/applications-service-api/src/utils/application.mapper.js
ASB-1909
Fixes bug where `Region`, `Stage` or `Proposal` in the NI database were set to an unexpected value, which was then returned in the list of `filters` from the `GET /applications`.
Updated the NI-to-API mapping object (`NI_MAPPING`) to include `Region` rather than relying on naming convention being followed, and does not return a filter value if it is not found in the mapping.
> fix(applications-service-api): validate applications filter values

- packages/forms-web-app/src/pages/register-of-applications/utils/get-register-of-applications-query-string.js
- packages/forms-web-app/src/pages/register-of-applications/utils/get-register-of-applications-query-string.unit.test.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-1897
Update to https://github.com/Planning-Inspectorate/applications-service/pull/841 changes DateOfDCOSubmission sort from ascending to descending
> fix: register of apps default sort DateOfDCOSubmission to descending

- packages/back-office-subscribers/nsip-exam-timetable/__tests__/index.test.js
- packages/back-office-subscribers/nsip-exam-timetable/index.js
Quick fix to check for `caseReference` to exist in message or we log and skip the message. Previous PR for reference: https://github.com/Planning-Inspectorate/applications-service/pull/876
> fix: validation case reference in back office examtimetable function

- packages/forms-web-app/src/pages/projects/register/index/_utils/is-registration-open.js
- packages/forms-web-app/src/pages/projects/register/index/_utils/is-registration-open.unit.test.js
Relevant reps registration is closing on the start of deadline date rather than the end of the day.
> fix(is-registration-open.js): fix issue with reps being closed on deadline date

- packages/back-office-subscribers/nsip-project-update/__tests__/index.test.js
- packages/back-office-subscribers/nsip-project-update/function.json
- packages/back-office-subscribers/nsip-project-update/index.js
- packages/back-office-subscribers/nsip-project/__tests__/index.test.js
- packages/back-office-subscribers/nsip-project/index.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-1974
This techdeb PR updates the back-office subscriber function for project-update to use Prisma. Similar to the convention we have set in exam-timetable, we use transactions and ensure we check the timestamps to only consume new data. 
2. Run azurite `npx azurite` and this function `npm run start:dev nsip-project-update`
3. Make a POST request to `http://localhost:7071/admin/functions/nsip-project-update` with this body:
```
{
"input": "{\"id\":9,\"caseReference\":\"BC0110001\",\"updateDate\":\"2023-07-28\",\"updateName\":\"July Update\",\"updateContentEnglish\":\"this is an update\",\"updateContentWelsh\":\"diweddariad yw hwn\",\"updateStatus\":\"published\""
}
```
> feat: bo project-update function update with prisma

- packages/applications-service-api/__tests__/unit/repositories/submission.ni.repository.test.js
- packages/applications-service-api/__tests__/unit/services/submission.ni.service.test.js
- packages/applications-service-api/src/repositories/submission.ni.repository.js
- packages/applications-service-api/src/services/submission.ni.service.js
ASB-xxxx
Fix regression introduced by #850 where completing a NI submission does not set the `validated` field for every row in the submissions table with the given `submissionId`, only the first one.
The change which caused the regression has been reverted - switching the function back to updating by `submissionId`, rather than `id`.
- Prior to the change introduced in https://github.com/Planning-Inspectorate/applications-service/pull/850/files#diff-e320b91b50789dde422e5a21d6b3aae480a27ead3782b5fa2ecd5b3927b39913 - the `completeSubmission` function was calling `updateSubmissionsBySubmissionId`. When that function was moved (new name `completeNISubmission`), the `updateSubmissionsBySubmissionId` was removed in favour of `updateSubmission` (which updated by `id`, not `submissionId`).
> fix(applications-service-api): ni submission complete bug

- packages/applications-service-api/__tests__/unit/services/interestedParty.ni.service.test.js
- packages/applications-service-api/src/routes/interested-party.js
- packages/applications-service-api/src/services/interestedParty.ni.service.js
Fix for bug introduced by https://github.com/Planning-Inspectorate/applications-service/pull/898 where the wrong field (should be `ID` not `id`) was being passed to the update query which sets the `emailed` field in the interested party table in the NI DB (to indicate an email confirmation has been sent to the interested party). Added a unit test which was missed from aforementioned PR that would have caught this
Also added the async route wrapper to allow exceptions to be caught and returned as a HTTP response, rather than crashing the whole node process.
> fix(applications-service-api): fix issue updating interestedParty

- packages/applications-service-api/__tests__/integration/interestedParty.test.js
- packages/applications-service-api/__tests__/unit/repositories/interestedParty.repository.test.js
- packages/applications-service-api/src/repositories/interestedParty.ni.repository.js
ASB-2080
Add some additional error handling for the scenario where inserting a row into the NI database for a table/column which does not have utf8 character encoding enabled.
Also added a unit test for the interested party repository.
Sequelize throws a specific error for this scenario (`ER_TRUNCATED_WRONG_VALUE_FOR_FIELD`)
> fix(applications-service-api): ni interested party db encoding error handling

- packages/applications-service-api/__tests__/integration/interestedParty.test.js
- packages/applications-service-api/__tests__/unit/utils/openapi.test.js
- packages/applications-service-api/api/openapi.yaml
- packages/applications-service-api/src/routes/interested-party.js
- packages/applications-service-api/src/utils/openapi.js
ASB-1468 (AC4)
Adds validation to the request body of `POST /api/v1/interested-party` endpoint, as per AC4 of ASB-1468 (missed in previous PR - #906)
Also fixes bug in the openapi validation helper where it throws an error if the request path has a trailing slash
change to `utils/openapi.js` looks larger than it is due to prettier reformatting the file to current linting standards. The change is one extra string `replace` call
>  fix(applications-service-api): add required property validation to interested-party endpoint

- packages/applications-service-api/__tests__/unit/services/advice.service.test.js
- packages/applications-service-api/src/repositories/document.ni.repository.js
- packages/applications-service-api/src/services/advice.service.js
[PR to extend advice endpoint for BO integration](https://github.com/Planning-Inspectorate/applications-service/pull/921) accidentally removed adviceID filter in query. This PR adds it back.
> fix: re-added missing adviceID in NI attachment repository

- packages/applications-service-api/src/repositories/document.backoffice.repository.js
https://pins-ds.atlassian.net/browse/ASB-2157
PR fixes S51 attachments not showing up for BO cases
Feature branch has been deployed to dev currently and the BO case shows advice attachments below:
https://applications-service-dev.planninginspectorate.gov.uk/projects/BC0110001/s51advice/60
> fix: get s51 advice attachments for bo integration cases

- packages/back-office-subscribers/nsip-advice-unpublish/__tests__/index.test.js
- packages/back-office-subscribers/nsip-advice-unpublish/function.json
- packages/back-office-subscribers/nsip-advice-unpublish/index.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-2089
This PR creates a back office subscriber function to unpublish s51 advice messages (remove from DB)
2. Run azurite `npx azurite` and this function `npm run start:dev nsip-advice-unpublish`
3. Make a POST request to `http://localhost:7071/admin/functions/nsip-advice-unpublish` with this body:
```
{
"input": "{\"adviceId\":2}"
}
```
> feat: unpublish advice bo function

- packages/back-office-subscribers/nsip-representation/__tests__/index.test.js
- packages/back-office-subscribers/nsip-representation/index.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-2178
PR adds a check to consumer function to only createOrConnect represented Or representative if the representedId and representativeId exists in the message.
> fix: representation function only create service user if id exists in message

- packages/back-office-subscribers/nsip-representation-update/__tests__/index.test.js
- packages/back-office-subscribers/nsip-representation-update/function.json
- packages/back-office-subscribers/nsip-representation-update/index.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-2173
This PR creates a back office subscriber function to consume and update the status for representations
2. Run azurite `npx azurite` and this function `npm run start:dev nsip-representation-update`
3. Make a POST request to `http://localhost:7071/admin/functions/nsip-representation-update` with this body: 
```
{
"input": "{\"representationId\":100,\"status\":\"PUBLISHED\"}"
}
```
> feat: rep update consumer function

- packages/back-office-subscribers/nsip-exam-timetable/__tests__/index.test.js
- packages/back-office-subscribers/nsip-exam-timetable/index.js
https://pins-ds.atlassian.net/browse/ASB-2214
Handle case where deadlineStartDate does not exist. This will only be set on events of type deadline, change will set based on availability.
This is causing the function to fail at the moment for any messages which include non-deadline events.
Will be tested/validated once deployed via message bus.
> fix(nsip-exam-timetable): handle missing deadline start time

- e2e-tests/cypress/e2e/examination-of-the-application.feature
- packages/back-office-subscribers/nsip-exam-timetable-unpublish/__tests__/index.test.js
- packages/back-office-subscribers/nsip-exam-timetable-unpublish/function.json
- packages/back-office-subscribers/nsip-exam-timetable-unpublish/index.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-2286
Infra PR:
2. Run azurite `npx azurite` and this function `npx func start --functions nsip-exam-timetable-unpublish`
3. Make a POST request to `http://localhost:7071/admin/functions/nsip-exam-timetable-unpublish` with this body:
```
{
"input": "{\"caseReference\":\"mock-id\"}"
}
```
to test that the error is thrown when case reference is missing:
```
{
"input": "{\"notCaseReference\":\"mock-id\"}"
}
```
> feat(back-office-subscribers): add exam timetable unpublish function

- packages/forms-web-app/src/config.js
- packages/forms-web-app/src/pages/project-search/view.njk
- packages/forms-web-app/src/pages/register-of-applications/view.njk
Ticket: https://pins-ds.atlassian.net/browse/ASB-2284
PR hides pagination and items per page controls when showing merged applications (checked via feature flag)
> feat: hide pagination controls for merged applications

- packages/e2e_tests/cypress.config.js
- packages/e2e_tests/cypress/e2e/examination-timetable-agent-submission.cy.js
- packages/e2e_tests/package-lock.json
- packages/e2e_tests/package.json
Ticket: https://pins-ds.atlassian.net/browse/ASB-2300
PR combines all the dependabot updating dependancies in `packages/e2e-tests`:
- https://github.com/Planning-Inspectorate/applications-service/pull/1012 
- https://github.com/Planning-Inspectorate/applications-service/pull/1008 
- https://github.com/Planning-Inspectorate/applications-service/pull/1007 
- https://github.com/Planning-Inspectorate/applications-service/pull/1006 
- https://github.com/Planning-Inspectorate/applications-service/pull/1005
The main change is `cypress` updating to `13.6.4` and some other indirect dependancy updates only updating on the `package-json.json`. Running e2e tests locally caused some failures due to timeouts not being long enough for submissions, so have increased that. Some of these tests do fail but …
> chore: dependabot combined packages/e2e updates 

- packages/applications-service-api/__tests__/unit/repositories/document.backoffice.repository.test.js
- packages/applications-service-api/src/repositories/document.backoffice.repository.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-2353
Previously was sorting by `createdAt` but should be using `datePublished`. This PR changes the sort filter for BO document repository.
> fix: document sorting by datePublished

- packages/forms-web-app/src/pages/projects/section-51/advice-detail/controller.js
Issue with general advice attachments not appearing on the page. Fix to fallback to the general advice case reference in the Section 51 advice detail controller when there isn't a project case reference available.
Original ticket: https://pins-ds.atlassian.net/browse/ASB-2310?atlOrigin=eyJpIjoiMTBkMjQ2Y2MzYTBlNDJmMDhmZWY0MjI2N2E0YTFlZmIiLCJwIjoiaiJ9
> fix: fallback to general advice case ref if project case ref is not available

- packages/back-office-subscribers/nsip-advice/index.js
Hotfix as BO advice function was throwing an error when attachmentIds did not exist due to missing null check.
> fix: added null check to advice function attachmentIds

- packages/back-office-subscribers/nsip-service-user/__tests__/index.test.js
- packages/back-office-subscribers/nsip-service-user/index.js
https://pins-ds.atlassian.net/browse/ASB-2388
Update function to follow existing pattern of throwing exception on missing id.
Merge query was already being used, however tests had to be re-written to follow pattern in order to pass.
The only change is the check for missing Id which throws an exception.
Unit test had to be updated.
- [n/a] I have made corresponding changes to the documentation
> fix(nsip-service-user): throw exception when no service user id present

- packages/forms-web-app/src/utils/timetables/check-timetable-state.js
- packages/forms-web-app/src/utils/timetables/check-timetable-state.unit.test.js
https://pins-ds.atlassian.net/browse/ASB-2359
Fix to the above ticket. When first introducing the `procedural deadline` event type, it was not considering the fact that BO version of the event is called `procedural deadline (pre-examination)` and only opened NI cases where the event type is just `procedural deadline`
> fix(web): correctly open timetable based on two name versions of procedural deadline event type

- packages/forms-web-app/src/app.js
[APPLICS-403](https://pins-ds.atlassian.net/browse/APPLICS-403)
* fix: move flash message middlewares to after the i18n middleware
When Welsh is selected and the user submits the form at /cookies, the
request goes through multiple redirects caused by the i18n middleware.
Since the flash message middleware came before the i18n middleware in
the chain, the success flash message was being cleared during one of the
redirects.
Tested locally.
[APPLICS-403]: https://pins-ds.atlassian.net/browse/APPLICS-403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: move flash message middlewares to after the i18n middleware

- packages/forms-web-app/src/pages/projects/_utils/get-application-data.js
- packages/forms-web-app/src/views/components/section/results.njk
[APPLICS-193](https://pins-ds.atlassian.net/browse/APPLICS-193)
Fall back to English document fields if Welsh aren't available
[APPLICS-193]: https://pins-ds.atlassian.net/browse/APPLICS-193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: fall back to English document fields if Welsh aren't available

- packages/forms-web-app/src/pages/projects/section-51/index/_utils/advice-helpers.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-444
When organisation name `from` came as ` ` (space), we wouldn't default to `firstName + lastName` or `Anonymous` and display the empty space instead. This change trims the organisation field to ensure if its empty, we default to the name or Anonymous.
> fix: advice organisation name trim whitespace

- packages/applications-service-api/__tests__/unit/controllers/representations.test.js
- packages/applications-service-api/src/models/index.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-479
PR uses a mock sequelize connection if using training environment (determined by BACK_OFFICE_INTEGRATION_GET_APPLICATIONS  feature flag being set as 'BO'), which would bypass the NI connection errors that occurred because training environment cannot access NI. This approach was chosen over a memory DB as it requires no new dependancies or more memory, whilst still ensuring everything is built correctly
> fix: bypass ni sequelize connection on training env

- packages/applications-service-api/src/repositories/document.backoffice.repository.js
https://pins-ds.atlassian.net/browse/APPLICS-667
Fix for BO cases where the documents page is not showing filters.
This is because the filters where clause has a condition of welsh filter field not being null.
This is going to be null for the non-welsh cases so the condition has been removed
This has been tested locally and will be validated in dev against projects that are affected by this issue:
BC0110003
BC0110005
- [n/a] I have made corresponding changes to the documentation
- [n/a] I have included unit tests to cover any testable code changes
> fix(document.backoffice.repository.js): fix document filters issue for BO cases

- azure-pipelines-release.yml
Fix to release pipeline due to the upgrade to node 20, this has caused release pipeline to fail.
It appears the wrapper template upgrade requires the timeoutInMinutes to be set in version refs/tags/release/3.16.1.
This is going to have to be tested by running it.
> fix(azure-pipelines-release.yml): add timeout parameter to release jobs

- packages/forms-web-app/src/pages/projects/section-51/_translations/cy.json
- packages/forms-web-app/src/pages/projects/section-51/_translations/cy.test.js
- packages/forms-web-app/src/pages/projects/section-51/_translations/en.json
- packages/forms-web-app/src/pages/projects/section-51/_translations/en.test.js
- packages/forms-web-app/src/pages/projects/section-51/_translations/translations.test.js
- packages/forms-web-app/src/pages/projects/section-51/advice-detail/_includes/page.njk
- packages/forms-web-app/src/pages/projects/section-51/advice-detail/_utils/get-attachments.js
- packages/forms-web-app/src/pages/projects/section-51/advice-detail/_utils/get-breadcrumbs-items.js
- packages/forms-web-app/src/pages/projects/section-51/advice-detail/_utils/get-breadcrumbs-items.test.js
- packages/forms-web-app/src/pages/projects/section-51/advice-detail/_utils/get-enquiry-summary-list.js
- packages/forms-web-app/src/pages/projects/section-51/advice-detail/_utils/get-page-view-model.js
- packages/forms-web-app/src/pages/projects/section-51/advice-detail/controller.test.js
- packages/forms-web-app/src/pages/projects/section-51/index/_translations/cy.json
- packages/forms-web-app/src/pages/projects/section-51/index/_translations/cy.test.js
- packages/forms-web-app/src/pages/projects/section-51/index/_translations/en.json
- packages/forms-web-app/src/pages/projects/section-51/index/_translations/en.test.js
- packages/forms-web-app/src/pages/projects/section-51/index/view.njk
- packages/forms-web-app/src/pages/projects/section-51/router.js
- packages/forms-web-app/src/pages/projects/section-51/router.test.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-686
Fixes the bugs: 
- On the main cy page the date and the results per page are shown in english
- On the cy detail page the breadcrumbs, the H2s, type description and  attachment link description are shown in english
- On the cy detail page the query field and the Advice given heading and content are missing
- On the cy detail page the date is not translated to Welsh
> fix: s51 advice welsh bugs

- docker-compose.yml
Update to docker-compose.yml to include new file reference
Prior to this change the application service solution build would fail with a "Cannot find module '@pins/common/src/utils/redis'" error when attempting to do a "npm run dev". Including a reference to the module in docker-compose corrected this error. The fix has been confirmed by myself and Ben Jacobs. There is nothing to test on the front end for this fix. There is no ticket for this issue.
> Fix/windows common package erroAdded new common volume package to docker-compose to correct build issue on Windows machinesr

- packages/applications-service-api/src/models/index.js
[APPLICS-630](https://pins-ds.atlassian.net/browse/APPLICS-630)
Explicitly define mock models for sequelize-mock.
Will need to test this in dev by setting `BACK_OFFICE_INTEGRATION_GET_APPLICATIONS` to "BO".
This might be enough to fix the error, but a follow-up PR might be needed to include mock data.
[APPLICS-630]: https://pins-ds.atlassian.net/browse/APPLICS-630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: explicitly define mock models for sequelize-mock

- packages/applications-service-api/src/models/index.js
[APPLICS-630](https://pins-ds.atlassian.net/browse/APPLICS-630)
Assign the generated Sequelize mock to the `db` object.
[APPLICS-630]: https://pins-ds.atlassian.net/browse/APPLICS-630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: assign Sequelize mocks to db object

- packages/forms-web-app/src/pages/examination/_middleware/examination.middleware.js
- packages/forms-web-app/src/pages/examination/_middleware/examination.middleware.test.js
- packages/forms-web-app/src/routes/index.js
- Middleware added to examination journey pages to redirect the user back to the examination start page if no examination session is present.
https://pins-ds.atlassian.net/browse/APPLICS-892?atlOrigin=eyJpIjoiNjM3Y2QxOWJiNWI3NDA5ZjljZWY4NjljYmQxYWIxYTkiLCJwIjoiaiJ9
> feat: APPLICS-892 - Examination journey - redirect if examination session is not found

- packages/forms-web-app/src/pages/projects/_utils/get-application-data.js
[APPLICS-912](https://pins-ds.atlassian.net.mcas.ms/browse/APPLICS-912)
Always display English name, summary and location for English cases, even when in Welsh mode.
AC:
Given the user has created an english case in BO 
And the project has been published
When the user navigates to Project page for the case
And select the welsh toggle
Then the project page is visible in welsh
And the project name, description and location appear in English (As there is no Welsh)
[APPLICS-912]: https://pins-ds.atlassian.net/browse/APPLICS-912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: always display English name, summary and location for English cases

- packages/applications-service-api/__tests__/integration/submission.test.js
- packages/applications-service-api/src/services/submission.service.js
APPLICS-909- https://pins-ds.atlassian.net/browse/APPLICS-909
- Updated naming of a written representation pdf so that the filename includes the submission type.
- Update unit tests to match above
> fix: replace hard coded name of submission comments pdf with the submission type

- packages/forms-web-app/src/pages/projects/get-updates/_middleware/get-updates-middleware.js
- packages/forms-web-app/src/pages/projects/get-updates/_middleware/get-updates-middleware.test.js
test: add unit test case for when no session found
[APPLICS-926](https://pins-ds.atlassian.net.mcas.ms/browse/APPLICS-926?McasTsid=20596&McasCtx=4)
* fix: redirect to project root from get-updates if missing session
* test: add unit test case for when no session found
Tested locally. 
[APPLICS-926]: https://pins-ds.atlassian.net/browse/APPLICS-926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: redirect to project root from get-updates if missing session

- packages/forms-web-app/src/pages/projects/_utils/format-project-update.js
- packages/forms-web-app/src/pages/projects/_utils/format-project.update.test.js
* display English project update content is language is Welsh and Welsh project update content is missing
https://pins-ds.atlassian.net.mcas.ms/jira/software/c/projects/APPLICS/boards/242?selectedIssue=APPLICS-1013
> fix: add English update data if Welsh update data missing

- packages/forms-web-app/__tests__/unit/lib/get-file-name-from-url.test.js
- packages/forms-web-app/src/lib/get-file-name-from-url.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1137
BO migrated cases have a slightly different path (published URI). This change ensures its formatted correctly on the FO FE instead of being blank. This change should not impact what currently works.
> fix: bo migrated cases document display names

- packages/forms-web-app/__tests__/unit/lib/session.test.js
- packages/forms-web-app/src/lib/session.js
https://pins-ds.atlassian.net/browse/APPLICS-1154
-set redis pingInterval to 5 mins to stop Azure Redis 10min idle timeouts
> chore(web): set redis pingInterval to stop Azure redis idle timeouts

- docker-compose.yml
- packages/applications-service-api/Dockerfile
- packages/forms-web-app/Dockerfile
https://pins-ds.atlassian.net/browse/APPLICS-1189
we don't specify an alpine version in our dockerfiles and things have broken specifically for prisma.
node alpine has been updated, and openssl path has changed, setting node alpine to node:20-alpine3.20
> chore(tooling): set node alpine to node:20-alpine3.20

- packages/applications-service-api/__tests__/unit/utils/document.mapper.test.js
- packages/applications-service-api/src/utils/document.mapper.js
CBOS / Service Bus model value for document case stage is "post_decision" with an underscore, not a hyphen (post-decision).  Amended CBOS mapper to handle this correctly.
https://pins-ds.atlassian.net/browse/APPLICS-1193
> fix: post decision doc case stage (applics-1193)

- packages/forms-web-app/src/pages/contact/view.njk
[APPLICS-1205](https://pins-ds.atlassian.net/browse/APPLICS-1205): Contact us page content update
- Added Welsh translation variable to template for link text.
[APPLICS-1205]: https://pins-ds.atlassian.net/browse/APPLICS-1205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): add welsh translation for link text on contact us page

- e2e-tests/cypress/support/common-methods/assertUserOnThePage.js
- packages/e2e_tests/cypress/e2e/cookie-settings.cy.js
- packages/e2e_tests/cypress/e2e/footer-links.cy.js
[APPLICS-1207](https://pins-ds.atlassian.net/browse/APPLICS-1207): Fix failing e2e tests to reflect content changes to Cookies page
Affected tests in E2E pipeline:
- cookie-settings.cy.js
- footer-links.cy.js
Affected tests in local test pack:
- cookies-banner.feature
- footer-links.feature
[APPLICS-1207]: https://pins-ds.atlassian.net/browse/APPLICS-1207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): update failing cookies e2e tests (applics-1207)

- packages/applications-service-api/__tests__/__data__/representation.js
- packages/applications-service-api/__tests__/unit/utils/document.mapper.test.js
- packages/applications-service-api/src/utils/document.mapper.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1137
Update to set author as personalName. Then FE will use personalName for display name if description does not exist,
> feat: use personalName for documents

- azure-pipelines-build.yml
- azure-pipelines-deploy.yml
Switch to newer versions of the Build & Deploy pipelines, to use git commit hash for docker image tags
NOTE: this does not change the release pipeline
More [docs here](https://pins-ds.atlassian.net/wiki/spaces/CS/pages/1719861253/App+Service+Deployments)
[Ticket](https://pins-ds.atlassian.net/browse/DEV-337)
> ci: use git commit hash for deployments

- packages/applications-service-api/src/repositories/project.ni.repository.js
- packages/applications-service-api/src/routes/applications.js
APPLICS-1284 
The NI `wp_ipc_projects` table uses `latin1` encoding which means queries cannot include non-latin1 characters, and when doing so the database throws an errors, which the API does not handle and crashes.
This PR updates the NI project repository to return an empty result rather than throwing an error if a query with unsupported characters is received.
The `asyncRoute` middleware has also been added to the router/controller, so in the future any uncaught errors are caught at the router level rather than crashing the whole application.
> fix(api): handle error caused by querying ni projects table with utf chars

- packages/applications-service-api/__tests__/integration/applications.test.js
- packages/applications-service-api/__tests__/unit/controllers/applications.v2.test.js
- packages/applications-service-api/__tests__/unit/services/application.merge.service.test.js
- packages/applications-service-api/__tests__/unit/utils/application.mapper.test.js
- packages/applications-service-api/src/utils/application.mapper.js
APPLICS-1259
- Updates field mapping for cases originating from CBOS, which were missing the 'Date of acceptance' field in the CSV download
- `dateOfAcceptance` is the name of the field in CBOS and the Front Office database
- `DateOfDCOAcceptance_NonAcceptance` is the name of the field in NI (the field is used for two purposes)
> fix(api): update back office field mapping for acceptance date

- packages/forms-web-app/__tests__/unit/middleware/handle-encoded-spaces.test.js
- packages/forms-web-app/src/app.js
- packages/forms-web-app/src/middleware/handle-encoded-spaces.js
https://pins-ds.atlassian.net/browse/APPLICS-1263
Users were able to continue journeys with an encoded space (%20) in the url, however it would fail the submission with an API error. 
-fixed by trimming encoded spaces in URL segments
> fix(web): trim encodede spaces in URLs

- packages/forms-web-app/src/pages/process-guide/_translations/__snapshots__/translations.test.js.snap
- packages/forms-web-app/src/pages/process-guide/_translations/cy.json
- packages/forms-web-app/src/pages/process-guide/_translations/en.json
- packages/forms-web-app/src/pages/process-guide/_utils/get-process-guide-stages.test.js
- packages/forms-web-app/src/pages/process-guide/_utils/get-process-guide-steps.test.js
- packages/forms-web-app/src/pages/projects/index/controller.test.js
[APPLICS-1398](https://pins-ds.atlassian.net/browse/APPLICS-1398): FO Process guide - minor content update
Pre-examination registration period changed from 28 to 30 days in English and Welsh and unit tests updated.
[APPLICS-1398]: https://pins-ds.atlassian.net/browse/APPLICS-1398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(web): update pre-examination registration period in process guide (applics-1398)

- packages/forms-web-app/src/pages/register-of-advice/index/view.njk
[APPLICS-1358](https://pins-ds.atlassian.net/browse/APPLICS-1358): FO Zoonou testing - 5/10 - Page Title is Not Descriptive
Added page title to register of advice page following Zoonou accessibility audit.
[APPLICS-1358]: https://pins-ds.atlassian.net/browse/APPLICS-1358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): add page title to register of advice page (applics-1358)

- packages/forms-web-app/__tests__/unit/lib/remove-unwanted-cookies.test.js
- packages/forms-web-app/src/lib/remove-unwanted-cookies.js
[APPLICS-1455](https://pins-ds.atlassian.net/browse/APPLICS-1455): Add session affinity cookie to allow list
To confirm the change is working, once deployed, the cookies values should remain static when browsing the website (check request headers and responses).
[APPLICS-1455]: https://pins-ds.atlassian.net/browse/APPLICS-1455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): add session affinity cookie to allow list (applics-1455)

- packages/forms-web-app/src/pages/examination/add-another-deadline-item/view.njk
[APPLICS-1355](https://pins-ds.atlassian.net/browse/APPLICS-1355): Related Form Elements Not Grouped Correctly
Following accessibility testing by Zoonou, it was observed that in the Have Your Say form on the "Your response to deadline" page, "the checkbox fields are grouped within a fieldset where the legend is not a direct child of the fieldset and is instead nested within a div element." 
This PR removes the additional div element, which contained hint text, and sets this text as the legend directly inside the fieldset.
On inspecting the page in the browser, the legend element should be directly nested inside the fieldset element.
[APPLICS-1355]: https://pins-ds.atlassian.net/browse/APPLICS-1355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(web): group examination deadline form elements correctly (applics-1355)

- packages/applications-service-api/__tests__/unit/repositories/document.backoffice.repository.test.js
- packages/applications-service-api/__tests__/unit/repositories/document.ni.repository.test.js
- packages/applications-service-api/src/repositories/document.backoffice.repository.js
- packages/applications-service-api/src/repositories/document.ni.repository.js
[APPLICS 1215](https://pins-ds.atlassian.net/browse/APPLICS-1215): Documents page - Search term split
NI and back-office:
- Split the search term string into an array of terms and filtered out stop words such as 'and' or 'or'.
- Updated the where clause in each database query to iterate through this array for each field to check if each term is present.
- Updated the unit tests for each repository.
Covered by the project-application-documents e2e test.
> feat(api): add search term split for documents page (applics-1215)

- packages/forms-web-app/src/pages/projects/examination-timetable/_utils/events/get-events.js
- packages/forms-web-app/src/pages/projects/examination-timetable/controller.js
- packages/forms-web-app/src/utils/date-utils.js
https://pins-ds.atlassian.net/browse/APPLICS-1508
Issue is caused by the FO not handling dates correctly. 
CBOS is saving dates in UTC. In a situation when a timetable event (eg meeting or hearing) is created without the end time, as they usually are, a default time is set eg `2025-04-24 00:00:00.000` then prisma correctly saves the date in UTC and during summer time, subtracts an hour, saving the date in the db as 
`2025-04-23 23:00:00.000`. 
Not only does FO currently not handle timezones/DST at all and simply displays given values, it also ignores the time on the deadlines/meetings, and sets the time to end of day by default on all timetable dates. Changing CBOS date into `2025-04-23 23:59:59.000`.  Which in this situation makes the event timetable items display as a day early.
This …
> fix(web): localise CBOS exam timetable dates

- packages/forms-web-app/src/pages/examination/have-your-say/view.njk
- packages/forms-web-app/src/views/macros/pagination-bar.njk
This PR removes the bold `<b>` tags in nunjucks templates and replaces them with `<strong>` tags for better use with screen readers as per accessibility testing.
https://pins-ds.atlassian.net/browse/APPLICS-1353
> fix(applics-1353): change html bold tags to use strong

- packages/forms-web-app/src/config.js
- packages/forms-web-app/src/pages/_utils/get-govuk-urls.js
- packages/forms-web-app/src/pages/_utils/get-govuk-urls.test.js
[APPLICS 1497](https://pins-ds.atlassian.net/browse/APPLICS-1497): FO Welsh Advice pages
This PR adds the URL for the Welsh advice pages to the existing config to be utilised on the Detailed Information page when the locale is equal to 'cy'. The relevant unit test has been updated.
> feat(web): add welsh advice link to detailed information page (applics-1497)

- azure-pipelines-deploy-release.yml
Variable '$(deploySlotOutputs.slotUrl)' works well for stage Web/API but fails in Deploy Api/web.
Following error is found in the failed pipeline logs:
`/agent/_work/_temp/c5a69a5d-6a09-4609-be62-04cd72ae588e.sh: line 71: deploySlotOutputs.slotUrl: command not found`
Hence I have updated the appURL to https://pins-app-applications-service-$(appName)-$(ENVIRONMENT)-$(REGION_SHORT)-001.azurewebsites.net/health
Part of ticket: https://pins-ds.atlassian.net/browse/DEV-356
> fix(tooling): updating appURL for deploy API in  deploy-release pipeline

- packages/forms-web-app/src/pages/examination/select-file/view.njk
https://pins-ds.atlassian.net/browse/APPLICS-1360
This is a workaround solution allowing Dragon Naturally Speaking users to target the upload feature using voice commands such as “click link” or saying the linked label for the input.
https://github.com/alphagov/reported-bugs/issues/35
> feat(web): additional attributes to file upload component to improve accessibility(applics-1360)

- packages/applications-service-api/prisma/schema.prisma
[APPLICS 1595](https://pins-ds.atlassian.net/browse/APPLICS-1595): Publishing to FO failing in dev and test environments
The Front Office is failing to get any service bus updates, the Invocations report this error: PrismaClientInitializationError: Prisma Client could not locate the Query Engine for runtime "debian-openssl-1.1.x". This happened because Prisma Client was generated for "debian-openssl-3.0.x", but the actual deployment required "debian-openssl-1.1.x"
This PR adds debian 1.1 to the Prisma targets as advised in the above error message.
> fix(api): add debian 1.1 to prisma targets (applics-1595)

- packages/applications-service-api/prisma/utils.js
alternative solution for db:reset in  troubleshooting
Ticket info: [applics-1556](https://pins-ds.atlassian.net/jira/software/c/projects/APPLICS/boards/269?assignee=712020%3Aba8d1ca6-3808-4688-95c8-74fe19f585b1&selectedIssue=APPLICS-1556) : FO Service user avoid conflicts in seed script Prisma/seed.js
If the user reruns the database seed will be no issue that stops the migration.
Tested and is fully compatible with the current seed.js file.
Tested in Windows internally with MSSQL and as public user with temp MySQL DB in macOS.
I run the database migration as internal and as public user in both Windows and macOS.
> fix(api): update utils.js in prisma folder (applics-1556)
