Planning-Inspectorate/applications-service

- e2e-tests/cypress/integration/full-name.feature
- e2e-tests/cypress/integration/full-name/PageObjects/PO_FullName.js
- e2e-tests/cypress/integration/full-name/full-name.js
- e2e-tests/cypress/integration/overview-page.feature
- e2e-tests/cypress/integration/overview-page/PageObjects/PO_OverviewPage.js
- e2e-tests/cypress/integration/overview-page/overview-page.js
- e2e-tests/cypress/integration/register-type-of-party.feature
- e2e-tests/cypress/integration/register-type-of-party/PageObjects/PO_TypeOfParty.js
- e2e-tests/cypress/integration/register-type-of-party/register-type-of-party.js
- e2e-tests/cypress/integration/start-page.feature
- e2e-tests/cypress/integration/start-page/PageObjects/PO_StartPage.js
- e2e-tests/cypress/integration/start-page/start-page.js
- e2e-tests/cypress/support/commands/navigation-commands.js
- e2e-tests/cypress/support/common-methods/clickOnBackLink.js
- e2e-tests/cypress/support/common-methods/clickOnHref.js
- overview page acceptance tests
- start page acceptance tests
> overview page and start page acceptance tests

- docker-compose.yml
- packages/applications-service-api/__tests__/unit/lib/crypto.test.js
- packages/applications-service-api/__tests__/unit/lib/notify.test.js
- packages/applications-service-api/api/openapi.yaml
- packages/applications-service-api/src/controllers/interested-party.js
- packages/applications-service-api/src/lib/config.js
- packages/applications-service-api/src/lib/crypto.js
- packages/applications-service-api/src/lib/notify.js
- packages/applications-service-api/src/services/interested-party.service.js
* APS-494 Amend API endpoint to support "Draft" comments
* APS-495 Implement Magic Link Generation
* APS-513 Provide notification email template
> This commit covers

- packages/forms-web-app/src/validators/register/confirm-email.js
- packages/forms-web-app/src/views/register/confirm-email.njk
Omitted URL change since it would cause significant upheaval around magic link interaction which is risky and unnecessary when the real goal for now is improve the on-screen content.
> feat(ASB-146): Revised content on confirm-email view

- docker-compose.yml
- packages/forms-web-app/src/views/includes/head.njk
Constrained use of Google Tag Manager to cookie consent and set Google Analytics ID in docker-compose
> ASB-141: Google Analytics tracking setup

- pipelines/common/common-ci.yml
- pipelines/forms-web-app/forms-web-app-ci.yml
- Remove an unused parameter in the CI pipeline
- Add new required parameters since templates changed
> Fix: CI Pipeline - Remove unused param

- packages/forms-web-app/__tests__/unit/lib/get-previous-page-path.test.js
- packages/forms-web-app/__tests__/unit/middleware/flash-message-cleanup.test.js
- packages/forms-web-app/__tests__/unit/middleware/flash-message-to-nunjucks.test.js
- packages/forms-web-app/src/lib/get-previous-page-path.js
- packages/forms-web-app/src/views/cookies.njk
ASB-154: Fixed issue with calculating previous page link on cookies info page which was not suitable for app deployed behind a proxy, i.e. in azure
> ASB-154: Fixed issue with calculating previous page link on cookies info page

- pipelines/applications-service-api/Dockerfile
- pipelines/applications-service-api/applications-service-api-cd.yml
- pipelines/applications-service-api/applications-service-api-ci.yml
- pipelines/applications-service-api/variables.yml
- Add CI and CD pipeline for the API
- Duplicated the Dockerfile again in the pipelines folder
> Add pipeline for applications service api

- pipelines/applications-service-api/applications-service-api-cd.yml
- pipelines/applications-service-api/applications-service-api-ci.yml
- pipelines/common/common-ci.yml
- pipelines/forms-web-app/forms-web-app-cd.yml
- pipelines/forms-web-app/forms-web-app-ci.yml
- Removes agent pool from pipeline as it has been added to wrapper template for stages - see https://github.com/Planning-Inspectorate/common-pipeline-templates/pull/18
> Agent pool change

- packages/forms-web-app/src/validators/register/myself/telephone.js
- packages/forms-web-app/src/validators/register/organisation/address.js
- packages/forms-web-app/src/validators/register/organisation/email.js
- packages/forms-web-app/src/validators/register/organisation/full-name.js
- packages/forms-web-app/src/validators/register/organisation/organisation-name.js
- packages/forms-web-app/src/validators/register/organisation/role.js
- packages/forms-web-app/src/validators/register/organisation/telephone.js
- packages/forms-web-app/src/validators/register/organisation/tell-us-about-project.js
* Added validation rules and error messages as per story spec. 
* Also made improvement to sanitise telephone number input to remove spaces.
> ASB-172: Added validation rules and error messages as per story spec

- packages/forms-web-app/__tests__/unit/lib/nsip-project-link.test.js
- packages/forms-web-app/package-lock.json
- packages/forms-web-app/package.json
- packages/forms-web-app/src/config.js
- packages/forms-web-app/src/controllers/register/agent/registration-complete.js
- packages/forms-web-app/src/controllers/register/myself/registration-complete.js
- packages/forms-web-app/src/controllers/register/organisation/confirmation.js
- packages/forms-web-app/src/lib/nsip-project-link.js
- packages/forms-web-app/src/views/register/agent/registration-complete.njk
- packages/forms-web-app/src/views/register/myself/registration-complete.njk
- packages/forms-web-app/src/views/register/organisation/confirmation.njk
Added NSIP project link generation function and made use of it on registration completion views
> ASB-160: Go back to project page links

- packages/forms-web-app/src/controllers/having-your-say-guide.js
- packages/forms-web-app/src/views/having-your-say-guide/registering-have-your-say.njk
Also made link conditional based on whether user has viewed a specific project prior to viewing the have your say guide.
> ASB-171: Link to Project page on NSIP site from Have Your Say Guide

- pipelines/applications-service-api/applications-service-api-cd.yml
- pipelines/forms-web-app/forms-web-app-cd.yml
- Updates the CD pipelines to use the new naming convention for the applications service Azure App Services.
> Fix App Service names for CD pipelines

- packages/forms-web-app/src/views/register/agent/registration-complete.njk
- packages/forms-web-app/src/views/register/myself/registration-complete.njk
- packages/forms-web-app/src/views/register/organisation/confirmation.njk
Revised guide links on registration confirmation pages to deep link into most relevant page of have your say guide
> ASB-148 Revised guide links on registration confirmation pages

- packages/forms-web-app/src/views/having-your-say-guide/interested-party.njk
Removed link to decision making process from having your say guide since it will not be launched as part of Private Beta v1
> ASB-200 Removed link to decision making process from having your say guide

- packages/forms-web-app/src/views/layouts/main.njk
Fixed issue introduced as part of ASB-162 where cookie banner was missed out.
> Re-instated cookie banner

- pipelines/applications-service-api/applications-service-api-cd.yml
- pipelines/forms-web-app/forms-web-app-cd.yml
- Adds a parameter to choose region when deploying
> Add region parameter to pipelines

- packages/forms-web-app/src/views/footer-pages/accessibility-statement.njk
Made URL for accessibility statement dynamic - based on configured host
> ASB-138: Make URL for accessibility statement dynamic

- packages/forms-web-app/src/views/examination/all-examination-documents.njk
- packages/forms-web-app/src/views/examination/examination.njk
- packages/forms-web-app/src/views/examination/project-timeline.njk
- packages/forms-web-app/src/views/examination/recommendations.njk
- packages/forms-web-app/src/views/examination/representations.njk
- packages/forms-web-app/src/views/examination/timetable.njk
- packages/forms-web-app/src/views/layouts/layout.njk
- packages/forms-web-app/src/views/layouts/main.njk
- packages/forms-web-app/src/views/layouts/register-main.njk
- packages/forms-web-app/src/views/project-search.njk
Fixed issue with cookies banner HTML markup being inserted into the html.head rather than html.body
> ASB-257: Fix for cookies banner markup not within body of HTML document

- pipelines/applications-service-api/applications-service-api-ci.yml
- pipelines/forms-web-app/forms-web-app-ci.yml
Attempting fix so that both CI builds (for each respective app) are triggered for PRs in order to have GitHub merge checks satisfied
> Attempting fix for triggering both CI builds on PRs

- packages/forms-web-app/src/views/projects/documents.njk
Fixed issue where only first word of search text was being retained which was due to missing double-quotes around the value attribute
> ASB-184: Fix for search box to retail complete value

- packages/forms-web-app/__tests__/unit/lib/pagination.test.js
- packages/forms-web-app/src/controllers/projects/documents.js
- packages/forms-web-app/src/lib/pagination.js
- packages/forms-web-app/src/views/macros/pagination-bar.njk
- packages/forms-web-app/src/views/projects/documents.njk
Created paginationBar macro so that pagination template code from documents can be re-used for registration comments.  Also extracted out function from controller used to derive pagination data from paginated results.
> ASB-312 Frontend: Make re-usable pagination component based on documents pagination

- packages/applications-service-api/pipelines/azure-pipelines-build.yml
- packages/applications-service-api/pipelines/azure-pipelines-release.yml
- packages/applications-service-api/pipelines/azure-pipelines-variables.yml
- packages/common/pipelines/azure-pipelines-build.yml
- packages/forms-web-app/pipelines/azure-pipelines-build.yml
- packages/forms-web-app/pipelines/azure-pipelines-release.yml
- packages/forms-web-app/pipelines/azure-pipelines-variables.yml
Pin pipeline templates to a specific version and update to use the new templates
> Pin version of pipeline templates

- packages/applications-service-api/pipelines/azure-pipelines-variables.yml
- packages/applications-service-api/src/services/interested-party.service.js
- packages/common/pipelines/azure-pipelines-variables.yml
- packages/forms-web-app/pipelines/azure-pipelines-variables.yml
Remove unnecessary call to JSON.stringify which adds unwanted escaping of new line and return characters to comments persisted in database
> Fix for ASB-357 on mainline: Additional characters included in comments text box

- packages/forms-web-app/pipelines/azure-pipelines-release.yml
Remove slots from pipeline as this is blocking deployment.
Attempt to fix the deployment issue:
`
ERROR: Cannot swap site slots for site 'pins-app-applications-service-applications-wfe-dev-ukw-001' because the 'staging' slot did not respond to http ping.`
By removing the deployment slots swap stage.
> build(azure-pipelines-release.yml): remove slots for Stage in pipeline

- packages/forms-web-app/src/views/projects/documents.njk
- packages/forms-web-app/src/views/projects/examination.njk
https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-331
> ASB-331 About the Project

- packages/forms-web-app/src/views/projects/index.njk
https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-450
> Restore contact us section on to project page

- packages/forms-web-app/src/public/javascripts/modules/sanitise-form.js
- packages/forms-web-app/src/validators/register/tell-us-about-project.js
revert sanitise form changes to prevent WAF being triggered
PR that is reverting the changes: https://github.com/Planning-Inspectorate/applications-service/pull/340
> fix(revert sanitise form changes): revert sanitise form changes

- packages/forms-web-app/src/views/register/agent/address.njk
- packages/forms-web-app/src/views/register/agent/their-postal-address.njk
- packages/forms-web-app/src/views/register/myself/address.njk
- packages/forms-web-app/src/views/register/organisation/address.njk
replace postcode autocomplete attr to postal-code
https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-341
> fix(replace postcode autocomplete attr to postal-code): replace postcode

- e2e-tests/cypress/integration/project-application-documents.feature
- packages/forms-web-app/__tests__/unit/controllers/projects/documents.test.js
- packages/forms-web-app/__tests__/unit/controllers/projects/examination.test.js
- packages/forms-web-app/__tests__/unit/controllers/register/start.test.js
- packages/forms-web-app/__tests__/unit/utils/date-utils.test.js
- packages/forms-web-app/__tests__/unit/utils/format-day-date-without-prefix-zero.test.js
- packages/forms-web-app/src/controllers/projects/documents.js
- packages/forms-web-app/src/utils/date-utils.js
> feat(add new date format): add new date format

- docker-compose.yml
- package.json
- packages/applications-service-api/Dockerfile
- packages/applications-service-api/package.json
- revert back to mounting local directories inside docker container
- switch to docker compose v2
- remove `common` from api docker container (not currently used)
- author change in package.json
> fix: amend docker-compose.yml to run code from mounted volume

- e2e-tests/cypress/integration/registration-comments.feature
- packages/forms-web-app/__tests__/unit/controllers/projects/representations.test.js
- packages/forms-web-app/src/controllers/projects/representations.js
- packages/forms-web-app/src/views/projects/representations.njk
Date format change to be GDS compliant
JIRA Ticket: https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-467
> feat(date format change to be gds compliant): date format representations

- packages/forms-web-app/src/views/layouts/vertical-tabs.njk
hide all examination docs link
> feat(hide all examination docs link): hide all examination docs link

- packages/forms-web-app/src/views/layouts/vertical-tabs.njk
Hide Recommendation and Decision Link
> feat(hide recommendation and decision link): hide Recommendation and Decision Link

- packages/forms-web-app/src/views/layouts/vertical-tabs.njk
Hide Examination Timetable Link
> feat(hide examination timetable link): hide Examination Timetable Link

- e2e-tests/cypress/integration/project-application-documents.feature
- packages/forms-web-app/src/utils/status.js
Stage name update for Acceptance (Review of the application)
> feat(stage name update for acceptance (review of the application)): Stage name update for Acceptance

- packages/forms-web-app/src/views/components/text/link.njk
- packages/forms-web-app/src/views/projects/index.njk
- packages/forms-web-app/src/views/projects/timetable.njk
https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-335
> Feat: Updated HTML Copy and Links

- e2e-tests/cypress/integration/project-application-documents.feature
- packages/applications-service-api/__tests__/unit/utils/map-filters.test.js
- packages/applications-service-api/src/controllers/documents.js
- packages/applications-service-api/src/utils/map-filters.js
- packages/forms-web-app/__tests__/unit/mocks.js
- packages/forms-web-app/__tests__/unit/utils/remove-filter-types.test.js
- packages/forms-web-app/__tests__/unit/utils/replace-controller-param-type.test.js
- packages/forms-web-app/src/controllers/projects/documents.js
- packages/forms-web-app/src/utils/remove-filter-types.js
- packages/forms-web-app/src/utils/replace-controller-param-type.js
'Other Documents' to be part of 'Everything else' filter
JIRA TICKET: https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-495
> feat('other documents' to be part of 'everything else' filter): Other Docs to be Everything Else

- e2e-tests/cypress/integration/project-application-documents.feature
- packages/forms-web-app/__tests__/unit/controllers/projects/documents.test.js
- packages/forms-web-app/src/controllers/projects/documents.js
- packages/forms-web-app/src/utils/project-stages.js
[Filter by all project stages](https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-491)
> Feature: ASB-491 filter by all project stages

- package-lock.json
- packages/forms-web-app/__tests__/unit/controllers/projects/representations.test.js
- packages/forms-web-app/__tests__/unit/utils/string-case.test.js
- packages/forms-web-app/src/controllers/projects/representations.js
- packages/forms-web-app/src/utils/string-case.js
[Filter Box - Relevant Representations Page requires correct case lettering](https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-507)
> Filter Box - Relevant Representations Page requires correct case lettering

- packages/forms-web-app/src/controllers/projects/documents.js
[ASB-485 Pin Examination library document](https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-485)
> Fix: ASB-485 Pin Examination library document

- packages/forms-web-app/src/views/cookies.njk
Remove legend tag used inappropriately
https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-349
> fix(remove legend tag used inappropriately): remove legend tag used inappropriately

- packages/forms-web-app/__tests__/unit/controllers/projects/documents.test.js
- packages/forms-web-app/src/controllers/projects/documents.js
- packages/forms-web-app/src/utils/project-stages.js
https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-491
> ASB-491: Filter by all project stages

- packages/forms-web-app/__tests__/unit/utils/query-string-builder.test.js
- packages/forms-web-app/src/lib/application-api-wrapper.js
- packages/forms-web-app/src/utils/query-string-builder.js
- packages/forms-web-app/src/utils/replace-controller-param-type.js
[Project documents filter by project stage](https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-631)
> ASB-631: Project documents filter

- packages/forms-web-app/__tests__/unit/controllers/projects/documents.test.js
- packages/forms-web-app/__tests__/unit/utils/query-string-builder.test.js
- packages/forms-web-app/src/controllers/projects/documents.js
- packages/forms-web-app/src/utils/query-string-builder.js
- packages/forms-web-app/src/views/projects/documents.njk
https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166/backlog?view=detail&selectedIssue=ASB-636&issueLimit=100
> Fix: ASB-636 - Pagination filtering issue

- e2e-tests/cypress/integration/project-application-documents.feature
- e2e-tests/cypress/integration/project-application-documents/PageObjects/PO_ProjectAppDocs.js
- e2e-tests/cypress/integration/project-application-documents/project-application-documents.js
- packages/applications-service-api/__tests__/unit/controllers/document-filter.test.js
- packages/applications-service-api/__tests__/unit/controllers/documents.test.js
- packages/applications-service-api/__tests__/unit/mocks.js
- packages/applications-service-api/__tests__/unit/utils/get-category-filter-type.test.js
- packages/applications-service-api/__tests__/unit/utils/map-filters.test.js
- packages/applications-service-api/__tests__/unit/utils/validate-parameters.test.js
- packages/applications-service-api/__tests__/unit/utils/validate-types.test.js
- packages/applications-service-api/src/controllers/documents.js
- packages/applications-service-api/src/services/document.service.js
- packages/applications-service-api/src/utils/get-category-filter-type.js
- packages/applications-service-api/src/utils/map-filters.js
- packages/applications-service-api/src/utils/validate-parameters.js
- packages/forms-web-app/__tests__/unit/controllers/projects/documents.test.js
- packages/forms-web-app/__tests__/unit/mocks.js
- packages/forms-web-app/__tests__/unit/utils/build-query-params.test.js
- packages/forms-web-app/__tests__/unit/utils/remove-filter-types.test.js
- packages/forms-web-app/__tests__/unit/utils/replace-controller-param-type.test.js
- packages/forms-web-app/src/controllers/projects/documents.js
- packages/forms-web-app/src/lib/application-api-wrapper.js
- packages/forms-web-app/src/utils/build-query-params.js
- packages/forms-web-app/src/utils/remove-filter-types.js
- packages/forms-web-app/src/utils/replace-controller-param-type.js
- packages/forms-web-app/src/views/projects/documents.njk
add application documents filter
> feat(add application documents filter): add application documents filter

- packages/forms-web-app/src/controllers/projects/documents.js
Add category to queryStringBuilder
> fix(add category to querystringbuilder): Add category to queryStringBuilder

- packages/forms-web-app/src/controllers/projects/documents.js
Fix category list - Application Document Checkbox
> feat(fix category list): fix category list - Application Document Checkbox

- packages/forms-web-app/src/app.js
- packages/forms-web-app/src/config.js
- packages/forms-web-app/src/views/layouts/vertical-tabs.njk
Add hideDecisionMakingProcessGuideLink
> feat(add hidedecisionmakingprocessguidelink): Add hideDecisionMakingProcessGuideLink

- packages/forms-web-app/__tests__/unit/controllers/examination/have-your-say.test.js
- packages/forms-web-app/__tests__/unit/controllers/projects/examination-timetable.test.js
- packages/forms-web-app/__tests__/unit/lib/views.test.js
- packages/forms-web-app/src/config.js
- packages/forms-web-app/src/controllers/examination/have-an-interested-party-number.js
- packages/forms-web-app/src/controllers/examination/have-your-say.js
- packages/forms-web-app/src/controllers/projects/examination-timetable.js
- packages/forms-web-app/src/lib/views.js
- packages/forms-web-app/src/routes/config.js
- packages/forms-web-app/src/routes/examination/index.js
- packages/forms-web-app/src/views/pages/examination/have-an-interested-party-number.njk
- packages/forms-web-app/src/views/pages/examination/have-your-say.njk
add have your say njk file, tests and controller
> feat(add have your say): add have your say njk file, tests and controller

- packages/forms-web-app/src/config.js
set hideallexaminationdocumentslink and hideprojectinformationlink to false
> fix(set hideallexaminationdocumentslink and hideprojectinformationlink to false):

- packages/forms-web-app/__tests__/unit/routes/projects/index.test.js
- packages/forms-web-app/src/routes/projects/index.js
move /:case_ref into !useprivatebetav1routesonly if
> fix(move /:case_ref into !useprivatebetav1routesonly if): move /:case_ref into !useprivatebetav1routesonly if

- packages/forms-web-app/src/config.js
hide examamination documents, project info, recommendation and decision
> fix(hide exam documents, proj info, recom and decision): hide examamination documents, project info, recommendation and decision

- packages/forms-web-app/src/views/layouts/vertical-tabs.njk
add ../../having-your-say-guide/ to href
> fix(add ../../having-your-say-guide/ to href): add ../../having-your-say-guide/ to href

- packages/forms-web-app/src/config.js
set hideExaminationTimetableLink to true (hiding it)
> fix(set hideexaminationtimetablelink to true): set hideExaminationTimetableLink to true (hiding it)

- packages/forms-web-app/__tests__/unit/controllers/examination/submitting-for.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/your-name.test.js
- packages/forms-web-app/__tests__/unit/lib/views.test.js
- packages/forms-web-app/src/config.js
- packages/forms-web-app/src/controllers/examination/applicant.js
- packages/forms-web-app/src/controllers/examination/check-your-answers.js
- packages/forms-web-app/src/controllers/examination/name.js
- packages/forms-web-app/src/controllers/examination/submitting-for.js
- packages/forms-web-app/src/lib/views.js
- packages/forms-web-app/src/routes/config.js
- packages/forms-web-app/src/routes/examination/index.js
- packages/forms-web-app/src/validators/shared/not-empty.js
- packages/forms-web-app/src/views/pages/examination/applicant.njk
- packages/forms-web-app/src/views/pages/examination/check-your-answers.njk
- packages/forms-web-app/src/views/pages/examination/name.njk
- packages/forms-web-app/src/views/pages/examination/submitting-for.njk
https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-576
> ASB-576: Who are you making the submission for?

- packages/forms-web-app/__tests__/unit/controllers/examination/has-interested-party-number.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/submitting-for.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/your-interested-party-number.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/your-name.test.js
- packages/forms-web-app/src/config.js
- packages/forms-web-app/src/controllers/examination/email.js
- packages/forms-web-app/src/controllers/examination/has-interested-party-number.js
- packages/forms-web-app/src/controllers/examination/have-your-say.js
- packages/forms-web-app/src/controllers/examination/name.js
- packages/forms-web-app/src/controllers/examination/submitting-for.js
- packages/forms-web-app/src/controllers/examination/your-interested-party-number.js
- packages/forms-web-app/src/routes/config.js
- packages/forms-web-app/src/routes/examination/index.js
- packages/forms-web-app/src/validators/shared/not-empty-and-length.js
- packages/forms-web-app/src/validators/shared/not-empty.js
- packages/forms-web-app/src/views/pages/examination/email.njk
- packages/forms-web-app/src/views/pages/examination/has-interested-party-number.njk
- packages/forms-web-app/src/views/pages/examination/have-your-say.njk
- packages/forms-web-app/src/views/pages/examination/submitting-for.njk
- packages/forms-web-app/src/views/pages/examination/your-interested-party-number.njk
https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-573
> ASB-573: Do you have an interested party number?

- packages/forms-web-app/__tests__/unit/controllers/projects/examination-timetable.test.js
- packages/forms-web-app/src/controllers/projects/examination-timetable.js
fix examination timetable query params
> fix(fix examination timetable query params): fix examination timetable query params

- packages/forms-web-app/__tests__/unit/controllers/examination/your-name.test.js
- packages/forms-web-app/__tests__/unit/controllers/projects/examination-timetable.test.js
- packages/forms-web-app/__tests__/unit/mocks.js
- packages/forms-web-app/src/controllers/examination/name.js
- packages/forms-web-app/src/middleware/forward-view.js
- packages/forms-web-app/src/routes/config.js
- packages/forms-web-app/src/routes/examination/index.js
Add nameAgent, organizationName controller, tests, refactor config
> Feature/ASB-578-579 - Add nameAgent, organizationName controller, tests, refactor config

- packages/forms-web-app/__tests__/unit/controllers/examination/has-interested-party-number.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/submitting-for.test.js
- packages/forms-web-app/src/controllers/examination/applicant.js
- packages/forms-web-app/src/controllers/examination/has-interested-party-number.js
- packages/forms-web-app/src/routes/config.js
send user to right url when selecting NO
> fix(send user to right url when selecting no): send user to right url when selecting NO

- packages/forms-web-app/__tests__/unit/controllers/examination/has-interested-party-number.test.js
- packages/forms-web-app/src/routes/config.js
- packages/forms-web-app/src/routes/examination/index.js
Add missing middleware to forward the view into the post controller
> fix(Add missing middleware): to forward the view into the post controller

- packages/forms-web-app/src/routes/config.js
Add What’s your organisations name? to title and pageTitle
> fix(add what’s your organisations name? to title): Add What’s your organisations name? to title and pageTitle

- packages/applications-service-api/__tests__/unit/services/timetable.service.test.js
- packages/applications-service-api/src/services/timetable.service.js
- update the select timetables query to order by date_of_event (descending order / newest first)
> chore: update fetch timetable query to order by dateOfEvent

- packages/forms-web-app/__tests__/unit/controllers/examination/applicant.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/has-interested-party-number.test.js
- packages/forms-web-app/src/config.js
- packages/forms-web-app/src/controllers/examination/applicant.js
- packages/forms-web-app/src/controllers/examination/has-interested-party-number.js
- packages/forms-web-app/src/routes/config.js
- packages/forms-web-app/src/routes/examination/index.js
- packages/forms-web-app/src/views/pages/examination/applicant.njk
https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-575
> ASB-575: Are you the applicant?

- packages/forms-web-app/__tests__/unit/utils/is-before-or-after-date.test.js
- packages/forms-web-app/src/utils/is-before-or-after-date.js
> fix(fix formatted date): fix formatted date

- package-lock.json
- packages/forms-web-app/__tests__/unit/controllers/projects/examination-timetable.test.js
- packages/forms-web-app/package.json
- packages/forms-web-app/src/controllers/projects/examination-timetable.js
- packages/forms-web-app/src/lib/application-api-wrapper.js
- packages/forms-web-app/src/routes/projects/index.js
Add dynamic timetable data using getTimetables function
> feat(add dynamic timetable data): add dynamic timetable data

- packages/applications-service-api/api/openapi.yaml
- Document new POST submissions API endpoint in the OpenAPI spec
> ASB-689: Update OpenAPI spec with Submissions API

- e2e-tests/cypress/integration/registration/agent/what-do-you-want-to-tell-about-project/PageObjects/PO_TellAboutProject.js
- e2e-tests/cypress/integration/registration/myself/what-do-you-want-to-tell-about-project/PageObjects/PO_TellAboutProject.js
- e2e-tests/cypress/integration/registration/organisation/what-do-you-want-to-tell-about-project/PageObjects/PO_TellAboutProject.js
- packages/forms-web-app/src/views/register/agent/tell-us-about-project.njk
- packages/forms-web-app/src/views/register/myself/tell-us-about-project.njk
- packages/forms-web-app/src/views/register/organisation/tell-us-about-project.njk
Content changes to the having your say page.
> feat(tell-us-about-project.njk): ASB-745 - changes to text around having your say

- packages/forms-web-app/__tests__/unit/controllers/examination/select-deadline.test.js
- packages/forms-web-app/__tests__/unit/controllers/projects/examination-timetable.test.js
- packages/forms-web-app/src/config.js
- packages/forms-web-app/src/controllers/examination/applicant.js
- packages/forms-web-app/src/controllers/examination/evidence-or-comment.js
- packages/forms-web-app/src/controllers/examination/select-deadline.js
- packages/forms-web-app/src/controllers/examination/submitting-for.js
- packages/forms-web-app/src/controllers/projects/examination-timetable.js
- packages/forms-web-app/src/routes/config.js
- packages/forms-web-app/src/routes/examination/index.js
- packages/forms-web-app/src/views/pages/examination/default.njk
- packages/forms-web-app/src/views/pages/examination/evidence-or-comment.njk
- packages/forms-web-app/src/views/pages/examination/select-deadline.njk
https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-581
> ASB-581: Submit Against Deadline Items

- e2e-tests/cypress/integration/registration/agent/uk-address-details.feature
- e2e-tests/cypress/integration/registration/agent/what-is-their-address.feature
- e2e-tests/cypress/integration/registration/myself/uk-address-details.feature
- e2e-tests/cypress/integration/registration/organisation/uk-address-details.feature
- e2e-tests/cypress/support/common-methods/clickProjectLink.js
- packages/forms-web-app/src/validators/register/agent/address.js
- packages/forms-web-app/src/validators/register/agent/their-postal-address.js
- packages/forms-web-app/src/validators/register/myself/address.js
- packages/forms-web-app/src/validators/register/organisation/address.js
- packages/forms-web-app/src/views/register/agent/address.njk
- packages/forms-web-app/src/views/register/agent/their-postal-address.njk
- packages/forms-web-app/src/views/register/myself/address.njk
- packages/forms-web-app/src/views/register/organisation/address.njk
Address Line 3 label becomes Town or county in the address entry.  
This commit also fixes a large number of tests due to the click location problem for over 100 tests.
> Task/ASB-747 Address line 3 becomes Town or county

- packages/forms-web-app/src/views/register/agent/tell-us-about-project.njk
- packages/forms-web-app/src/views/register/myself/tell-us-about-project.njk
- packages/forms-web-app/src/views/register/organisation/tell-us-about-project.njk
Add paragraph of text which was incorrectly removed.
> fix(tell-us-about-project.njk): add previously removed line

- packages/forms-web-app/src/views/pages/examination/select-deadline.njk
https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-783
> Fix: ASB-783 - Which items would you like to submit against for this deadline?

- packages/forms-web-app/__tests__/unit/controllers/projects/examination-timetable.test.js
- packages/forms-web-app/__tests__/unit/utils/date-utils.test.js
- packages/forms-web-app/src/controllers/projects/examination-timetable.js
- packages/forms-web-app/src/utils/date-utils.js
- packages/forms-web-app/src/views/components/section/events.njk
Implement 'make a submission' button being visible based on spec logic:
if timetable_type == 'deadline' AND
date (+ 1 day) < dateOfEvent AND 
(date > dateTimeDeadlineStart OR '0000-00-00')
show make a submission CTA 
else 
don't show  
Added test to validate event data which includes the submission button.
> Feature/ASB-649 - Make a submission button logic

- package-lock.json
- packages/forms-web-app/__tests__/unit/controllers/examination/check-your-answers.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/enter-comment.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/evidence-or-comment.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/select-deadline.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/select-file.test.js
- packages/forms-web-app/src/controllers/examination/check-your-answers.js
- packages/forms-web-app/src/controllers/examination/enter-comment.js
- packages/forms-web-app/src/controllers/examination/evidence-or-comment.js
- packages/forms-web-app/src/controllers/examination/select-deadline.js
- packages/forms-web-app/src/controllers/examination/select-file.js
- packages/forms-web-app/src/controllers/examination/submitting-for.js
- packages/forms-web-app/src/routes/config.js
- packages/forms-web-app/src/routes/examination/index.js
- packages/forms-web-app/src/views/pages/examination/enter-comment.njk
- packages/forms-web-app/src/views/pages/examination/evidence-or-comment.njk
- packages/forms-web-app/src/views/pages/examination/select-file.njk
https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-582
> ASB-582: How would you like to submit comments (written representation)?

- packages/forms-web-app/src/app.js
increase express.json payload limit
> fix(increase express.json payload limit): increase express.json payload limit

- packages/forms-web-app/__tests__/unit/controllers/examination/enter-comment.test.js
- packages/forms-web-app/src/app.js
- packages/forms-web-app/src/routes/config.js
increase express json payload limit
> fix(increase express json payload limit): increase express json payload limit

- packages/forms-web-app/__tests__/unit/controllers/examination/personal-information.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/select-file.test.js
- packages/forms-web-app/src/controllers/examination/check-deadline-item.js
- packages/forms-web-app/src/controllers/examination/enter-comment.js
- packages/forms-web-app/src/controllers/examination/personal-information-which.js
- packages/forms-web-app/src/controllers/examination/personal-information.js
- packages/forms-web-app/src/controllers/examination/select-file.js
- packages/forms-web-app/src/routes/config.js
- packages/forms-web-app/src/routes/examination/index.js
- packages/forms-web-app/src/views/pages/examination/check-deadline-item.njk
- packages/forms-web-app/src/views/pages/examination/personal-information-which.njk
- packages/forms-web-app/src/views/pages/examination/personal-information.njk
- packages/forms-web-app/src/views/pages/examination/select-file.njk
- https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-585
- https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-586
- https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-642
> Personal Information

- packages/forms-web-app/__tests__/unit/controllers/examination/enter-comment.test.js
- packages/forms-web-app/src/app.js
- packages/forms-web-app/src/routes/config.js
> fix(reset validation to default): reset validation to default

- .gitignore
hosted env does not allow express-fileUpload to create the directory
> fix(file upload): commit empty upload directory

- package-lock.json
- packages/applications-service-api/__tests__/unit/controllers/submissions.test.js
- packages/applications-service-api/__tests__/unit/middleware/validator/submission.test.js
- packages/applications-service-api/__tests__/unit/services/ni.file.service.test.js
- packages/applications-service-api/__tests__/unit/utils/md5.test.js
- packages/applications-service-api/__tests__/unit/utils/pdf.test.js
- packages/applications-service-api/api/openapi.yaml
- packages/applications-service-api/package.json
- packages/applications-service-api/src/controllers/submissions.js
- packages/applications-service-api/src/lib/config.js
- packages/applications-service-api/src/middleware/validator/submission.js
- packages/applications-service-api/src/services/ni.api.service.js
- packages/applications-service-api/src/services/ni.file.service.js
- packages/applications-service-api/src/utils/md5.js
- packages/applications-service-api/src/utils/pdf.js
- adds functionality to generate a PDF file containing the comment and upload it to NI
- add validation of max length/size of `representation` (<= 65234 chars)
> ASB-801: upload submission comment as pdf file to ni

- docker-compose.yml
- packages/applications-service-api/__tests__/unit/lib/notify.test.js
- packages/applications-service-api/__tests__/unit/middleware/validator/openapi.test.js
- packages/applications-service-api/__tests__/unit/services/submission.service.test.js
- packages/applications-service-api/src/error/apiError.js
- packages/applications-service-api/src/lib/config.js
- packages/applications-service-api/src/lib/notify.js
- packages/applications-service-api/src/middleware/apiErrorHandler.js
- packages/applications-service-api/src/middleware/validator/openapi.js
- packages/applications-service-api/src/services/submission.service.js
- further develop the `POST /api/v1/submissions/{submissionId}/complete` endpoint
- integrate with GOV notify to send email notification
- fetch project details to insert project name/email address into the notification template
> asb-779: submission complete email

- packages/forms-web-app/__tests__/unit/controllers/examination/add-another-deadline-item/controller.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/check-submission-item/controller.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/check-submission-item/utils/get-back-link-url.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/select-deadline/controller.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/select-deadline/utils/get-back-link-url.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/select-deadline/utils/get-page-data.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/select-deadline/utils/get-redirect-url.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/select-deadline/utils/handle-edit-mode-submission-item-id.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/session/submission-items-session.test.js
- packages/forms-web-app/src/controllers/examination/add-another-deadline-item/controller.js
- packages/forms-web-app/src/controllers/examination/check-submission-item/controller.js
- packages/forms-web-app/src/controllers/examination/check-submission-item/utils/get-back-link-url.js
- packages/forms-web-app/src/controllers/examination/enter-comment/controller.js
- packages/forms-web-app/src/controllers/examination/personal-information-which/controller.js
- packages/forms-web-app/src/controllers/examination/personal-information/controller.js
- packages/forms-web-app/src/controllers/examination/select-deadline/controller.js
- packages/forms-web-app/src/controllers/examination/select-deadline/utils/get-back-link-url.js
- packages/forms-web-app/src/controllers/examination/select-deadline/utils/get-page-data.js
- packages/forms-web-app/src/controllers/examination/select-deadline/utils/get-redirect-url.js
- packages/forms-web-app/src/controllers/examination/select-deadline/utils/handle-edit-mode-submission-item-id.js
- packages/forms-web-app/src/controllers/examination/select-file/controller.js
- packages/forms-web-app/src/controllers/examination/select-if-want-to-delete-data/controller.js
- packages/forms-web-app/src/controllers/examination/session/deadlineItems-session.js
- packages/forms-web-app/src/controllers/examination/session/submission-items-session.js
- packages/forms-web-app/src/middleware/unset-edit-mode-submission-item-id.js
- packages/forms-web-app/src/routes/examination/index.js
- [Submitted deadline item not removed when user changes deadline item](https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-934)
- [Back button on Check your deadline item answers page](https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-935)
> fix: submitted deadline item not removed when user changes deadline item

- packages/applications-service-api/__tests__/unit/controllers/documents.v3.test.js
- packages/applications-service-api/__tests__/unit/services/document.v3.service.test.js
- packages/applications-service-api/src/controllers/documents.v3.js
- packages/applications-service-api/src/models/document.js
- packages/applications-service-api/src/services/document.v3.service.js
- implementation of search filtering for the `POST /v3/documents` endpoint
> feat(applications-service-api): documents v3 endpoint apply search filters

- packages/applications-service-api/__tests__/unit/services/submission.service.test.js
- packages/applications-service-api/src/services/submission.service.js
- set the validated field for submissions, when invoking the /submissions/:id/complete endpoint
> feat(applications-service-api): set submission validated field on complete

- packages/applications-service-api/__tests__/unit/services/document.v3.service.test.js
- packages/applications-service-api/src/services/document.v3.service.js
- fixes issue with document v3 endpoint where documents with Stage of `0` or `NULL` were included in the results
> fix(applications-service-api): add stage != 0 or null condition to document v3 query

- packages/forms-web-app/src/views/projects/documents.njk
- packages/forms-web-app/src/views/projects/representations.njk
[Search field - add label for screen reader “search” - applicable to relevant reps and doc library](https://pins-ds.atlassian.net/browse/ASB-834)
> ASB-834: Apply accessibility attributes to doc/reps search bar

- packages/forms-web-app/src/controllers/projects/examination-timetable.js
always use the path arg for setting the case ref
> fix(examination timetable): 

- packages/forms-web-app/__tests__/unit/controllers/projects/examination-timetable.test.js
- packages/forms-web-app/src/controllers/projects/examination-timetable.js
> fix(examination timetable): always use the path arg 

- packages/forms-web-app/__tests__/unit/controllers/examination/enter-comment/controller.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/enter-comment/utils/get-page-data.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/name/controller.test.js
- packages/forms-web-app/__tests__/unit/controllers/examination/name/utils/page-data.test.js
- packages/forms-web-app/src/controllers/examination/enter-comment/controller.js
- packages/forms-web-app/src/controllers/examination/enter-comment/utils/get-page-data.js
- packages/forms-web-app/src/controllers/examination/name/controller.js
- packages/forms-web-app/src/controllers/examination/name/utils/get-page-data.js
- packages/forms-web-app/src/routes/examination/index.js
- packages/forms-web-app/src/utils/sanitise-form-post.js
- packages/forms-web-app/src/views/pages/examination/enter-comment.njk
- packages/forms-web-app/src/views/pages/examination/name.njk
Use existing Client side sanitisation and JSON fetch pattern on fields:
- name
- comment
> fix: sanitise examination - have your say

- package-lock.json
ran `npm i` to update package-lock
> fix: update package-lock.json

- packages/applications-service-api/__tests__/unit/controllers/documents.v3.test.js
- packages/applications-service-api/__tests__/unit/services/document.v3.service.test.js
- packages/applications-service-api/api/openapi.yaml
- packages/applications-service-api/src/controllers/documents.v3.js
- packages/applications-service-api/src/services/document.v3.service.js
POST  /api/v3/documents
```
{
"caseReference": "TR040009",
"searchTerm": "string",
"page": 1,
"datePublishedFrom": "",
"datePublishedTo": ""
"filters": [
{
"name": "stage",
"value": 1,
"type": [
{
"value": "Plans"
}
]
}
]
}
```
> feat(applications-api): filter documents by published date

- packages/forms-web-app/__tests__/unit/utils/is-before-or-after-date.test.js
- packages/forms-web-app/src/utils/is-before-or-after-date.js
- Reworked imp and tests to match original A/C
- Added handling of all dates being invalid
> fix(exam-timetable): incorrect closing date

- e2e-tests/cypress/e2e/register-to-say-about-national-infra-project/register-to-say-about-national-infra-project.js
Fix broken test that had route to have your say relative to project page.
> test(register-to-say-about-national-infra-project.js): fix test for have your say link

- packages/applications-service-api/api/openapi.yaml
I have put some new lines in to break up this 1585 line file 😃
> feat: add advice openAPI spec

- packages/forms-web-app/__tests__/unit/controllers/projects/documents/controller.component.test.js
- packages/forms-web-app/__tests__/unit/controllers/projects/documents/utils/is-filters-displayed.test.js
- packages/forms-web-app/src/controllers/projects/documents/controller.js
- packages/forms-web-app/src/controllers/projects/documents/utils/is-filters-displayed.js
- packages/forms-web-app/src/views/projects/documents.njk
https://pins-ds.atlassian.net/browse/ASB-1240?atlOrigin=eyJpIjoiYTg2ZTYzMmI2OGY4NGRhOGI2ODA2ODE2MDdjMTJmODEiLCJwIjoiaiJ9
> Fix: Filter options do not show when there are no matching results

- packages/forms-web-app/src/views/components/ui/checkbox-accordion.njk
https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-1208
> ASB-1208: Set aria controls to valid values

- packages/forms-web-app/__tests__/unit/middleware/set-locals-display-cookie-banner-value.test.js
- packages/forms-web-app/src/app.js
- packages/forms-web-app/src/middleware/set-locals-display-cookie-banner-value.js
- packages/forms-web-app/src/views/includes/cookie-banner.njk
https://pins-ds.atlassian.net/browse/ASB-829?atlOrigin=eyJpIjoiNDhkNWY2YmViYTRkNDdkN2EzN2NhMmNkYjU2N2MxOWIiLCJwIjoiaiJ9
> ASB-829: Fix Cookie Banner Jolt

- packages/forms-web-app/src/views/register/common/email-address.njk
https://pins-ds.atlassian.net/browse/ASB-847?atlOrigin=eyJpIjoiMThlMGM5ZTY4MjA3NGZkOTgxNDhiZGNmMWE3ZGU5ZGIiLCJwIjoiaiJ9
> ASB-847: Email Address White Space Error

- packages/forms-web-app/src/views/components/section/events.njk
https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?modal=detail&selectedIssue=ASB-1207
> ASB-1207: Examination timetable w3c validation warnings

- packages/applications-service-api/__tests__/unit/controllers/advice.test.js
- packages/applications-service-api/src/controllers/advice.js
- packages/forms-web-app/src/pages/projects/components/project-pages-template.njk
- packages/forms-web-app/src/pages/projects/section-51/index.njk
- packages/forms-web-app/src/pages/projects/section-51/section-51-advice-detail/index.njk
- packages/forms-web-app/src/pages/projects/section-51/section-51-advice-detail/section-51-advice-detail.controller.component.test.js
- packages/forms-web-app/src/pages/projects/section-51/section-51-advice-detail/section-51-advice-detail.controller.js
- packages/forms-web-app/src/pages/projects/section-51/section-51-advice-detail/utils/get-attachments.js
- packages/forms-web-app/src/pages/projects/section-51/section-51-advice-detail/utils/get-back-link-url.js
- packages/forms-web-app/src/pages/projects/section-51/section-51-advice-detail/utils/get-breadcrumbs-items.js
- packages/forms-web-app/src/pages/projects/section-51/section-51-advice-detail/utils/get-enquiry-summary-list.js
- packages/forms-web-app/src/pages/projects/section-51/section-51-advice-detail/utils/get-navigation-urls.js
- packages/forms-web-app/src/pages/projects/section-51/section-51-advice-detail/utils/get-navigation-urls.unit.test.js
- packages/forms-web-app/src/pages/projects/section-51/section-51-advice-detail/utils/get-page-view-model.js
- packages/forms-web-app/src/pages/projects/section-51/section-51.router.js
- packages/forms-web-app/src/pages/projects/section-51/section-51.router.unit.test.js
- packages/forms-web-app/src/services/advice.service.js
- packages/forms-web-app/src/services/advice.service.unit.test.js
https://pins-ds.atlassian.net/browse/ASB-879?atlOrigin=eyJpIjoiNjA4OThmZDNkM2JiNDMxM2FmYzRhNzE0MGE2N2M4NmUiLCJwIjoiaiJ9
> ASB-879: Section 51 Advice Detail Page

- packages/forms-web-app/src/pages/projects/components/project-pages-template.njk
- packages/forms-web-app/src/pages/projects/examination-timetable/index.njk
- packages/forms-web-app/src/pages/projects/section-51/section-51-advice-detail/index.njk
https://pins-ds.atlassian.net/browse/ASB-1113?atlOrigin=eyJpIjoiMDJjYmYxYzUyZDRiNDRhZDk4OTcxMzYyZmEwZGMwMTEiLCJwIjoiaiJ9
> ASB-1113: Examination timetable content update

- azure-pipelines-deploy.yml
- make deployment of `back-office-subscribers` opt-in by default, for time being
> ci(back-office-subscribers): make deployment opt-in

- packages/forms-web-app/src/pages/projects/_middleware/_utils/get-vertical-tabs.js
- packages/forms-web-app/src/pages/projects/_middleware/_utils/get-vertical-tabs.test.js
- packages/forms-web-app/src/pages/projects/_middleware/middleware.js
- packages/forms-web-app/src/pages/projects/documents/utils/get-application-data.js
- packages/forms-web-app/src/pages/projects/examination-timetable/utils/events/get-events.js
https://pins-ds.atlassian.net/browse/ASB-1112?atlOrigin=eyJpIjoiYzY3ODEzZTM2ZWE3NDkwMDgxNTM4MGFjNGUzYjNmZTQiLCJwIjoiaiJ9
> ASB-1112: Exam timetable link on left hand navigation-Rule 8 letter

- packages/applications-service-api/__tests__/unit/utils/documentFilterLabelMapper.test.js
- packages/applications-service-api/src/utils/documentFilterLabelMapper.js
https://pins-ds.atlassian.net/browse/ASB-1008?atlOrigin=eyJpIjoiOTc3YWMyNjU3YWU1NGUzYmFiMjNiYjhmOWEyNDg0YzYiLCJwIjoiaiJ9
> ASB-1008: Relabel “Decision” filter  to 'Recommendation and Decision' filter on Documents page

- package-lock.json
- packages/forms-web-app/__tests__/unit/scripts/sw.test.js
- packages/forms-web-app/src/public/scripts/sw.script.js
https://pins-ds.atlassian.net/browse/ASB-1477?atlOrigin=eyJpIjoiNzY2ODc5OTk0Mzc1NDFlYjlmMjFkZjFiOWNmNzI5MmUiLCJwIjoiaiJ9
> ASB-1477: Radio buttons not recognised in Firefox

- README.md
- package-lock.json
- package.json
- packages/applications-service-api/prisma/schema.prisma
- updates to README
- setup/troubleshooting info for prisma errors
- removed lots of old/redundant info
- added some info about release, deployment, docker
- added extra binary target for prisma to cover linux alpine on x86
- removed prisma from root package.json, not needed
> docs: readme updates

- docker-compose.yml
- package-lock.json
- packages/applications-service-api/__tests__/integration/subscriptions.test.js
- packages/applications-service-api/__tests__/unit/controllers/subscriptions.test.js
- packages/applications-service-api/__tests__/unit/lib/eventClient.test.js
- packages/applications-service-api/__tests__/unit/services/backoffice.publish.service.test.js
- packages/applications-service-api/api/openapi.yaml
- packages/applications-service-api/package.json
- packages/applications-service-api/src/controllers/subscriptions.js
- packages/applications-service-api/src/lib/config.js
- packages/applications-service-api/src/lib/eventClient.js
- packages/applications-service-api/src/routes/subscriptions.js
- packages/applications-service-api/src/services/backoffice.publish.service.js
adds `PUT /api/v1/subscriptions/{caseReference}` endpoint
> feat(applications-service-api): confirm subscription endpoint

- packages/forms-web-app/src/views/register/agent/name-of-organisation.njk
Fix broken link after refactor, add base url.
> fix: fix broken link to add correct base url

- packages/forms-web-app/__tests__/unit/scripts/sw.test.js
- packages/forms-web-app/src/public/scripts/sw.script.js
https://pins-ds.atlassian.net/browse/ASB-1645?atlOrigin=eyJpIjoiZTk0YWNjNzE4YzE1NDgxOGFkMmIzYTUxOWE2Y2E2OTAiLCJwIjoiaiJ9
> Fix: ASB-1645: Handle multiple form data values with the same name

- packages/forms-web-app/src/pages/projects/project-updates/email/view.njk
https://pins-ds.atlassian.net/browse/ASB-1682?atlOrigin=eyJpIjoiODdiNWE3YjMwOGQxNGNjN2I2Y2YzYmVhNjJkYzU4MjAiLCJwIjoiaiJ9
> ASB-1682 - Fix: Correct capitalisation of letter

- packages/forms-web-app/src/pages/projects/get-updates/subscribed/controller.js
- packages/forms-web-app/src/pages/projects/get-updates/subscribed/controller.test.js
https://pins-ds.atlassian.net/browse/ASB-1695?atlOrigin=eyJpIjoiN2YyYzBhNTY4YjQ2NDYwOTg1M2UyMzg2MmNlMzFhNTciLCJwIjoiaiJ9
> ASB-1695 - Fix: Rename query parameter

- packages/applications-service-api/prisma/migrations/20230815090647_add_representation_table/migration.sql
- packages/applications-service-api/prisma/migrations/20230815143109_add_representationid_to_document/migration.sql
- packages/applications-service-api/prisma/schema.prisma
- adds `Representation` table (asb-1701)
- adds `representationId` to `Document` table (asb-1735)
> add Representation table and representationId to Document table

- packages/forms-web-app/src/pages/projects/get-updates/unsubscribe/view.njk
https://pins-ds.atlassian.net/browse/ASB-1760?atlOrigin=eyJpIjoiN2RjMDBhYTM2MGJmNDcwMGEzMGNmMjEzODY1MjdhNzEiLCJwIjoiaiJ9
> ASB-1760: Fix - Add full stop

- packages/applications-service-api/src/utils/document.mapper.js
- packages/forms-web-app/src/pages/projects/project-information/includes/stages/examination/description.njk
Ticket: https://pins-ds.atlassian.net/browse/ASB-1771
> fix: added default value for rule8Document.path

- packages/applications-service-api/__tests__/unit/services/application.services.test.js
- packages/applications-service-api/api/openapi.yaml
- packages/applications-service-api/src/services/application.service.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-1740
> feat: get applications api sorting

- packages/forms-web-app/src/pages/projects/project-information/utils/pre-examination-sub-stages.js
- packages/forms-web-app/src/pages/projects/project-information/utils/pre-examination-sub-stages.unit.test.js
Bug Fix https://pins-ds.atlassian.net/browse/ASB-1785
Representation period should be treated as closed when website date is not set.
> fix(pre-examination-sub-stages.js): fix Pre-exam issue where websiteDate is null

- packages/forms-web-app/src/pages/projects/project-information/__snapshots__/controller.component.test.js.snap
- packages/forms-web-app/src/pages/projects/project-information/controller.component.test.js
- packages/forms-web-app/src/pages/projects/project-information/includes/stages/pre-examination/description.njk
Add Links to process guides on project stage, as per bug- https://pins-ds.atlassian.net/browse/ASB-1789
> fix(stages/pre-examination/description.njk): add links to process guides

- packages/applications-service-api/__tests__/integration/applications.test.js
- packages/applications-service-api/__tests__/unit/repositories/project.ni.repository.test.js
- packages/applications-service-api/__tests__/unit/services/application.service.test.js
- packages/applications-service-api/api/openapi.yaml
- packages/applications-service-api/src/repositories/project.ni.repository.js
- packages/applications-service-api/src/services/application.service.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-1752
Adds searchTerm parameter to search for PromoterName and ProjectName in get applications endpoint.
> feat(applications-service-api): get applications searching

- packages/applications-service-api/src/repositories/project.ni.repository.js
- packages/applications-service-api/src/utils/map-applications-to-csv.js
Fixed bugs to test this ticket: https://pins-ds.atlassian.net/browse/ASB-1755
- Default `options `object `parameter` in getAllApplications repository
- CSV `'GPS co-ordinates'`  null checks `LongLat` value and passes default empty string
> fix: get applications csv download issues

- packages/forms-web-app/src/pages/_fixtures/application-data.js
- packages/forms-web-app/src/pages/projects/_middleware/middleware.component.test.js
- packages/forms-web-app/src/pages/projects/project-information/__snapshots__/controller.component.test.js.snap
- packages/forms-web-app/src/pages/projects/project-information/includes/stages/post-decision/description.njk
- packages/forms-web-app/src/pages/projects/project-information/utils/formatters.js
- packages/forms-web-app/src/utils/project-stages.js
-amend post decision stage name and prevent decision text from rendering if decision date is not available
> fix(project-information): amend post decision stage content

- packages/applications-service-api/__tests__/integration/applications.test.js
- packages/applications-service-api/__tests__/unit/repositories/project.ni.repository.test.js
- packages/applications-service-api/__tests__/unit/services/application.service.test.js
- packages/applications-service-api/src/controllers/applications.js
- packages/applications-service-api/src/repositories/project.ni.repository.js
- packages/applications-service-api/src/services/application.service.js
- packages/applications-service-api/src/utils/application.mapper.js
Ticket: https://github.com/Planning-Inspectorate/applications-service/compare/fix/asb-1831-get-application-filters
> fix: get applications pagination count using filters

- packages/forms-web-app/src/pages/projects/_utils/get-application-data.js
- packages/forms-web-app/src/pages/projects/project-information/__snapshots__/controller.component.test.js.snap
- packages/forms-web-app/src/pages/projects/project-information/controller.component.test.js
- packages/forms-web-app/src/pages/projects/project-information/includes/stages/pre-application/description.njk
if anticipatedDateOfSubmission is not available, show anticipatedSubmissionDateNonSpecific instead, if available.
If both not available don't show the submition period text
> feat(project-information): update template

- packages/forms-web-app/src/pages/projects/_utils/get-application-data.js
- packages/forms-web-app/src/pages/projects/project-information/__snapshots__/controller.component.test.js.snap
- packages/forms-web-app/src/pages/projects/project-information/controller.component.test.js
- packages/forms-web-app/src/pages/projects/project-information/includes/about.njk
https://pins-ds.atlassian.net/browse/ASB-1896?atlOrigin=eyJpIjoiZTg0YmI2ZjU2MTI2NDUyN2JhZjY3NWI4N2IzY2U5NzkiLCJwIjoiaiJ9
> Feature: ASB-1896 - Add Applicant Name to Project Information page

- packages/forms-web-app/src/pages/projects/project-information/__snapshots__/controller.component.test.js.snap
- packages/forms-web-app/src/pages/projects/project-information/controller.unit.test.js
- packages/forms-web-app/src/pages/projects/project-information/includes/contact.njk
- packages/forms-web-app/src/pages/projects/project-information/includes/stages/_includes/email-request-text.njk
- packages/forms-web-app/src/pages/projects/project-information/includes/stages/examination/description.njk
- packages/forms-web-app/src/pages/projects/project-information/includes/stages/pre-examination/description.njk
- packages/forms-web-app/src/pages/projects/project-information/utils/get-page-data.js
https://pins-ds.atlassian.net/browse/ASB-1840?atlOrigin=eyJpIjoiMGFmZGMxMDczMGZhNGY5NWFlNGMyZTIxYjNlMmRiN2EiLCJwIjoiaiJ9
> Feature: ASB-1840 - Update content pre-examination and examination content

- .github/pull_request_template.md
Github PR template to have a better format for PRs (similar to BO repo). Would be useful to see ticket numbers straight from PR instead of looking at messages or branch names. Plus it would encourage us to add more information on how to reproduce and test the changes when reviewing the PR.
> docs: github PR template

- packages/forms-web-app/src/pages/register-of-applications/utils/get-register-of-applications-query-string.js
- packages/forms-web-app/src/pages/register-of-applications/utils/get-register-of-applications-query-string.unit.test.js
https://pins-ds.atlassian.net/browse/ASB-1897
Changed default sort order from ProjectName to DateOfDCOSubmission
> fix: changed default sort order from ProjectName to DateOfDCOSubmission

- package-lock.json
- packages/applications-service-api/package.json
- packages/applications-service-api/prisma/schema.prisma
- packages/back-office-subscribers/.gitignore
- packages/back-office-subscribers/README.md
- packages/back-office-subscribers/nsip-project/__tests__/index.test.js
- packages/back-office-subscribers/nsip-project/index.js
- packages/back-office-subscribers/package.json
ASB-1846
- schema changes to the `Project` table in Applications database
- add new columns for new fields in the [nsip-project schema](https://github.com/Planning-Inspectorate/back-office/blob/main/apps/api/src/message-schemas/events/nsip-project.schema.json)
- make all dates `Date` type (was previously `DateTime`)
- add README for `back-office-subscribers` package
> fix(back-office-subscribers): nsip-project property updates and selection

- packages/forms-web-app/__tests__/unit/routes/index.test.js
- packages/forms-web-app/src/api/_services/get-applications-csv.js
- packages/forms-web-app/src/api/_utils/get-url/applications-download/index.js
- packages/forms-web-app/src/api/_utils/get-url/applications-download/index.test.js
- packages/forms-web-app/src/api/_utils/get-url/index.js
- packages/forms-web-app/src/api/applications-download/config.js
- packages/forms-web-app/src/api/applications-download/controller.js
- packages/forms-web-app/src/api/applications-download/controller.test.js
- packages/forms-web-app/src/api/applications-download/router.js
- packages/forms-web-app/src/api/config.js
- packages/forms-web-app/src/api/router.js
- packages/forms-web-app/src/pages/_fixtures/applications/get-applications-fixture.js
- packages/forms-web-app/src/pages/project-search/controller.test.js
- packages/forms-web-app/src/pages/project-search/utils/get-page-data.js
- packages/forms-web-app/src/pages/project-search/view.njk
- packages/forms-web-app/src/pages/register-of-applications/controller.test.js
- packages/forms-web-app/src/pages/register-of-applications/utils/get-page-data.js
- packages/forms-web-app/src/pages/register-of-applications/view.njk
- packages/forms-web-app/src/routes/index.js
- packages/forms-web-app/src/services/applications.service.js
https://pins-ds.atlassian.net/browse/ASB-1849?atlOrigin=eyJpIjoiMzY3OTZjNzdmZGNkNDNlOTk4ODY3MTMyZTcwYzRmODQiLCJwIjoiaiJ9
Add proxy to handle download request from the api
> Fix: ASB-1849 - Applications CSV Download Link

- packages/applications-service-api/prisma/migrations/20231004105518_project_column_updates/migration.sql
ASB-1846:
Added migration file for Project table updates
> chore(applications-service-api): add project column migration file

- packages/forms-web-app/src/lib/application-api-wrapper.js
- packages/forms-web-app/src/pages/projects/relevant-representations/_utils/get-relevant-representations-query.js
- packages/forms-web-app/src/pages/projects/relevant-representations/_utils/get-relevant-representations-query.test.js
- packages/forms-web-app/src/pages/projects/relevant-representations/_utils/is-query-search-or-type-present.js
- packages/forms-web-app/src/pages/projects/relevant-representations/_utils/is-query-search-or-type-present.test.js
- packages/forms-web-app/src/pages/projects/relevant-representations/includes/pagination.njk
- packages/forms-web-app/src/pages/projects/relevant-representations/includes/results-per-page.njk
- packages/forms-web-app/src/pages/projects/relevant-representations/representations.js
- packages/forms-web-app/src/pages/projects/relevant-representations/representations.njk
- packages/forms-web-app/src/pages/projects/relevant-representations/representations.test.js
https://pins-ds.atlassian.net/browse/ASB-1131?atlOrigin=eyJpIjoiYTUxYjk0NjZiM2QxNDNjZmI1M2JkZmFiYzMyZWFmNDUiLCJwIjoiaiJ9
> Feature: ASB-1131 - Add results per page to representations page

- packages/forms-web-app/src/pages/process-guide/_utils/get-back-link-url.js
- packages/forms-web-app/src/pages/process-guide/_utils/get-back-link-url.test.js
- packages/forms-web-app/src/pages/process-guide/_utils/get-page-data.js
- packages/forms-web-app/src/pages/process-guide/controller.js
- packages/forms-web-app/src/pages/process-guide/controller.test.js
- packages/forms-web-app/src/pages/projects/project-information/__snapshots__/controller.component.test.js.snap
- packages/forms-web-app/src/views/components/ui/vertical-tabs.njk
- packages/forms-web-app/src/views/components/wrappers/related-guides-wrapper.njk
- packages/forms-web-app/src/views/decision-making-process-guide/recommendation-and-decision.njk
- packages/forms-web-app/src/views/decision-making-process-guide/what-happens-after-the-decision-is-made.njk
- packages/forms-web-app/src/views/includes/dco-step-by-step-navigation.njk
https://pins-ds.atlassian.net/browse/ASB-1945?atlOrigin=eyJpIjoiNThjMTRkMzE2ODg3NDliODhjZTBhNDZiNjZlMTMzMzciLCJwIjoiaiJ9
https://pins-ds.atlassian.net/browse/ASB-1394?atlOrigin=eyJpIjoiNzY1MDQ3YWUwNzViNDY0MzkxNWE2ZjU2MTFlZmRkMjciLCJwIjoiaiJ9
> Fix: ASB-1945 - Process guide issues

- azure-pipelines-build.yml
- packages/back-office-subscribers/package.json
Merging https://github.com/Planning-Inspectorate/applications-service/pull/863 has introduced an issue on the build pipeline which should be fixed by removing the below stage.
> fix: backoffice sub node_modules

- packages/applications-service-api/__tests__/integration/submission.test.js
- packages/applications-service-api/__tests__/unit/lib/notify.test.js
- packages/applications-service-api/__tests__/unit/routes/submissions.test.js
- packages/applications-service-api/__tests__/unit/services/submission.service.test.js
- packages/applications-service-api/api/openapi.yaml
- packages/applications-service-api/src/controllers/submissions.js
- packages/applications-service-api/src/lib/notify.js
- packages/applications-service-api/src/routes/submissions.js
- packages/applications-service-api/src/services/submission.service.js
ASB-1837
Adapt the `POST /api/v1/submissions/{submissionId}/complete` endpoint to accept requests for both NI and Back Office cases.
> feat(applications-service-api): submission complete back office integration

- packages/forms-web-app/src/pages/process-guide/_utils/get-process-guide-stages.test.js
- packages/forms-web-app/src/pages/process-guide/_utils/get-process-guide-steps.test.js
- packages/forms-web-app/src/pages/process-guide/pre-application/config.js
- packages/forms-web-app/src/pages/process-guide/pre-application/config.test.js
- packages/forms-web-app/src/pages/projects/project-information/controller.unit.test.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-1993
> fix(web/process-guide): update pre-application process guide text

- docker-compose.yml
- package-lock.json
- packages/applications-service-api/package.json
- packages/applications-service-api/src/lib/config.js
- packages/applications-service-api/src/main.js
- packages/forms-web-app/package.json
- packages/forms-web-app/src/config.js
- packages/forms-web-app/src/server.js
ASB-1971
- Add feature flag for enabling use of Application Insights
- Initialise Application Insights library on app startup if feature flag is enabled
> feat: add app insights sdk and feature toggle

- packages/forms-web-app/src/pages/project-search/controller.test.js
- packages/forms-web-app/src/pages/project-search/utils/filters/get-filters-view-model.js
- packages/forms-web-app/src/pages/project-search/utils/filters/get-filters.component.test.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-1969
Location filters on project-search ordered from north to south
> feat: project-search location filters order

- packages/applications-service-api/prisma/migrations/20231115161654_add_advice_table/migration.sql
- packages/applications-service-api/prisma/schema.prisma
- packages/applications-service-api/prisma/seed.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-2013
Adds Advice schema and seeding for the upcoming consuming section 51 advice.
> feat: added advice schema 

- packages/back-office-subscribers/nsip-advice/__tests__/index.test.js
- packages/back-office-subscribers/nsip-advice/function.json
- packages/back-office-subscribers/nsip-advice/index.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-2014
This PR creates a back office subscriber function to consume s51 advice messages and save it to our database
2. Run azurite `npx azurite` and this function `npm run start:dev nsip-advice`
3. Make a POST request to `http://localhost:7071/admin/functions/nsip-advice` with this body:
```
{
"input": "{\"adviceId\":1,\"adviceReference\":\"TR0200007-0005\",\"caseReference\":\"BC0110001\",\"caseId\":130,\"title\":\"Advice title\",\"from\":\"Advice from\",\"agent\":\"Advice agent\",\"method\":\"Advice method\",\"enquiryDate\":\"2021-06-01T00:00:00.000Z\",\"enquiryDetails\":\"Advice enquiry details\",\"adviceGivenBy\":\"Advice given …
```
> feat: advice bo consumer function

- packages/applications-service-api/__tests__/__data__/interestedParty.js
- packages/applications-service-api/__tests__/integration/interestedParty.test.js
- packages/applications-service-api/__tests__/unit/controllers/interested-party.test.js
- packages/applications-service-api/__tests__/unit/services/backoffice.publish.service.test.js
- packages/applications-service-api/__tests__/unit/services/interestedParty.ni.service.test.js
- packages/applications-service-api/__tests__/unit/services/interestedParty.service.test.js
- packages/applications-service-api/__tests__/unit/utils/interestedParty.mapper.test.js
- packages/applications-service-api/src/controllers/interested-party.js
- packages/applications-service-api/src/lib/config.js
- packages/applications-service-api/src/lib/notify.js
- packages/applications-service-api/src/services/backoffice.publish.service.js
- packages/applications-service-api/src/services/interestedParty.ni.service.js
- packages/applications-service-api/src/services/interestedParty.service.js
- packages/applications-service-api/src/utils/interestedParty.mapper.js
ASB-1468
Integration of `POST /interested-party` endpoint with Back Office
- Check if case reference is a BO value
- Publish message to `register-representation` topic
- Send confirmation email to interested party with reference number
- Moved 'end to test' style tests from `__tests__/unit/controllers/interested-party.test.js` to `__tests__/integration/interestedParty.test.js`
> feat(applications-service): interested party backoffice integration

- packages/forms-web-app/src/pages/projects/representations/index/_includes/results.njk
- packages/forms-web-app/src/pages/projects/representations/index/_utils/get-representations-view-model.js
- packages/forms-web-app/src/pages/projects/representations/index/controller.test.js
- packages/forms-web-app/src/pages/projects/representations/representation/controller.test.js
https://pins-ds.atlassian.net/browse/ASB-2075?atlOrigin=eyJpIjoiNmI0YjRkNThmNzA4NGVkZjhmYmE3MmQ1ZDlkMWRjOGUiLCJwIjoiaiJ9
> Fix: ASB-2075 - Representations display attachments

- packages/back-office-subscribers/nsip-project-unpublish/__tests__/index.test.js
- packages/back-office-subscribers/nsip-project-unpublish/function.json
- packages/back-office-subscribers/nsip-project-unpublish/index.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-1368
This PR adds the back-office subscriber function for unpublishing projects. 
2. Run azurite `npx azurite` and this function `npx func start nsip-project-unpublish`
3. Make a POST request to `http://localhost:7071/admin/functions/nsip-project-unpublish` with this body:
```
{
"input": "{\"caseReference\":\"mock-project-id\"}"
}
```
> feat: project unpublish bo function

- e2e-tests/cypress/e2e/registration-comments.feature
- e2e-tests/cypress/e2e/registration-comments/PageObjects/PO_RegComments.js
- e2e-tests/cypress/e2e/registration-comments/registration-comments.js
- packages/e2e_tests/cypress/pageObject/Relevant-representations/PO_RelevantReps.js
- packages/forms-web-app/src/pages/examination/have-your-say/no-deadlines-view.njk
- packages/forms-web-app/src/pages/examination/have-your-say/view.njk
- packages/forms-web-app/src/pages/projects/register/index/view.njk
- packages/forms-web-app/src/pages/projects/representations/index/_includes/results.njk
- packages/forms-web-app/src/pages/projects/representations/representation/view.njk
https://pins-ds.atlassian.net/browse/ASB-2096?atlOrigin=eyJpIjoiMDMyZTIyYzViYWUxNGVmOGFiMjM1Njc2NmU4N2Y4NTMiLCJwIjoiaiJ9
> Feature: ASB-2096 - 'Register to have your say' and 'Have your say' - Content update

- packages/forms-web-app/src/views/components/core/pins-header-default.njk
https://pins-ds.atlassian.net/browse/ASB-2144?atlOrigin=eyJpIjoiODUyYzM3ZTMxYjMzNGEzNWIwYzM4NjY4OTAyNmM1ODgiLCJwIjoiaiJ9
> Fix: ASB-2144 - Add data attribute to back link

- e2e-tests/cypress/e2e/overview-page.feature
- e2e-tests/cypress/e2e/overview-page/overview-page.js
- packages/forms-web-app/src/pages/router.js
- [] I have referenced the ticket number above
- [] I have included unit tests to cover any testable code changes
> fix(router.js): put detailed information page behind feature flag

- packages/applications-service-api/prisma/migrations/20231205140532_update_representation_types/migration.sql
- packages/applications-service-api/prisma/schema.prisma
- packages/back-office-subscribers/nsip-representation/__tests__/index.test.js
- packages/back-office-subscribers/nsip-representation/index.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-2079
This PR updates the back office subscriber function for representation messages. It also includes a prisma schema update to match the [message schema](https://github.com/Planning-Inspectorate/back-office/blob/main/apps/api/src/message-schemas/events/nsip-representation.schema.json).
2. Run azurite `npx azurite` and this function `npm run start:dev nsip-representation`
3. Make a POST request to `http://localhost:7071/admin/functions/nsip-representation` with this body:
```
{
"input": "{\"representationId\":123,\"caseRef\":\"CASE-REF\",\"caseId\":123,\"referenceId\":\"reference-id\",\"status\":\"published\",\"dateReceived\":\"2023-01-01T09:00:00.000Z\",\"redacted\": …
```
> feat: update representation bo function

- packages/back-office-subscribers/__data__/service-user.js
- packages/back-office-subscribers/nsip-service-user/__tests__/index.test.js
- packages/back-office-subscribers/nsip-service-user/index.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-2011
Update to https://github.com/Planning-Inspectorate/applications-service/pull/938 - updates the function to work correctly with new valid `serviceTypeUser` values.
2. Run azurite `npx azurite` and this function `npm run start:dev nsip-service-user`
3. Make a POST request to `http://localhost:7071/admin/functions/nsip-service-user` with this body:
```
{
"input": "{\"serviceUserType\":\"Applicant\",\"id\":\"1234\",\"firstName\":\"John\",\"lastName\":\"Smith\",\"organisation\":\"ACME\",\"organisationType\":\"Sole Trader\",\"caseReference\":\"B123456\",\"emailAddress\":\"test@test.com\",\"webAddress\":\"www.test.com\",\"telephoneNumber\":\"0123456789\"}"
}
```
Note, …
> feat: update service user bo function

- docker-compose.yml
- packages/forms-web-app/src/config.js
- packages/forms-web-app/src/views/includes/header.njk
- packages/forms-web-app/src/views/layouts/main.njk
Ticket: https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166
> feat(web/applications): move primary navigation behind a feature flag

- packages/applications-service-api/prisma/migrations/20240105120607_add_and_link_applicantid/migration.sql
- packages/applications-service-api/prisma/schema.prisma
- packages/applications-service-api/prisma/seed.js
- packages/applications-service-api/prisma/utils.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-2163
Add `applicantId` to the `Project` table and link it to the `serviceUser` table using the `serviceUserId`. The PR also refactors the seeding script to make it more readable.
> feat: added applicantId to project table

- packages/forms-web-app/src/pages/index/view.njk
https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?selectedIssue=ASB-2165)
Added "govuk-link" class to projects link.
> style(web/applications): add class to projects link

- packages/applications-service-api/src/repositories/document.backoffice.repository.js
- packages/applications-service-api/src/repositories/document.ni.repository.js
500 being returned for relevant rep details which don't have attachments, others work as expected. Added null check to not call repository.
> fix: added null check value in get documents for rep endpoint

- packages/applications-service-api/__tests__/__data__/application.js
- packages/applications-service-api/__tests__/integration/applications.test.js
- packages/applications-service-api/__tests__/unit/controllers/applications.v2.test.js
- packages/applications-service-api/__tests__/unit/repositories/project.repository.test.js
- packages/applications-service-api/__tests__/unit/utils/application.mapper.test.js
- packages/applications-service-api/prisma/seed.js
- packages/applications-service-api/prisma/utils.js
- packages/applications-service-api/src/controllers/applications.v2.js
- packages/applications-service-api/src/repositories/project.repository.js
- packages/applications-service-api/src/utils/application.mapper.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-2164
Updates the `GET [/api/v1/applications/{caseReference}` for back office integration to show user details from service user table.
> feat: extend application endpoint with service user details

- packages/applications-service-api/src/utils/document.mapper.js
- packages/forms-web-app/src/pages/projects/documents/_utils/filters/convertFiltersToPageView.js
https://pins-ds.atlassian.net/browse/ASB-2150?atlOrigin=eyJpIjoiODNlYWUwOTU5ZjgzNGVmNmIyOTQ3ZmI1Njk3NWMxZTIiLCJwIjoiaiJ9
> Fix: ASB-2150: Document filter showing as 'undefined'

- packages/back-office-subscribers/nsip-exam-timetable/__tests__/index.test.js
- packages/back-office-subscribers/nsip-exam-timetable/index.js
https://pins-ds.atlassian.net/browse/ASB-2214
Update subscriber function following a change in the field name in the message schema.
BO now send eventLineItem.description instead of eventLineItem.eventLineItemDescription
> fix(nsip-exam-timetable/index.js): update subscriber to handle field name change

- packages/back-office-subscribers/lib/queries.js
- packages/back-office-subscribers/nsip-project/__tests__/index.test.js
- packages/back-office-subscribers/nsip-project/index.js
- packages/back-office-subscribers/nsip-representation/__tests__/index.test.js
- packages/back-office-subscribers/nsip-representation/index.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-2172
This PR updates the project consumer function to add applicantId. A placeholder service user is created first which is then linked to the created project.
2. Run azurite `npx azurite` and this function `npm run start:dev nsip-project`
3. Make a POST request to `http://localhost:7071/admin/functions/nsip-project` with this body:
```
{
"input": "{\"caseId\":1,\"caseReference\":\"ABC\",\"projectName\":\"some case\",\"projectDescription\":\"some desc\",\"publishStatus\":\"published\",\"sourceSystem\":\"ODT\",\"applicantId\":\"mock-applicant-id\",\"nsipOfficerIds\":[],\"nsipAdministrationOfficerIds\":[],\"inspectorIds\":[],\"interestedPartyIds\":[],\"regions\":[\"a\",\ …
```
> feat: project consumer updated with applicantId

- packages/applications-service-api/__tests__/__data__/interestedParty.js
- packages/applications-service-api/src/utils/interestedParty.mapper.js
Populate new fields to be sent to BO
representationFrom
contactMethod
These are required by BO for reps sent from FO.
https://pins-ds.atlassian.net/browse/ASB-2242
End 2 end test required to validate these appear in BO.
> fix(interestedparty.js): populate fields for contactMethod and representationFrom

- packages/applications-service-api/__tests__/__data__/advice.js
- packages/applications-service-api/api/openapi.yaml
- packages/applications-service-api/src/utils/advice.mapper.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-2196
Adds title field to S51 advice both endpoints
> feat: added title to s51 advice api

- packages/forms-web-app/src/pages/examination/have-your-say/controller.js
- packages/forms-web-app/src/pages/examination/have-your-say/controller.unit.test.js
- packages/forms-web-app/src/pages/examination/have-your-say/utils/setup/setup-examination-journey.component.test.js
- packages/forms-web-app/src/pages/examination/have-your-say/utils/setup/setup-has-come-direct.js
- packages/forms-web-app/src/pages/projects/_middleware/_utils/get-vertical-tabs.js
- packages/forms-web-app/src/pages/projects/_middleware/_utils/get-vertical-tabs.test.js
- packages/forms-web-app/src/pages/projects/_middleware/middleware.component.test.js
- packages/forms-web-app/src/pages/projects/_middleware/middleware.js
- packages/forms-web-app/src/pages/projects/examination-timetable/_session/timetables.js
- packages/forms-web-app/src/pages/projects/examination-timetable/_utils/events/events-view-model.js
- packages/forms-web-app/src/pages/projects/examination-timetable/_utils/events/get-events.component.test.js
- packages/forms-web-app/src/pages/projects/examination-timetable/_utils/events/get-events.js
- packages/forms-web-app/src/pages/projects/examination-timetable/controller.test.js
- packages/forms-web-app/src/pages/projects/examination-timetable/view.njk
- packages/forms-web-app/src/utils/timetables/get-timetables-state.js
- packages/forms-web-app/src/utils/timetables/get-timetables-state.unit.test.js
https://pins-ds.atlassian.net/browse/ASB-2161?atlOrigin=eyJpIjoiOGE2ZTM1YzRlZmVmNDVmYmI3YzMxODBhYWUzYzJhY2IiLCJwIjoiaiJ9
> ASB-2161 - Reduce Exam timetable API calls from middleware

- packages/forms-web-app/src/pages/examination/evidence-or-comment/utils/get-page-data.test.js
- packages/forms-web-app/src/routes/config.js
https://pins-ds.atlassian.net/browse/ASB-2239?atlOrigin=eyJpIjoiOTFiMDM0M2FlMGNjNDFiOTlkMGQxZDhkNjQ3OGE2NjQiLCJwIjoiaiJ9
> ASB-2239: Have your say journey - Content update

- packages/forms-web-app/src/pages/projects/_utils/get-application-data.js
https://pins-ds.atlassian.net/browse/ASB-2249?atlOrigin=eyJpIjoiZjY2MzQ5MGRhNjI2NDE0MWFkOGI1YWU2OTlmNTNkZmQiLCJwIjoiaiJ9
> Fix: ASB-2249 - Problem displaying Projects in withdrawn stage

- packages/forms-web-app/src/pages/project-search/utils/filters/get-filters-view-model.js
Bug fix, application breaks when we don't have a region filter returned - PR adds a null check. 
Error on pipeline:
```
{"level":50,"time":1707322209963,"pid":23,"hostname":"f4ee0b06bc49","err":{"type":"TypeError","message":"Cannot read properties of undefined (reading 'items')","stack":"TypeError: Cannot read properties of undefined (reading 'items')\n at getFiltersViewModel (/opt/app/packages/forms-web-app/dist/pages/project-search/utils/filters/get-filters-view-model.js:85:85)\n at getFilters (/opt/app/packages/forms-web-app/dist/pages/project-search/utils/filters/get-filters.js:7:27)\n at getPageData (/opt/app/packages/forms-web-app/dist/pages/project-search/utils/get-page-data.js:13:5)\n at getProjectSearchController (/opt/app/packages/forms-web-app/dist/pages/project-search/controlle …
```
> fix: null check for getFiltersViewModel function

- packages/forms-web-app/src/pages/projects/index/_includes/stages/withdrawn/description.njk
https://pins-ds.atlassian.net/browse/ASB-2081?atlOrigin=eyJpIjoiNTZlNzY5OTE0ZGQ5NDEwY2ExM2EzYWNlNTBkNjU5OTUiLCJwIjoiaiJ9
> Fix: ASB-2081 - Project stage withdrawn content amend

- packages/applications-service-api/__tests__/unit/routes/index.test.js
- packages/applications-service-api/api/openapi.yaml
- packages/applications-service-api/src/routes/index.js
Task: https://pins-ds.atlassian.net/browse/ASB-2231
Add 204 to api root
> feat: add 204 response to api root path

- packages/forms-web-app/src/pages/projects/index/_includes/stages/pre-examination/description.njk
https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?selectedIssue=ASB-2265 
Changed size of have your say link text for pre-examination stage projects.
> fix: change font size for have your say link

- packages/applications-service-api/__tests__/__data__/documents.js
- packages/applications-service-api/__tests__/unit/utils/document.mapper.test.js
- packages/applications-service-api/src/utils/document.mapper.js
https://pins-ds.atlassian.net/browse/ASB-2266?atlOrigin=eyJpIjoiNjAyZDk3NWZlNTQ0NGRkOWJmYjFkN2EwNzNhMWM0MjkiLCJwIjoiaiJ9
> Fix: ASB-2266 - E2E Testing - Document Links broken

- docker-compose.yml
- packages/applications-service-api/__tests__/integration/applications.test.js
- packages/applications-service-api/__tests__/unit/controllers/applications.v2.test.js
- packages/applications-service-api/__tests__/unit/controllers/project-updates.test.js
- packages/applications-service-api/__tests__/unit/controllers/subscriptions.test.js
- packages/applications-service-api/__tests__/unit/services/application.backoffice.service.test.js
- packages/applications-service-api/__tests__/unit/services/application.merge.service.test.js
- packages/applications-service-api/__tests__/unit/services/interestedParty.service.test.js
- packages/applications-service-api/__tests__/unit/services/submission.service.test.js
- packages/applications-service-api/api/openapi.yaml
- packages/applications-service-api/src/controllers/applications.js
- packages/applications-service-api/src/controllers/applications.v2.js
- packages/applications-service-api/src/controllers/subscriptions.js
- packages/applications-service-api/src/lib/config.js
- packages/applications-service-api/src/services/application.backoffice.service.js
- packages/applications-service-api/src/services/application.merge.service.js
- packages/applications-service-api/src/services/application.ni.service.js
- packages/applications-service-api/src/services/interestedParty.service.js
- packages/applications-service-api/src/services/submission.service.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-2281
Ticket uses `BACK_OFFICE_INTEGRATION_GET_APPLICATIONS` as enum to show either NI, BO or MERGE projects. MERGE projects prioritises BO cases when one exists in both sources.  Filtering and search works as expected but MERGED sort will be implemented in the next ticket.
> feat: merge applications for project search using ff

- packages/back-office-subscribers/nsip-document/__tests__/index.test.js
- packages/back-office-subscribers/nsip-document/index.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-2315
> fix: updated stage property to documentCaseStage consumer func

- packages/applications-service-api/__tests__/integration/applications.test.js
- packages/applications-service-api/__tests__/unit/repositories/project.backoffice.repository.test.js
- packages/applications-service-api/__tests__/unit/repositories/project.ni.repository.test.js
- packages/applications-service-api/src/repositories/project.backoffice.repository.js
- packages/applications-service-api/src/repositories/project.ni.repository.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-2292
PR adds filters to NI and BO repository to remove all wales cases
> feat: restrict wales projects from ni + bo repository

- packages/applications-service-api/__tests__/integration/interestedParty.test.js
- packages/applications-service-api/__tests__/unit/utils/interestedParty.mapper.test.js
- packages/applications-service-api/src/utils/interestedParty.mapper.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-2299
PR changes the interested party number to be shortened, using a uuid chopped to 8 digits and prefixed by "F".
> feat: shorten generated interested party no

- packages/forms-web-app/src/config.js
- packages/forms-web-app/src/pages/detailed-information/view.njk
- packages/forms-web-app/src/pages/index/_includes/professional-users.njk
- packages/forms-web-app/src/pages/index/view.njk
https://pins-ds.atlassian.net/browse/ASB-2298?atlOrigin=eyJpIjoiMjY3NzRiNGI0YWZjNDBhZDliODlhYTNmMjIyOTgwNDgiLCJwIjoiaiJ9
> Feature: ASB-2100 - Add homepage components

- packages/forms-web-app/src/config.js
- packages/forms-web-app/src/pages/index/view.njk
- packages/forms-web-app/src/pages/project-search/view.njk
- packages/forms-web-app/src/pages/projects/index/_includes/stages/post-decision/description.njk
https://pins-ds.atlassian.net/browse/ASB-2316?atlOrigin=eyJpIjoiZmYzOTBhMTg0OGFhNGQyYWE4YzM3ZWE0NTk5ZWQ4ZDEiLCJwIjoiaiJ9
> ASB-2316: Homepage & project search - content update

- packages/applications-service-api/__tests__/integration/applications.test.js
- packages/applications-service-api/__tests__/unit/services/application.merge.service.test.js
- packages/applications-service-api/__tests__/unit/utils/sort-applications.merge.test.js
- packages/applications-service-api/src/services/application.merge.service.js
- packages/applications-service-api/src/utils/sort-applications.merge.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-2282
PR adds API level sort for merged (BO + NI) projects. Sorting is done on API level after merged and mapped. Like other merged functionality, it is temporarily and will be removed after we have migrated all cases to BO.
> feat: project api sort for merged applications

- e2e-tests/cypress/support/common-methods/assertUserOnThePage.js
- init/wp_ipc_projects.sql
Fix tests run before release:
1) Project information page content update for lowercase "information"
2) Filter on Welsh cases not displaying key project St James Barton causing failures.
- [] I have referenced the ticket number above
> test(e2e-tests): fix end to end tests

- packages/forms-web-app/src/pages/projects/index/_includes/stages/examination/description.njk
2328: https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?selectedIssue=ASB-2328
Make Rule 8 paragraph dynamic
> feat: 2328 make rule 8 paragraph dynamic

- packages/forms-web-app/src/pages/register-of-advice/index/view.njk
https://pins-ds.atlassian.net/browse/ASB-2297?atlOrigin=eyJpIjoiZGE2MmM3OGZmOWZjNDZiMWE1NDE2ODUzMmQxZDFiNGUiLCJwIjoiaiJ9
> Fix: ASB-2297 - Register of advice no results found

- package-lock.json
Ticket: https://pins-ds.atlassian.net/browse/ASB-2302
PR combines the dependabot dependancy updates in root `package-lock.json`: 
- https://github.com/Planning-Inspectorate/applications-service/pull/1011 
- https://github.com/Planning-Inspectorate/applications-service/pull/1010
I've ran `./e2e-tests` after pulling these changes, removing + reinstalling node_modules, and then rebuilding containers - everything is passing as expected:
Note: 
- Combining the changes in one PR will allow for all the changes in this package to be validated at once and dependabot should automatically recognise this and remove the alerts for these dependancies. 
- Dependabot commits were too long and failed commit lint checks so I've squashed it for the PR and listed the individual PRs above.
> chore: dependabot combined updates 

- packages/forms-web-app/src/pages/projects/register/_common/complete/controller.js
- packages/forms-web-app/src/pages/projects/register/_common/complete/controller.test.js
- packages/forms-web-app/src/pages/projects/register/_common/complete/view.njk
2311: https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?selectedIssue=ASB-2311
Update the project link on the register to have your say confirmation page.
> feat: update register to have your say project link

- packages/applications-service-api/__tests__/unit/repositories/document.backoffice.repository.test.js
- packages/applications-service-api/src/repositories/document.backoffice.repository.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-2353
This is in addition to https://github.com/Planning-Inspectorate/applications-service/pull/1075 which updated another function (which was also good to do) but this is the main one required.
> fix: document sorting by datePublished 

- packages/forms-web-app/src/pages/process-guide/_utils/get-process-guide-stages.test.js
- packages/forms-web-app/src/pages/process-guide/_utils/get-process-guide-steps.test.js
- packages/forms-web-app/src/pages/process-guide/examination/view.njk
- packages/forms-web-app/src/pages/process-guide/pre-application/view.njk
- packages/forms-web-app/src/pages/process-guide/pre-examination/config.js
- packages/forms-web-app/src/pages/process-guide/pre-examination/config.test.js
- packages/forms-web-app/src/pages/projects/index/controller.test.js
https://pins-ds.atlassian.net/browse/ASB-2254?atlOrigin=eyJpIjoiYWZjM2U0ZWQxNzA2NDk5YjkwN2VmODk3YzRjNjk0ZTAiLCJwIjoiaiJ9
> ASB-2254 - Content audit

- packages/forms-web-app/src/config.js
- packages/forms-web-app/src/pages/detailed-information/view.njk
https://pins-ds.atlassian.net/browse/ASB-2100?atlOrigin=eyJpIjoiNTk1MjA3MDk5M2E2NDUxYmE1YjI2NThjYmZlNDg0NDEiLCJwIjoiaiJ9
> Fix: ASB-2100 - Correct Gov UK URLs

- azure-pipelines-e2e-test.yml
- packages/e2e_tests/install-chromium.sh
- packages/e2e_tests/run-tests.sh
https://pins-ds.atlassian.net/browse/ASB-1143
Changes to add a pipeline to run the e2e tests from the packages directory.
Once setup the pipeline will have an option to run against dev or test environments.
Initially setup to trigger only on e2e test PR merges to main.  This can be changed in the future.
This has been tested by creating a pipeline from the branch.
> feat(e2e-tests): add e2e test pipeline

- package-lock.json
Ticket: https://pins-ds.atlassian.net/browse/ASB-2366
The changes include:
- https://github.com/Planning-Inspectorate/applications-service/pull/1080
- https://github.com/Planning-Inspectorate/applications-service/pull/1074
Changes have been validated locally with e2e tests.
> chore: dependabot updates

- packages/forms-web-app/src/pages/projects/section-51/advice-detail/_includes/page.njk
- packages/forms-web-app/src/pages/projects/section-51/advice-detail/_utils/get-page-view-model.js
- packages/forms-web-app/src/pages/projects/section-51/advice-detail/controller.test.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-2312
> fix(web): formatting of advice detail page

- packages/forms-web-app/src/pages/terms-and-conditions/view.njk
Ticket: https://pins-ds.atlassian.net/browse/ASB-2390
Fix typo
> fix(web): fix typo in terms and conditions page

- packages/back-office-subscribers/nsip-document/__tests__/index.test.js
- packages/back-office-subscribers/nsip-document/index.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-2383
> feat: document bo function to new pattern

- packages/back-office-subscribers/nsip-advice/__tests__/index.test.js
- packages/back-office-subscribers/nsip-advice/index.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-2382
> feat: advice bo function to new pattern

- packages/back-office-subscribers/nsip-exam-timetable/__tests__/index.test.js
- packages/back-office-subscribers/nsip-exam-timetable/index.js
- packages/back-office-subscribers/nsip-project/__tests__/index.test.js
- packages/back-office-subscribers/nsip-project/index.js
Tickets:
- https://pins-ds.atlassian.net/browse/ASB-2384
- https://pins-ds.atlassian.net/browse/ASB-2385
Refactors functions to new pattern for query and error handling.
> feat: exam + project functions updated

- packages/back-office-subscribers/nsip-representation/__tests__/index.test.js
- packages/back-office-subscribers/nsip-representation/index.js
Tickets: https://pins-ds.atlassian.net/browse/ASB-2386
Refactors functions to new pattern for query and error handling.
> feat: update rep bo function

- packages/forms-web-app/src/pages/accessibility-statement/view.njk
https://pins-ds.atlassian.net/browse/ASB-2404?atlOrigin=eyJpIjoiMjUzMzg3Nzc0N2YxNDE1ZGFhNGJkMjQyMjU1NjU3NTciLCJwIjoiaiJ9
> ASB-2404 - Accessibility statement - style update

- packages/forms-web-app/src/config.js
- packages/forms-web-app/src/pages/projects/index/_includes/contact.njk
https://pins-ds.atlassian.net/browse/ASB-2398?atlOrigin=eyJpIjoiNmZkNDg1Y2U1MjE1NGQ0N2I3ZTFhYmE5N2MwMTc4MzkiLCJwIjoiaiJ9
> ASB-2398 - Contact us updates

- packages/applications-service-api/__tests__/unit/utils/map-applications-to-csv.test.js
- packages/applications-service-api/src/utils/application.mapper.js
- packages/applications-service-api/src/utils/map-applications-to-csv.js
https://pins-ds.atlassian.net/browse/ASB-2397?atlOrigin=eyJpIjoiZDk3M2Y0YzQzMGJjNGZiYWIzOGM0NzQ3ZGI5MTVlMjEiLCJwIjoiaiJ9
> Fix: ASB-2397 - Applications download values not correctly formatted

- packages/back-office-subscribers/nsip-project-update/__tests__/index.test.js
- packages/back-office-subscribers/nsip-project-update/index.js
- packages/back-office-subscribers/nsip-service-user/__tests__/index.test.js
- packages/back-office-subscribers/nsip-service-user/index.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-2387
> feat: update project-update func

- packages/back-office-subscribers/nsip-representation-update/__tests__/index.test.js
- packages/back-office-subscribers/nsip-representation-update/index.js
Ticket: https://pins-ds.atlassian.net/browse/ASB-2389
> feat: update rep-update func

- packages/forms-web-app/src/pages/projects/_utils/get-application-data.js
add DateOfReOpenRelevantRepresentationStart and DateOfReOpenRelevantRepresentationClose to projects locals
> feat(web): add re-open register dates to projects locals

- packages/forms-web-app/src/pages/_middleware/i18n/add-common-translations-middleware.js
- packages/forms-web-app/src/pages/_middleware/i18n/add-common-translations-middleware.test.js
- packages/forms-web-app/src/pages/detailed-information/_middleware/add-detailed-information-translations-middleware.js
- packages/forms-web-app/src/pages/detailed-information/_middleware/add-detailed-information-translations-middleware.test.js
- packages/forms-web-app/src/pages/detailed-information/_translations/cy.json
- packages/forms-web-app/src/pages/detailed-information/_translations/cy.test.js
- packages/forms-web-app/src/pages/detailed-information/_translations/en.json
- packages/forms-web-app/src/pages/detailed-information/_translations/en.test.js
- packages/forms-web-app/src/pages/detailed-information/_utils/get-page-data.js
- packages/forms-web-app/src/pages/detailed-information/config.js
- packages/forms-web-app/src/pages/detailed-information/config.test.js
- packages/forms-web-app/src/pages/detailed-information/view.njk
- packages/forms-web-app/src/pages/index/controller.test.js
- packages/forms-web-app/src/pages/index/utils/get-page-data.js
- packages/forms-web-app/src/pages/index/view.njk
- packages/forms-web-app/src/pages/router.js
- packages/forms-web-app/src/pages/router.test.js
https://pins-ds.atlassian.net/browse/ASB-2437?atlOrigin=eyJpIjoiODM4NWIyODcxZmQyNGIwYTg2ZjRhMDNkOGI3MGE0N2IiLCJwIjoiaiJ9
> ASB-2437: Welsh translation - Detailed information

- .gitignore
Add Vim .swp files to the .gitignore
> chore: add Vim .swp files to the .gitignore

- packages/applications-service-api/__tests__/unit/middleware/parseParamProperties.test.js
- packages/applications-service-api/__tests__/unit/repositories/project.backoffice.repository.test.js
- packages/applications-service-api/__tests__/unit/repositories/project.ni.repository.test.js
- packages/applications-service-api/api/openapi.yaml
- packages/applications-service-api/src/middleware/parseParamProperties.js
- packages/applications-service-api/src/repositories/project.backoffice.repository.js
- packages/applications-service-api/src/repositories/project.ni.repository.js
- packages/applications-service-api/src/routes/applications.js
- packages/applications-service-api/src/services/application.merge.service.js
- packages/forms-web-app/src/pages/register-of-applications/utils/get-register-of-applications-query-string.js
- packages/forms-web-app/src/pages/register-of-applications/utils/get-register-of-applications-query-string.unit.test.js
https://pins-ds.atlassian.net/browse/ASB-2405?atlOrigin=eyJpIjoiNjE5NjllMTc5NDRkNGY4Y2FmMmQ2MmEyOGRiNzM0YTkiLCJwIjoiaiJ9
> ASB-2405: Register of advice - discrepancy

- packages/applications-service-api/__tests__/unit/repositories/project.ni.repository.test.js
- packages/applications-service-api/src/repositories/project.ni.repository.js
https://pins-ds.atlassian.net/browse/APPLICS-232?atlOrigin=eyJpIjoiYThlNzVmNmQ0OGZhNDI1ZTk5NzRiYTcyZjgxZWZiZTEiLCJwIjoiaiJ9
> Fix: APPLICS-232 - Register of advice -  discrepancy

- packages/applications-service-api/__tests__/unit/repositories/project.ni.repository.test.js
- packages/applications-service-api/src/repositories/project.ni.repository.js
> Fix: APPLICS-232 - Exclude zero and null dates

- packages/applications-service-api/prisma/migrations/20240513100923_increase_field_lengths/migration.sql
- packages/applications-service-api/prisma/schema.prisma
Ticket: https://pins-ds.atlassian.net/issues/APPLICS-112
Updates the prisma schema to align with [BO schema](https://github.com/Planning-Inspectorate/back-office/blob/main/apps/api/src/database/schema.prisma). This will prevent errors occuring when a message is sent to us via service bus and our functions fail to consume because the field length was too large.
> feat: schema update

- packages/forms-web-app/src/config.js
- packages/forms-web-app/src/locales/cy/common.json
- packages/forms-web-app/src/locales/cy/common.test.js
- packages/forms-web-app/src/locales/en/common.json
- packages/forms-web-app/src/locales/en/common.test.js
- packages/forms-web-app/src/pages/contact/_middleware/add-contact-translations-middleware.js
- packages/forms-web-app/src/pages/contact/_middleware/add-contact-translations-middleware.test.js
- packages/forms-web-app/src/pages/contact/_translations/cy.json
- packages/forms-web-app/src/pages/contact/_translations/cy.test.js
- packages/forms-web-app/src/pages/contact/_translations/en.json
- packages/forms-web-app/src/pages/contact/_translations/en.test.js
- packages/forms-web-app/src/pages/contact/_utils/get-page-data.js
- packages/forms-web-app/src/pages/contact/config.js
- packages/forms-web-app/src/pages/contact/config.test.js
- packages/forms-web-app/src/pages/contact/controller.js
- packages/forms-web-app/src/pages/contact/controller.test.js
- packages/forms-web-app/src/pages/contact/view.njk
- packages/forms-web-app/src/pages/router.js
- packages/forms-web-app/src/pages/router.test.js
https://pins-ds.atlassian.net/browse/APPLICS-83?atlOrigin=eyJpIjoiOGE0ODNiMzg1NDFiNGZlMzhlYWRjMTcyZDEwZjRhN2IiLCJwIjoiaiJ9
> APPLICS-43: Welsh translation - Contact us page

- packages/forms-web-app/src/pages/projects/representations/index/_includes/active-filters.njk
- packages/forms-web-app/src/pages/projects/representations/index/_includes/no-results-post-decision.njk
- packages/forms-web-app/src/pages/projects/representations/index/_includes/no-results-pre-decision.njk
- packages/forms-web-app/src/pages/projects/representations/index/_includes/results-not-found.njk
- packages/forms-web-app/src/pages/projects/representations/index/_includes/results-per-page.njk
- packages/forms-web-app/src/pages/projects/representations/index/_includes/search.njk
- packages/forms-web-app/src/pages/projects/representations/index/_middleware/add-representations-index-translations-middleware.js
- packages/forms-web-app/src/pages/projects/representations/index/_middleware/add-representations-index-translations-middleware.test.js
- packages/forms-web-app/src/pages/projects/representations/index/_translations/cy.json
- packages/forms-web-app/src/pages/projects/representations/index/_translations/cy.test.js
- packages/forms-web-app/src/pages/projects/representations/index/_translations/en.json
- packages/forms-web-app/src/pages/projects/representations/index/_translations/en.test.js
- packages/forms-web-app/src/pages/projects/representations/index/config.js
- packages/forms-web-app/src/pages/projects/representations/index/config.test.js
- packages/forms-web-app/src/pages/projects/representations/index/view.njk
- packages/forms-web-app/src/pages/projects/representations/router.js
- packages/forms-web-app/src/pages/projects/representations/router.test.js
APPLICS 95: https://pins-ds.atlassian.net/jira/software/c/projects/APPLICS/boards/242?selectedIssue=APPLICS-95
Welsh translations for static content on relevant representations page
> feat: add translations for relevant representations page

- packages/forms-web-app/src/pages/process-guide/_translations/en.json
- packages/forms-web-app/src/pages/process-guide/_translations/en.test.js
- packages/forms-web-app/src/pages/process-guide/_utils/get-process-guide-stages.test.js
- packages/forms-web-app/src/pages/process-guide/_utils/get-process-guide-steps.test.js
- packages/forms-web-app/src/pages/process-guide/examination/_translations/cy.json
- packages/forms-web-app/src/pages/process-guide/examination/_translations/cy.test.js
- packages/forms-web-app/src/pages/process-guide/examination/_translations/en.json
- packages/forms-web-app/src/pages/process-guide/examination/_translations/en.test.js
- packages/forms-web-app/src/pages/process-guide/pre-application/_translations/cy.json
- packages/forms-web-app/src/pages/process-guide/pre-application/_translations/cy.test.js
- packages/forms-web-app/src/pages/process-guide/pre-application/_translations/en.json
- packages/forms-web-app/src/pages/process-guide/pre-application/_translations/en.test.js
- packages/forms-web-app/src/pages/projects/index/controller.test.js
> Fix: APPLICS-78 Process Guide Translations

- azure-pipelines-deploy.yml
https://pins-ds.atlassian.net/browse/DEV-93
Add training environment
> ci: add training environment for deployment

- azure-pipelines-deploy.yml
Set the app names correctly for the training environment (which had to be shortened)
> ci: set app names for training env deploy

- packages/forms-web-app/src/i18n.js
Change config for I18n to turn off debug logging.  There is quite a bit of noise in the production logs so best to turn off.
Will be validated once deployed to dev.
- [n/a] I have referenced the ticket number above
> fix(i18n.js): change debug log to false for i18n

- packages/applications-service-api/__tests__/integration/representations.test.js
- packages/applications-service-api/__tests__/unit/repositories/representation.ni.repository.test.js
- packages/applications-service-api/src/repositories/representation.ni.repository.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-471
PR splits the search terms into words and then uses in NI query to get better search results.
> feat: ni reps search terms improvement

- azure-pipelines-build.yml
- package.json
https://pins-ds.atlassian.net/browse/APPLICS-482
> fix(tooling): fix commit linting

- packages/forms-web-app/src/locales/cy/common.json
- packages/forms-web-app/src/locales/cy/common.test.js
- packages/forms-web-app/src/locales/en/common.json
- packages/forms-web-app/src/locales/en/common.test.js
- packages/forms-web-app/src/pages/projects/section-51/index/_middleware/add-section-51-index-translations-middleware.js
- packages/forms-web-app/src/pages/projects/section-51/index/_middleware/add-section-51-index-translations-middleware.test.js
- packages/forms-web-app/src/pages/projects/section-51/index/_translations/cy.json
- packages/forms-web-app/src/pages/projects/section-51/index/_translations/cy.test.js
- packages/forms-web-app/src/pages/projects/section-51/index/_translations/en.json
- packages/forms-web-app/src/pages/projects/section-51/index/_translations/en.test.js
- packages/forms-web-app/src/pages/projects/section-51/index/_utils/advice-helpers.js
- packages/forms-web-app/src/pages/projects/section-51/index/config.js
- packages/forms-web-app/src/pages/projects/section-51/index/controller.js
- packages/forms-web-app/src/pages/projects/section-51/index/controller.test.js
- packages/forms-web-app/src/pages/projects/section-51/index/view.njk
- packages/forms-web-app/src/pages/projects/section-51/router.js
- packages/forms-web-app/src/pages/projects/section-51/router.test.js
[APPLICS 88](https://pins-ds.atlassian.net/jira/software/c/projects/APPLICS/boards/242?selectedIssue=APPLICS-88): 
- Add Welsh translations for section 51 static content
- Update conditional logic with language parameters so correct content continues to be displayed once a language is selected
> feat: add translations for section 51 static content

- packages/forms-web-app/src/pages/projects/section-51/index/_utils/advice-helpers.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-444
Advice title was being generated even if it was existed, this change checks if it exists before generating a new one.
> fix: advice title

- packages/applications-service-api/src/utils/sort-applications.merge.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-529
> fix: applications stage sort

- packages/applications-service-api/__tests__/__data__/timetables.js
- packages/applications-service-api/__tests__/unit/utils/timetable.mapper.test.js
- packages/applications-service-api/api/openapi.yaml
- packages/applications-service-api/prisma/migrations/20240621124915_add_welsh_timetable_fields/migration.sql
- packages/applications-service-api/prisma/schema.prisma
- packages/applications-service-api/src/utils/timetable.mapper.js
- packages/back-office-subscribers/nsip-exam-timetable/__tests__/index.test.js
- packages/back-office-subscribers/nsip-exam-timetable/index.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-189
PR adds welsh title and description fields to prisma schema, consumer functions and API.
> feat: timetable api welsh fields

- packages/forms-web-app/src/pages/projects/_middleware/_utils/get-vertical-tabs.js
- packages/forms-web-app/src/pages/projects/_middleware/_utils/get-vertical-tabs.test.js
- packages/forms-web-app/src/pages/projects/_middleware/add-projects-translations-middleware.js
- packages/forms-web-app/src/pages/projects/_middleware/add-projects-translations-middleware.test.js
- packages/forms-web-app/src/pages/projects/_middleware/middleware.component.test.js
- packages/forms-web-app/src/pages/projects/_middleware/middleware.js
- packages/forms-web-app/src/pages/projects/_translations/cy.json
- packages/forms-web-app/src/pages/projects/_translations/cy.test.js
- packages/forms-web-app/src/pages/projects/_translations/en.json
- packages/forms-web-app/src/pages/projects/_translations/en.test.js
- packages/forms-web-app/src/pages/projects/config.js
- packages/forms-web-app/src/pages/projects/config.test.js
- packages/forms-web-app/src/pages/projects/router.js
- packages/forms-web-app/src/pages/projects/router.test.js
https://pins-ds.atlassian.net/browse/APPLICS-205?atlOrigin=eyJpIjoiOTE1NDBmMWFmMDY4NGFmZGFhNWI4YmEwMjllMTczNTEiLCJwIjoiaiJ9
> Feature: APPLICS-205 - Welsh translation - project left hand nav bar

- package-lock.json
- packages/applications-service-api/package.json
- packages/applications-service-api/src/models/index.js
> fix: move sequelize-mock from dev to normal dep

- packages/forms-web-app/src/pages/projects/index/_includes/stages/recommendation/details.njk
https://pins-ds.atlassian.net/browse/APPLICS-554
> fix(web): fix recommendation stage tag

- packages/forms-web-app/src/pages/projects/examination-timetable/_utils/events/event/event-view-model.js
- packages/forms-web-app/src/pages/projects/examination-timetable/_utils/events/event/get-event.component.test.js
https://pins-ds.atlassian.net/browse/APPLICS-195
> feat(web): use welsh dynamic data on examination timetable

- packages/applications-service-api/__tests__/__data__/representation.js
- packages/applications-service-api/src/repositories/representation.backoffice.repository.js
- packages/applications-service-api/src/utils/representation.mapper.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-324
> feat: rep welsh api changes

- packages/forms-web-app/src/pages/projects/section-51/_translations/cy.json
- packages/forms-web-app/src/pages/projects/section-51/_translations/cy.test.js
- packages/forms-web-app/src/pages/projects/section-51/advice-detail/controller.test.js
- packages/forms-web-app/src/pages/projects/section-51/index/_utils/get-advice-view-model.test.js
Welsh translation - S51 page - dynamic content remedial fix
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-194
- Update translations with those now received in the ticket
> feat: welsh translation - S51 page - dynamic content remedial fix (APPLICS-194)

- packages/applications-service-api/__tests__/unit/repositories/advice.backoffice.repository.test.js
- packages/applications-service-api/__tests__/unit/repositories/advice.ni.repository.test.js
- packages/applications-service-api/__tests__/unit/utils/queries.test.js
- packages/applications-service-api/src/repositories/advice.backoffice.repository.js
- packages/applications-service-api/src/repositories/advice.ni.repository.js
- packages/applications-service-api/src/repositories/representation.ni.repository.js
- packages/applications-service-api/src/utils/queries.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-477
PR change search term queries to first split by words to get a more range of results. The advice repositories are updated to follow this pattern but common utils are made for BO and NI to be reused for other entities.
> feat: advice search term split search

- packages/forms-web-app/src/pages/_utils/map-applications.js
- packages/forms-web-app/src/pages/_utils/map-applications.unit.test.js
- packages/forms-web-app/src/pages/project-search/controller.test.js
- packages/forms-web-app/src/pages/register-of-applications/_middleware/add-register-of-applications-translations-middleware.js
- packages/forms-web-app/src/pages/register-of-applications/_middleware/add-register-of-applications-translations-middleware.test.js
- packages/forms-web-app/src/pages/register-of-applications/_translations/cy.json
- packages/forms-web-app/src/pages/register-of-applications/_translations/cy.test.js
- packages/forms-web-app/src/pages/register-of-applications/_translations/en.json
- packages/forms-web-app/src/pages/register-of-applications/_translations/en.test.js
- packages/forms-web-app/src/pages/register-of-applications/_translations/translations.test.js
- packages/forms-web-app/src/pages/register-of-applications/config.js
- packages/forms-web-app/src/pages/register-of-applications/controller.test.js
- packages/forms-web-app/src/pages/register-of-applications/includes/results-per-page.njk
- packages/forms-web-app/src/pages/register-of-applications/includes/search.njk
- packages/forms-web-app/src/pages/register-of-applications/utils/get-page-data.js
- packages/forms-web-app/src/pages/register-of-applications/utils/get-register-of-applications-sort-by-links.js
- packages/forms-web-app/src/pages/register-of-applications/utils/get-register-of-applications-sort-by-links.unit.test.js
- packages/forms-web-app/src/pages/register-of-applications/view.njk
- packages/forms-web-app/src/pages/router.js
- packages/forms-web-app/src/pages/router.test.js
- packages/forms-web-app/src/utils/date-utils.js
https://pins-ds.atlassian.net/browse/APPLICS-92?atlOrigin=eyJpIjoiYTdhOWQyNDlkNTVkNDdkNTg0NTFmMTQxZjU4MzU1NGEiLCJwIjoiaiJ9
> feat: add register of applications translations

- packages/forms-web-app/src/pages/projects/get-updates/how-often/controller.test.js
[APPLICS 203](https://pins-ds.atlassian.net/jira/software/c/projects/APPLICS/boards/242?selectedIssue=APPLICS-203)
Removed console log from getUpdatesHowOftenController test.
> fix: remove console log from get updates controller test

- packages/forms-web-app/src/pages/project-search/view.njk
[APPLICS 622](https://pins-ds.atlassian.net/jira/software/c/projects/APPLICS/boards/238?selectedIssue=APPLICS-622): Project search shows pagination for MERGE data source
> fix: remove pagination from project search page

- packages/applications-service-api/__tests__/unit/repositories/document.backoffice.repository.test.js
- packages/applications-service-api/__tests__/unit/repositories/document.ni.repository.test.js
- packages/applications-service-api/src/repositories/document.backoffice.repository.js
- packages/applications-service-api/src/repositories/document.ni.repository.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-476
Splits the search term up and searches for each word separately.
> feat: tech debt - api document search term split (APPLICS-476)

- packages/forms-web-app/src/pages/_utils/map-applications.unit.test.js
- packages/forms-web-app/src/pages/project-search/controller.test.js
- packages/forms-web-app/src/pages/register-of-applications/controller.test.js
- packages/forms-web-app/src/utils/project-stages.js
- packages/forms-web-app/src/utils/project-stages.test.js
[APPLICS 594](https://pins-ds.atlassian.net/browse/APPLICS-594): Amend acceptance stage description
> feat: amend acceptance stage description

- packages/applications-service-api/__tests__/unit/utils/map-applications-to-csv.test.js
- packages/applications-service-api/api/openapi.yaml
- packages/applications-service-api/src/utils/map-applications-to-csv.js
Ticket: [APPLICS-490: All projects download file (csv) includes internal field]( https://pins-ds.atlassian.net/browse/APPLICS-490)
- Removed "Anticipated submission date" column from "All projects download (csv) file"
- Updated unit test and snapshot to match
> fix: all projects download file (csv) includes internal field (APPLICS-490)

- e2e-tests/package-lock.json
- package-lock.json
- packages/applications-service-api/package.json
- packages/back-office-subscribers/package-lock.json
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-562
PR adds updates from the following:
Also created guide for handling these updates; https://pins-ds.atlassian.net/wiki/spaces/AS2/pages/1660321808/Dependabot+Updates
> chore: all dependabot commits

- packages/forms-web-app/src/lib/application-api-wrapper.js
- packages/forms-web-app/src/pages/examination/process-submission/utils/process.js
- packages/forms-web-app/src/pages/examination/process-submission/utils/process.test.js
- packages/forms-web-app/src/services/submission.service.js
Adding caseReference and email to API call to complete submission - these are required so API can determine if case if NI or BO.
https://pins-ds.atlassian.net.mcas.ms/jira/software/c/projects/APPLICS/boards/242?selectedIssue=APPLICS-757
- [x I have provided a description of the ticket
> fix: add req body details to complete submission API call

- packages/forms-web-app/src/pages/projects/documents/_utils/documents/documents-view-model.js
- packages/forms-web-app/src/views/components/section/results.njk
[APPLICS 722](https://pins-ds.atlassian.net/jira/software/c/projects/APPLICS/boards/238?selectedIssue=APPLICS-722):  Documents page not showing the From details on C-BOS cases
- Added author and author_welsh keys to the object passed into the view.
- Updated the conditional logic in the template to include these variables.
> fix: handle document author values for CBOS cases

- packages/forms-web-app/src/lib/application-api-wrapper.js
- packages/forms-web-app/src/pages/examination/process-submission/utils/process.js
- packages/forms-web-app/src/pages/examination/process-submission/utils/process.test.js
- packages/forms-web-app/src/pages/projects/documents/_utils/documents/documents-view-model.js
- packages/forms-web-app/src/pages/projects/section-51/_translations/cy.json
- packages/forms-web-app/src/pages/projects/section-51/_translations/cy.test.js
- packages/forms-web-app/src/pages/projects/section-51/_translations/en.json
- packages/forms-web-app/src/pages/projects/section-51/_translations/en.test.js
- packages/forms-web-app/src/pages/projects/section-51/_translations/translations.test.js
- packages/forms-web-app/src/pages/projects/section-51/advice-detail/_includes/page.njk
- packages/forms-web-app/src/pages/projects/section-51/advice-detail/_utils/get-attachments.js
- packages/forms-web-app/src/pages/projects/section-51/advice-detail/_utils/get-breadcrumbs-items.js
- packages/forms-web-app/src/pages/projects/section-51/advice-detail/_utils/get-breadcrumbs-items.test.js
- packages/forms-web-app/src/pages/projects/section-51/advice-detail/_utils/get-enquiry-summary-list.js
- packages/forms-web-app/src/pages/projects/section-51/advice-detail/_utils/get-page-view-model.js
- packages/forms-web-app/src/pages/projects/section-51/advice-detail/controller.test.js
- packages/forms-web-app/src/pages/projects/section-51/index/_translations/cy.json
- packages/forms-web-app/src/pages/projects/section-51/index/_translations/cy.test.js
- packages/forms-web-app/src/pages/projects/section-51/index/_translations/en.json
- packages/forms-web-app/src/pages/projects/section-51/index/_translations/en.test.js
- packages/forms-web-app/src/pages/projects/section-51/index/view.njk
- packages/forms-web-app/src/pages/projects/section-51/router.js
- packages/forms-web-app/src/pages/projects/section-51/router.test.js
- packages/forms-web-app/src/services/submission.service.js
- packages/forms-web-app/src/views/components/section/results.njk
Update to docker-compose.yml to include new file reference
Prior to this change the application service solution build would fail with a "Cannot find module '@pins/common/src/utils/redis'" error when attempting to do a "npm run dev".  Including a reference to the module in docker-compose corrected this error.  The fix has been confirmed by myself and Ben Jacobs.  There is nothing to test on the front end for this fix.  There is no ticket for this issue.
> Added new common volume package to docker-compose to correct build issue on Windows machines

- packages/forms-web-app/src/locales/__snapshots__/common.test.js.snap
- packages/forms-web-app/src/locales/cy/common.json
- packages/forms-web-app/src/pages/examination/_translations/__snapshots__/translations.test.js.snap
- packages/forms-web-app/src/pages/examination/_translations/cy.json
- packages/forms-web-app/src/pages/examination/select-file/view.njk
https://pins-ds.atlassian.net/browse/APPLICS-468?atlOrigin=eyJpIjoiMjcxNzJmOWQzMjhiNDFkNGE3MTZhOTQ1OGU4MDZhZTIiLCJwIjoiaiJ9
> feat: APPLICS-468 - Welsh translation - have your say journey 5/6 - Add missing translations

- packages/e2e_tests/cypress/pageObject/Cookies/PO_Cookies.js
- packages/forms-web-app/src/lib/render-template-filter.js
- packages/forms-web-app/src/pages/cookies/_includes/cookies-updated-successfully-message.njk
- packages/forms-web-app/src/pages/cookies/controller.js
- packages/forms-web-app/src/pages/cookies/controller.test.js
- packages/forms-web-app/src/views/components/flash-message.njk
APPLICS-434 - https://pins-ds.atlassian.net/browse/APPLICS-434
This will require anyone developing locally to re-run the build prior to running the containers in docker.
- Refactored the flash-message component so that the translations can occur within the template as well as the controller
- Amended the unit tests
- Improved the e2e tests for checking the cookie settings success message
> chore: refactor flash message

- packages/applications-service-api/src/utils/is-backoffice-case-reference.js
[APPLICS-630](https://pins-ds.atlassian.net/browse/APPLICS-630)
Bypass the case references feature flag when in training env
[APPLICS-630]: https://pins-ds.atlassian.net/browse/APPLICS-630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: bypass the case references feature flag when in training env

- packages/e2e_tests/cypress/e2e/examination-timetable-agent-submission.cy.js
- packages/e2e_tests/cypress/e2e/examination-timetable-myself-submission.cy.js
- packages/e2e_tests/cypress/e2e/filter-and-search-project-documents.cy.js
- packages/e2e_tests/cypress/e2e/filter-and-search-relevant-reps.cy.js
- packages/e2e_tests/cypress/e2e/get-updates-sign-up.cy.js
- packages/e2e_tests/cypress/e2e/register-as-an-organisation.cy.js
- packages/e2e_tests/cypress/e2e/registers-as-myself-over18-to-have-my-say.cy.js
- packages/e2e_tests/cypress/e2e/section-51-advice.cy.js
- packages/e2e_tests/cypress/pageObject/Documents/PO_Documents.js
- packages/e2e_tests/cypress/pageObject/Relevant-representations/PO_RelevantReps.js
- packages/e2e_tests/cypress/pageObject/basePage.js
Removed NI data and a refactored a few page objects
https://pins-ds.atlassian.net/browse/APPLICS-852
These changes are to remove the NI projects from the test file, and removed any flaky methods from files changed.
> Test: APPLICS-852-removing-NI-data-and-refactoring-existing-tests

- packages/forms-web-app/src/config.js
- packages/forms-web-app/src/pages/_utils/get-govuk-urls.js
- packages/forms-web-app/src/pages/_utils/get-govuk-urls.test.js
- packages/forms-web-app/src/pages/detailed-information/_utils/get-page-data.js
- packages/forms-web-app/src/pages/detailed-information/controller.js
- packages/forms-web-app/src/pages/detailed-information/view.njk
- packages/forms-web-app/src/pages/index/_includes/professional-users.njk
- packages/forms-web-app/src/pages/index/controller.js
- packages/forms-web-app/src/pages/index/controller.test.js
- packages/forms-web-app/src/pages/index/utils/get-page-data.js
* update URLS to English gov.uk pages
* add URLS to Welsh gov.uk pages
* update links on detailed information and homepage to use correct URLs for locale
https://pins-ds.atlassian.net.mcas.ms/jira/software/c/projects/APPLICS/boards/242?selectedIssue=APPLICS-817
> feat: update and add URLs for detailed information

- packages/forms-web-app/src/pages/project-search/_translations/__snapshots__/translations.test.js.snap
- packages/forms-web-app/src/pages/project-search/_translations/cy.json
- packages/forms-web-app/src/pages/project-search/_translations/en.json
- packages/forms-web-app/src/pages/project-search/includes/sidebar.njk
- packages/forms-web-app/src/pages/project-search/utils/get-page-data.js
- packages/forms-web-app/src/pages/project-search/utils/get-related-content-links.js
- packages/forms-web-app/src/pages/project-search/utils/get-related-content-links.test.js
* add translations for the "Related content" sidebar on the project search page
https://pins-ds.atlassian.net.mcas.ms/jira/software/c/projects/APPLICS/boards/242?selectedIssue=APPLICS-835
> feat: add sidebar related content translations

- packages/forms-web-app/src/pages/projects/_components/project-pages-template.njk
- packages/forms-web-app/src/pages/projects/_components/vertical-tabs-wrapper.njk
- packages/forms-web-app/src/pages/projects/_utils/get-application-data.js
- packages/forms-web-app/src/pages/projects/_utils/get-application-data.test.js
- packages/forms-web-app/src/pages/projects/documents/view.njk
- packages/forms-web-app/src/pages/projects/get-updates/index/view.njk
- packages/forms-web-app/src/pages/projects/index/view.njk
- packages/forms-web-app/src/pages/projects/representations/index/view.njk
- packages/forms-web-app/src/pages/projects/representations/representation/view.njk
- packages/forms-web-app/src/pages/projects/section-51/index/view.njk
- packages/forms-web-app/src/views/components/wrappers/related-guides-wrapper.njk
* remove NSIP link and project stages components if project is material changes
https://pins-ds.atlassian.net.mcas.ms/jira/software/c/projects/APPLICS/boards/242?selectedIssue=APPLICS-770
> feat: remove components if material changes

- packages/applications-service-api/__tests__/integration/applications.test.js
- packages/applications-service-api/__tests__/unit/repositories/project.backoffice.repository.test.js
- packages/applications-service-api/src/repositories/project.backoffice.repository.js
* remove filter preventing return of Wales region BO projects
https://pins-ds.atlassian.net.mcas.ms/jira/software/c/projects/APPLICS/boards/242?selectedIssue=APPLICS-761
> feat: remove Welsh project filter

- packages/applications-service-api/src/utils/timetable.mapper.js
https://pins-ds.atlassian.net/browse/APPLICS-875?atlOrigin=eyJpIjoiNzJkNDA4ZGE1M2VjNDg3NThlOGRkNzQ2MzZmNzYzMWUiLCJwIjoiaiJ9
> fix: APPLICS-875 - Allow desc to be created when timetable desc is not present

- azure-pipelines-deploy.yml
[APPLICS-602](https://pins-ds.atlassian.net.mcas.ms/browse/APPLICS-602?McasTsid=20596&McasCtx=4)
Change release pipeline config to allow deploying from a git tag
[APPLICS-602]: https://pins-ds.atlassian.net/browse/APPLICS-602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci: change release pipeline config to allow deploying from a git tag

- packages/applications-service-api/__tests__/integration/advice.test.js
- packages/applications-service-api/__tests__/integration/representations.test.js
- packages/applications-service-api/src/middleware/apiErrorHandler.js
https://pins-ds.atlassian.net/browse/APPLICS-294?atlOrigin=eyJpIjoiZDc1MDRiNjRhMGYzNGUwZTllNjI3ZTU0ZjU4ZDA1ZTUiLCJwIjoiaiJ9
> refactor: APPLICS-294 - Make API 500 error response consistent with other errors

- packages/forms-web-app/src/pages/projects/representations/index/_includes/pagination.njk
Added a "with context" to the pagination.njk for representations.  This corrects a bug which was causing the representation page to fail with a translation error
[https://applications-service-test.planninginspectorate.gov.uk/projects/BC0910150/representations](https://applications-service-test.planninginspectorate.gov.uk/projects/BC0910150/representations)
> fix: added with context to the representations pagination template to fix bug

- packages/applications-service-api/__tests__/integration/timetable.test.js
- packages/applications-service-api/src/controllers/timetables.js
APPLICS-829- https://pins-ds.atlassian.net/browse/APPLICS-829
- Sanitize the caseRef received within the URL
- Added unit test for above
> chore: prevent case reference cross site scripting (APPLICS-829)

- packages/e2e_tests/cypress/e2e/examination-timetable-agent-submission.cy.js
- packages/e2e_tests/cypress/e2e/examination-timetable-myself-submission.cy.js
- packages/e2e_tests/cypress/e2e/examinaton-timetable-organisation-submission.cy.js
- packages/e2e_tests/cypress/e2e/project-information.cy.js
- packages/e2e_tests/cypress/e2e/section-51-advice.cy.js
- packages/e2e_tests/cypress/pageObject/Examination-TimeTable/PO_ExaminationTimetable.js
- packages/e2e_tests/cypress/pageObject/basePage.js
- packages/e2e_tests/cypress/pageObject/section-51-advice/PO_Section51.js
Refactor of tests on examination timetable, along with updates to the project information page.
https://pins-ds.atlassian.net/browse/APPLICS-355
https://pins-ds.atlassian.net/browse/APPLICS-864
> Test: APPLICS-365-project-information-e2e-tests

- packages/forms-web-app/__tests__/setupTests.js
- packages/forms-web-app/src/pages/_translations/components/checkbox-accordion/__snapshots__/translations.test.js.snap
- packages/forms-web-app/src/pages/_translations/components/checkbox-accordion/translations.test.js
https://pins-ds.atlassian.net/browse/APPLICS-603?atlOrigin=eyJpIjoiMDc0ZWE3OTMyYTUxNGYzMTg2NjA2NmEzMGQwMDEyMGEiLCJwIjoiaiJ9
> test: update test to clear obj values and compare

- package-lock.json
- packages/applications-service-api/package.json
Update @planning-inspectorate/pins-notify package to use latest version
https://pins-ds.atlassian.net.mcas.ms/jira/software/c/projects/APPLICS/boards/242?selectedIssue=APPLICS-295
> feat: update notify package version

- packages/applications-service-api/src/database/config/config.js
> fix(api): revert sequelize timezone config change

- packages/applications-service-api/prisma/migrations/20240912141822_increase_examination_desc/migration.sql
- packages/applications-service-api/prisma/schema.prisma
APPLICS-959- https://pins-ds.atlassian.net/browse/APPLICS-959
- Update prisma schema for description and descriptionWelsh to @db.NText and generated migration
> fix: timetable description character limit (APPLICS-959)

- packages/applications-service-api/__tests__/unit/utils/is-backoffice-case-reference.test.js
- packages/applications-service-api/src/utils/is-backoffice-case-reference.js
https://pins-ds.atlassian.net/browse/APPLICS-943
Assume case is BO if caseRef is 9 characters long.
> feat(api): assume BO case when case reference is 9 characters long

- .github/CODEOWNERS
- Add a CODEOWNERS file for specific configuration files and folders
> chore(tooling): add CODEOWNERS

- packages/forms-web-app/src/app.js
- packages/forms-web-app/src/robots.txt
* add a robots.txt file to limit crawler requests and block individual project representation pages
* robots.txt is made available at domain root
https://pins-ds.atlassian.net.mcas.ms/jira/software/c/projects/APPLICS/boards/242?selectedIssue=APPLICS-961
> feat: add robots.txt file

- packages/forms-web-app/src/pages/project-search/includes/projects.njk
https://pins-ds.atlassian.net/browse/APPLICS-308?atlOrigin=eyJpIjoiYzk2NTM1N2MzZjlkNDk2N2E4MGE1OWQzYTE1YWIxYTAiLCJwIjoiaiJ9
> fix: APPLICS-308 - Project search accessibility - No context for voiceover 

- README.md
- e2e-tests/package-lock.json
- package-lock.json
- package.json
[APPLICS 949](https://pins-ds.atlassian.net/browse/APPLICS-949): Dependabot updates
#1346 dependabot update express 4.19.2 > 4.20.0
#1315 dependabot update webpack 5.88.2 > 5.94.0
#1263 dependabot update azure-identity 4.2.1 > 4.3.0
#1329 dependabot update elliptic 6.5.4 > 6.5.7
#1273 dependabot update fast-xml-parser 4.3.2 > 4.4.1 	(wanted 4.4.1, auto updated to 4.5.0)
- e2e-tests pack has been run locally after merging above updates
- It would also be useful to run the e2e pipeline in the Dev environment once this PR is merged
> chore: merge dependabot updates

- packages/forms-web-app/src/pages/examination/_translations/__snapshots__/translations.test.js.snap
- packages/forms-web-app/src/pages/examination/_translations/cy.json
- packages/forms-web-app/src/pages/examination/_translations/en.json
APPLICS-925- https://pins-ds.atlassian.net/browse/APPLICS-925
- Update translations for adding another deadline item
> chore: content audit add another deadline item (APPLICS-925)

- packages/forms-web-app/src/pages/projects/register/_common/are-you-18/view.njk
- packages/forms-web-app/src/pages/projects/register/agent/are-they-18/view.njk
APPLICS-1004- https://pins-ds.atlassian.net/browse/APPLICS-1004
- Correct styling class for over 18 legend heading
> fix: correct styling class for over 18 check (APPLICS-1004)

- azure-pipelines-deploy.yml
- azure-pipelines-release.yml
Updating common pipeline tag in deploy and release pipelines as these pipelines refers to azure_web_app_deploy.yml
Change: Docker credentials are removed from 'azure_web_app_deploy.yml'
Ticket number: DEV-287
Ticket link: https://pins-ds.atlassian.net/browse/DEV-287
Parent ticket link: https://pins-ds.atlassian.net/browse/DEV-273
> fix(tooling): updating common pipeline tag to 3.18.1

- packages/forms-web-app/src/pages/process-guide/_translations/__snapshots__/translations.test.js.snap
- packages/forms-web-app/src/pages/process-guide/_translations/cy.json
- packages/forms-web-app/src/pages/process-guide/_translations/en.json
- packages/forms-web-app/src/pages/process-guide/_utils/__snapshots__/get-material-change-process-guide-stages.test.js.snap
* content amendment
https://pins-ds.atlassian.net.mcas.ms/jira/software/c/projects/APPLICS/boards/242?selectedIssue=APPLICS-986
> feat: amend material changes stage content

- packages/forms-web-app/src/pages/process-guide/_translations/__snapshots__/translations.test.js.snap
- packages/forms-web-app/src/pages/process-guide/_translations/cy.json
- packages/forms-web-app/src/pages/process-guide/_translations/en.json
- packages/forms-web-app/src/pages/process-guide/_utils/__snapshots__/get-material-change-process-guide-stages.test.js.snap
- packages/forms-web-app/src/pages/process-guide/_utils/get-material-change-process-guide-stages.js
* amend content on project stages for material changes examination stage
https://pins-ds.atlassian.net.mcas.ms/jira/software/c/projects/APPLICS/boards/242?selectedIssue=APPLICS-1001
> feat: amend material changes examination stage content

- packages/forms-web-app/src/pages/projects/register/_common/declaration/controller.js
- packages/forms-web-app/src/pages/projects/register/_common/declaration/controller.test.js
Update error page displayed for RTHYS failed registrations - missed in original PR.
https://pins-ds.atlassian.net.mcas.ms/jira/software/c/projects/APPLICS/boards/242?selectedIssue=APPLICS-950
> fix: update rthys error page path

- packages/applications-service-api/src/utils/document.mapper.js
https://pins-ds.atlassian.net/browse/APPLICS-917?atlOrigin=eyJpIjoiYWM2MzM4OWY2MzhmNGViMWJhYWMxMjQ0YjYxNmJlZGIiLCJwIjoiaiJ9
> fix: APPLICS-917 - Material change cases - FO Document page

- packages/applications-service-api/__tests__/unit/controllers/documents.v3.test.js
- packages/applications-service-api/__tests__/unit/services/document.backoffice.service.test.js
- packages/applications-service-api/__tests__/unit/services/document.ni.service.test.js
- packages/applications-service-api/src/controllers/documents.v3.js
- packages/applications-service-api/src/services/document.backoffice.service.js
- packages/applications-service-api/src/services/document.ni.service.js
- packages/applications-service-api/src/utils/document.mapper.js
https://pins-ds.atlassian.net/browse/APPLICS-917?atlOrigin=eyJpIjoiZWY1NjJkODg3NWMzNGQ1M2I5MmYwNTUzZDg2MmMyYWEiLCJwIjoiaiJ9
> fix: APPLICS-917: Add material change labels to documents

- packages/ni-redirects/src/config.prod.json
- packages/ni-redirects/src/config.test.json
Update config for ni-redirects:
- Change blob document url to more friendly name
> feat(ni-redirects): Update redirect url to friendly name

- packages/forms-web-app/src/app.js
- packages/forms-web-app/src/config.js
Ensure static assets have a non-zero max-age applied. To be improved in the future with immutable assets and cache-busting techniques.
> chore(web): add cache control max-age

- packages/applications-service-api/src/database/config/config.js
- packages/applications-service-api/src/lib/prisma.js
> chore(api): reduce prisma and sequelize logging

- packages/forms-web-app/src/lib/application-api-wrapper.js
Trying out minor change to help performance and to use it to deploy a change
> fix: remove log on api wrapper

- packages/ni-redirects/src/config.test.json
> feat: redirect docs TR010012 test

- packages/applications-service-api/__tests__/integration/applications.test.js
- packages/applications-service-api/__tests__/unit/repositories/project.backoffice.repository.test.js
- packages/applications-service-api/__tests__/unit/repositories/project.ni.repository.test.js
- packages/applications-service-api/src/repositories/project.backoffice.repository.js
- packages/applications-service-api/src/repositories/project.ni.repository.js
- packages/forms-web-app/src/pages/projects/all-updates/_utils/get-formatted-updates.js
- packages/forms-web-app/src/pages/projects/all-updates/_utils/get-page-data.js
- packages/forms-web-app/src/pages/projects/all-updates/controller.js
- packages/forms-web-app/src/pages/projects/all-updates/controller.test.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1147
- Adds welsh language flag to the `getPageData` which was being used down the chain but wasn't being passed. 
- Bonus addition in same PR is to search by caseReference, it might not be used by users are much but speeds up development and testing
> fix: welsh project updates

- packages/applications-service-api/__tests__/unit/utils/document.mapper.test.js
- packages/applications-service-api/src/utils/document.mapper.js
Prod issue retrospective fix (although its already been merged in from feature branch from the last released commit).
https://pins-ds.atlassian.net/browse/APPLICS-1170
> fix: developers applicant doc mapper

- packages/applications-service-api/__tests__/integration/applications.test.js
- packages/applications-service-api/__tests__/unit/repositories/project.ni.repository.test.js
- packages/applications-service-api/src/repositories/project.ni.repository.js
We don't want to search NI for cases that are BO integrated: https://pins-ds.atlassian.net/browse/APPLICS-1157
> feat: remove integration cases from ni on search

- packages/applications-service-api/__tests__/integration/applications.test.js
- packages/applications-service-api/__tests__/unit/repositories/project.backoffice.repository.test.js
- packages/applications-service-api/__tests__/unit/repositories/project.ni.repository.test.js
- packages/applications-service-api/src/repositories/project.backoffice.repository.js
- packages/applications-service-api/src/repositories/project.ni.repository.js
Tickets:
- https://pins-ds.atlassian.net/browse/APPLICS-1208
- https://pins-ds.atlassian.net/browse/APPLICS-1209
OR search brings back to many results so now we are searching for all words matching (order is not important). We also remove stop words (e.g. And, The, etc.). Lastly, removed firstName + lastName applicant search as that is not required.
> feat: improve project search

- packages/applications-service-api/__tests__/unit/utils/map-applications-to-csv.test.js
- packages/applications-service-api/src/utils/map-applications-to-csv.js
https://pins-ds.atlassian.net/browse/APPLICS-1249
-the dates were being returned as a unix timestamp, which excel had issues displaying. Fixed by applying formatting in stringify function.
> fix(web): fix csv download date format

- packages/forms-web-app/src/pages/projects/section-51/index/_utils/advice-helpers.js
https://pins-ds.atlassian.net/browse/APPLICS-1258
-lowercase the enquiry method before it's checked as it  comes as capitalised value from NI and lowercase value from CBOS
> fix(web): fix s51 enquiry method label (applics-1258)

- azure-pipelines-deploy-ni-redirects.yml
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1274
- Adds a print of the generated config
- Fix minor issue where spaces were retained in case references 
It will print this on the config:
> feat: print ni redirect case ref list

- packages/applications-service-api/__tests__/unit/repositories/advice.backoffice.repository.test.js
- packages/applications-service-api/__tests__/unit/repositories/advice.ni.repository.test.js
- packages/applications-service-api/src/repositories/advice.backoffice.repository.js
- packages/applications-service-api/src/repositories/advice.ni.repository.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1226
> feat: register of advice improve search

- packages/applications-service-api/__tests__/unit/repositories/document.backoffice.repository.test.js
- packages/applications-service-api/src/repositories/document.backoffice.repository.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1285
> feat: document secondary sort order

- packages/applications-service-api/src/repositories/document.backoffice.repository.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1368
Although its a bug we actually did not implemenent functionality to paginate in BO sourced cases, it only existed for NI sourced cases. This PR adds this functionality.
> fix: paginate cbos sourced docs

- packages/forms-web-app/src/pages/projects/_utils/get-application-data.js
Ticket: https://pins-ds.atlassian.net/browse/APPLICS-1329
> fix: handle welsh translations for multiple region cases

- packages/applications-service-api/__tests__/__data__/application.js
- packages/applications-service-api/__tests__/integration/applications.test.js
- packages/applications-service-api/__tests__/unit/controllers/applications.v2.test.js
- packages/applications-service-api/__tests__/unit/services/application.merge.service.test.js
- packages/applications-service-api/__tests__/unit/utils/application.mapper.test.js
- packages/applications-service-api/src/utils/application.mapper.js
- packages/forms-web-app/src/pages/projects/_utils/get-application-data.js
- packages/forms-web-app/src/pages/projects/index/_includes/stages/acceptance/description.njk
- packages/forms-web-app/src/pages/projects/index/_includes/stages/decision/description.njk
- packages/forms-web-app/src/pages/projects/index/_includes/stages/recommendation/description.njk
- packages/forms-web-app/src/pages/projects/index/_utils/is-backoffice-case-reference.js
- packages/forms-web-app/src/pages/projects/index/controller.component.test.js
- packages/forms-web-app/src/pages/projects/index/controller.js
- packages/forms-web-app/src/pages/projects/index/controller.test.js
[APPLICS-1321](https://pins-ds.atlassian.net/browse/APPLICS-1321): FO 3 key dates in the Project stage section
- Added the CBOS date key-value pairs to to:
- The data object returned from the database for NI and CBOS cases (and set the value to null for NI).
- The data object returned when CBOS application data is mapped back to legacy format.
- The data object that is created to be added to res.locals.
- Added a function to the project index controller to check if case has a CBOS case reference.
- Added conditional logic to the templates for the Acceptance, Recommendation and Decision stages to render CBOS dates for CBOS cases and auto-calculated dates for NI cases.
- Updated the API unit and integration tests.
- Updated the web app unit tests.
[APPLICS-1321]: …
> feat: replace calculated dates with cbos dates (applics 1321)

- docker-compose.yml
- packages/forms-web-app/src/config.js
- packages/forms-web-app/src/pages/index/controller.js
- packages/forms-web-app/src/pages/index/controller.test.js
- packages/forms-web-app/src/pages/index/view.njk
[APPLICS 1387](https://pins-ds.atlassian.net/browse/APPLICS-1387): Welsh migration - FO homepage banner
- Added the FEATURE_ALLOW_WELSH_CASES flag to hide the change in Prod until migration is complete.
- Conditionally rendered the final paragraph of the homepage banner based on the status of the feature flag.
- Updated the unit test for the controller.
> feat(web): update content in homepage banner (applics-1387)

- azure-pipelines-deploy.yml
> fix(infrastructure): updating pipeline template version

- azure-pipelines-variables.yml
> fix(infrastructure): adding app reg value

- packages/forms-web-app/__tests__/unit/lib/remove-unwanted-cookies.test.js
- packages/forms-web-app/__tests__/unit/middleware/remove-unwanted-cookies.test.js
- packages/forms-web-app/src/consts.js
- packages/forms-web-app/src/lib/remove-unwanted-cookies.js
- packages/forms-web-app/src/middleware/remove-unwanted-cookies.js
remove confusing cookie session const
> refactor(web): remove session cookie const

- packages/forms-web-app/src/pages/projects/section-51/index/_translations/cy.json
- packages/forms-web-app/src/pages/projects/section-51/index/_translations/cy.test.js
- packages/forms-web-app/src/pages/projects/section-51/index/_translations/en.json
- packages/forms-web-app/src/pages/projects/section-51/index/_translations/en.test.js
This PR updates the english and welsh content on the s51 advice page above the search box
https://pins-ds.atlassian.net/browse/APPLICS-1186
> refactor: update content on s51 advice page

- azure-pipelines-deploy.yml
Updating verify API deploy stage to using script from common pipeline template repository 
[DEV API deploy testing the changes](https://dev.azure.com/planninginspectorate/applications-service/_build/results?buildId=118947&view=logs&j=fc98f0bd-3d99-52ad-7de8-d37b2cd98270&t=8d9ecfdd-5eda-5e93-eca0-3035dc1a6b65)
> fix(tooling): updating deploy api to use updated git verify step

- docker-compose.yml
- packages/applications-service-api/__tests__/unit/services/application.backoffice.service.test.js
- packages/applications-service-api/__tests__/unit/services/application.merge.service.test.js
- packages/applications-service-api/__tests__/unit/services/application.ni.service.test.js
- packages/applications-service-api/__tests__/unit/utils/map-applications-to-csv.test.js
- packages/applications-service-api/src/lib/config.js
- packages/applications-service-api/src/services/application.backoffice.service.js
- packages/applications-service-api/src/services/application.merge.service.js
- packages/applications-service-api/src/services/application.ni.service.js
- packages/applications-service-api/src/utils/get-url-for-blob-store-docs.js
- packages/applications-service-api/src/utils/map-applications-to-csv.js
[Data quality guide for all projects download](https://pins-ds.atlassian.net/browse/APPLICS-1620)
- URL to the data quality guide is appended to .csv file for all projects.
- data quality guide spreadsheet is available on blob store for all environments.
- URL to the data quality guide spreadsheet changes according to runtime environment, between testing and prod. When in prod then url to Blob store for prod will be used, else url for Blob store for testing will be used.
> Data quality guide for all projects download

- packages/back-office-subscribers/host.json
remove logging overrides
https://pins-ds.atlassian.net/browse/DEV-555
> chore(functions): align function settings in host.json
